SELECT ID_SOGGETTO, CODICE_FISCALE_SOGGETTO, ID_UTENTE_INS, ID_UTENTE_AGG, ID_TIPO_SOGGETTO, DT_INSERIMENTO, DT_AGGIORNAMENTO, RICEVENTE_TRASF
 FROM PBANDI_T_SOGGETTO 
 WHERE upper( CODICE_FISCALE_SOGGETTO )= 'PCHMRC72A05H355F'
 AND ID_TIPO_SOGGETTO = 1;