/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.pbandi.pbweb.pbandisrv.business.neoflux;

public interface Task {
 String CARICAM_INDIC_PROG = "CARICAM-INDIC-PROG";
 String CARICAM_INDIC_AVVIO = "CARICAM-INDIC-AVVIO";
 String CHIUSURA_PROGETTO = "CHIUSURA-PROGETTO";
 String CHIUS_PROG_RINUNCIA = "CHIUS-PROG-RINUNCIA";
 String CHIUS_UFF_PROG = "CHIUS-UFF-PROG";
 String COMUNIC_FINE_PROG = "COMUNIC-FINE-PROG";
 String COMUNIC_RINUNCIA = "COMUNIC-RINUNCIA";
 String CONSULTA_LIQUID ="CONSULTA-LIQUID";
 String CRONOPROGRAMMA = "CRONOPROGRAMMA";
 String CRONOPROG_AVVIO = "CRONOPROG-AVVIO";
 String DATI_PROG = "DATI-PROG";
 String DICH_DI_SPESA = "DICH-DI-SPESA";
 String DICH_SPESA_INTEGRATIVA = "DICH-SPESA-INTEGRATIVA";
 String EROGAZIONE = "EROGAZIONE";
 String GEST_APPALTI = "GEST-APPALTI";
 String GEST_APPALTI_CONT_INCARICHI = "GEST-APPALTI-CONT-INCARICHI";//GESTION APPALTI CONTRATTI INCARICHI
 String GEST_CHECKLIST = "GEST-CHECKLIST";
 String GEST_FIDEIUSSIONI = "GEST-FIDEIUSSIONI";
 String GEST_SPESA_VALID = "GEST-SPESA-VALID";
 String LIQUIDAZIONE = "LIQUIDAZIONE";
 String MOD_EROG = "MOD-EROG";
 String MOD_REVOCA = "MOD-REVOCA";
 String MOD_RECUPERO = "MOD-RECUPERO";
 String PROP_RIM_CE = "PROP-RIM-CE";
 String QUADRO_PREVISIO = "QUADRO-PREVISIO";
 String RET_CRONOPROG = "RET-CRONOPROG";
 String RET_INDIC_PROG = "RET-INDIC-PROG";
 String REVOCA = "REVOCA";
 String RICH_CE_DOM = "RICH-CE-DOM";
 String RICH_EROG_CALC_CAU = "RICH-EROG-CALC-CAU";
 String RILEV_IRREGOLAR = "RILEV-IRREGOLAR";
 String RIM_CE = "RIM-CE";
 String RIM_CE_ISTR = "RIM-CE-ISTR";
 String RECUPERO = "RECUPERO";
 String SOPPRESSIONE = "SOPPRESSIONE";
 String VALID_DICH_SPESA = "VALID-DICH-SPESA"; 
 String VALID_DICH_SPESA_FINALE = "VALID-DICH-SPESA-FINALE";
 String GEST_AFFIDAMENTI = "GEST-AFFIDAMENTI";
 String GEST_AFFIDAMENTI_BEN = "GEST-AFFIDAMENTI-BEN";
}
