/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.pbandi.pbgestfinbo.integration.vo;


public class BoxListVO {

	private Boolean PBANDI_T_TRANSAZIONI_BANCA = false;
	private Boolean PBANDI_T_SEGNALAZ_CORTE_CONTI = false;
	private Boolean PBANDI_T_SALDO_STRALCIO = false;
	private Boolean PBANDI_T_REVOCA_BANCARIA = false;
	private Boolean PBANDI_T_PIANO_RIENTRO = false;
	private Boolean PBANDI_T_PASSAGGIO_PERDITA = false;
	private Boolean PBANDI_T_MESSA_IN_MORA = false;
	private Boolean PBANDI_T_LIBERAZ_GARANTE = false;
	private Boolean PBANDI_T_LIBERAZ_BANCA = false;
	private Boolean PBANDI_T_ISCRIZIONE_RUOLO = false;
	private Boolean PBANDI_T_ESCUSS_CONFIDI = false;
	private Boolean PBANDI_T_CESSIONE_QUOTA_FP = false;
	private Boolean PBANDI_T_AZIONE_RECUP_BANCA = false;
	private Boolean PBANDI_T_ANNOTAZ_GENERALI = false;
	private Boolean PBANDI_T_ABBATTIM_GARANZIE = false;
	private Boolean PBANDI_T_PROCEDURE_CONCORS = false;
	private Boolean PBANDI_T_CREDITORIE = false;
	private Boolean PBANDI_T_ALLUNG_PIANO_AMMORT = false;
	
	
	public BoxListVO(Boolean pBANDI_T_TRANSAZIONI_BANCA, Boolean pBANDI_T_SEGNALAZ_CORTE_CONTI,
			Boolean pBANDI_T_SALDO_STRALCIO, Boolean pBANDI_T_REVOCA_BANCARIA, Boolean pBANDI_T_PIANO_RIENTRO,
			Boolean pBANDI_T_PASSAGGIO_PERDITA, Boolean pBANDI_T_MESSA_IN_MORA, Boolean pBANDI_T_LIBERAZ_GARANTE,
			Boolean pBANDI_T_LIBERAZ_BANCA, Boolean pBANDI_T_ISCRIZIONE_RUOLO, Boolean pBANDI_T_ESCUSS_CONFIDI,
			Boolean pBANDI_T_CESSIONE_QUOTA_FP, Boolean pBANDI_T_AZIONE_RECUP_BANCA, Boolean pBANDI_T_ANNOTAZ_GENERALI,
			Boolean pBANDI_T_ABBATTIM_GARANZIE, Boolean pBANDI_T_PROCEDURE_CONCORS, Boolean pBANDI_T_CREDITORIE,
			Boolean pBANDI_T_ALLUNG_PIANO_AMMORT) {
		PBANDI_T_TRANSAZIONI_BANCA = pBANDI_T_TRANSAZIONI_BANCA;
		PBANDI_T_SEGNALAZ_CORTE_CONTI = pBANDI_T_SEGNALAZ_CORTE_CONTI;
		PBANDI_T_SALDO_STRALCIO = pBANDI_T_SALDO_STRALCIO;
		PBANDI_T_REVOCA_BANCARIA = pBANDI_T_REVOCA_BANCARIA;
		PBANDI_T_PIANO_RIENTRO = pBANDI_T_PIANO_RIENTRO;
		PBANDI_T_PASSAGGIO_PERDITA = pBANDI_T_PASSAGGIO_PERDITA;
		PBANDI_T_MESSA_IN_MORA = pBANDI_T_MESSA_IN_MORA;
		PBANDI_T_LIBERAZ_GARANTE = pBANDI_T_LIBERAZ_GARANTE;
		PBANDI_T_LIBERAZ_BANCA = pBANDI_T_LIBERAZ_BANCA;
		PBANDI_T_ISCRIZIONE_RUOLO = pBANDI_T_ISCRIZIONE_RUOLO;
		PBANDI_T_ESCUSS_CONFIDI = pBANDI_T_ESCUSS_CONFIDI;
		PBANDI_T_CESSIONE_QUOTA_FP = pBANDI_T_CESSIONE_QUOTA_FP;
		PBANDI_T_AZIONE_RECUP_BANCA = pBANDI_T_AZIONE_RECUP_BANCA;
		PBANDI_T_ANNOTAZ_GENERALI = pBANDI_T_ANNOTAZ_GENERALI;
		PBANDI_T_ABBATTIM_GARANZIE = pBANDI_T_ABBATTIM_GARANZIE;
		PBANDI_T_PROCEDURE_CONCORS = pBANDI_T_PROCEDURE_CONCORS;
		PBANDI_T_CREDITORIE = pBANDI_T_CREDITORIE;
		PBANDI_T_ALLUNG_PIANO_AMMORT = pBANDI_T_ALLUNG_PIANO_AMMORT;
	}


	public BoxListVO() {
	}


	public Boolean getPBANDI_T_TRANSAZIONI_BANCA() {
		return PBANDI_T_TRANSAZIONI_BANCA;
	}


	public void setPBANDI_T_TRANSAZIONI_BANCA(Boolean pBANDI_T_TRANSAZIONI_BANCA) {
		PBANDI_T_TRANSAZIONI_BANCA = pBANDI_T_TRANSAZIONI_BANCA;
	}


	public Boolean getPBANDI_T_SEGNALAZ_CORTE_CONTI() {
		return PBANDI_T_SEGNALAZ_CORTE_CONTI;
	}


	public void setPBANDI_T_SEGNALAZ_CORTE_CONTI(Boolean pBANDI_T_SEGNALAZ_CORTE_CONTI) {
		PBANDI_T_SEGNALAZ_CORTE_CONTI = pBANDI_T_SEGNALAZ_CORTE_CONTI;
	}


	public Boolean getPBANDI_T_SALDO_STRALCIO() {
		return PBANDI_T_SALDO_STRALCIO;
	}


	public void setPBANDI_T_SALDO_STRALCIO(Boolean pBANDI_T_SALDO_STRALCIO) {
		PBANDI_T_SALDO_STRALCIO = pBANDI_T_SALDO_STRALCIO;
	}


	public Boolean getPBANDI_T_REVOCA_BANCARIA() {
		return PBANDI_T_REVOCA_BANCARIA;
	}


	public void setPBANDI_T_REVOCA_BANCARIA(Boolean pBANDI_T_REVOCA_BANCARIA) {
		PBANDI_T_REVOCA_BANCARIA = pBANDI_T_REVOCA_BANCARIA;
	}


	public Boolean getPBANDI_T_PIANO_RIENTRO() {
		return PBANDI_T_PIANO_RIENTRO;
	}


	public void setPBANDI_T_PIANO_RIENTRO(Boolean pBANDI_T_PIANO_RIENTRO) {
		PBANDI_T_PIANO_RIENTRO = pBANDI_T_PIANO_RIENTRO;
	}


	public Boolean getPBANDI_T_PASSAGGIO_PERDITA() {
		return PBANDI_T_PASSAGGIO_PERDITA;
	}


	public void setPBANDI_T_PASSAGGIO_PERDITA(Boolean pBANDI_T_PASSAGGIO_PERDITA) {
		PBANDI_T_PASSAGGIO_PERDITA = pBANDI_T_PASSAGGIO_PERDITA;
	}


	public Boolean getPBANDI_T_MESSA_IN_MORA() {
		return PBANDI_T_MESSA_IN_MORA;
	}


	public void setPBANDI_T_MESSA_IN_MORA(Boolean pBANDI_T_MESSA_IN_MORA) {
		PBANDI_T_MESSA_IN_MORA = pBANDI_T_MESSA_IN_MORA;
	}


	public Boolean getPBANDI_T_LIBERAZ_GARANTE() {
		return PBANDI_T_LIBERAZ_GARANTE;
	}


	public void setPBANDI_T_LIBERAZ_GARANTE(Boolean pBANDI_T_LIBERAZ_GARANTE) {
		PBANDI_T_LIBERAZ_GARANTE = pBANDI_T_LIBERAZ_GARANTE;
	}


	public Boolean getPBANDI_T_LIBERAZ_BANCA() {
		return PBANDI_T_LIBERAZ_BANCA;
	}


	public void setPBANDI_T_LIBERAZ_BANCA(Boolean pBANDI_T_LIBERAZ_BANCA) {
		PBANDI_T_LIBERAZ_BANCA = pBANDI_T_LIBERAZ_BANCA;
	}


	public Boolean getPBANDI_T_ISCRIZIONE_RUOLO() {
		return PBANDI_T_ISCRIZIONE_RUOLO;
	}


	public void setPBANDI_T_ISCRIZIONE_RUOLO(Boolean pBANDI_T_ISCRIZIONE_RUOLO) {
		PBANDI_T_ISCRIZIONE_RUOLO = pBANDI_T_ISCRIZIONE_RUOLO;
	}


	public Boolean getPBANDI_T_ESCUSS_CONFIDI() {
		return PBANDI_T_ESCUSS_CONFIDI;
	}


	public void setPBANDI_T_ESCUSS_CONFIDI(Boolean pBANDI_T_ESCUSS_CONFIDI) {
		PBANDI_T_ESCUSS_CONFIDI = pBANDI_T_ESCUSS_CONFIDI;
	}


	public Boolean getPBANDI_T_CESSIONE_QUOTA_FP() {
		return PBANDI_T_CESSIONE_QUOTA_FP;
	}


	public void setPBANDI_T_CESSIONE_QUOTA_FP(Boolean pBANDI_T_CESSIONE_QUOTA_FP) {
		PBANDI_T_CESSIONE_QUOTA_FP = pBANDI_T_CESSIONE_QUOTA_FP;
	}


	public Boolean getPBANDI_T_AZIONE_RECUP_BANCA() {
		return PBANDI_T_AZIONE_RECUP_BANCA;
	}


	public void setPBANDI_T_AZIONE_RECUP_BANCA(Boolean pBANDI_T_AZIONE_RECUP_BANCA) {
		PBANDI_T_AZIONE_RECUP_BANCA = pBANDI_T_AZIONE_RECUP_BANCA;
	}


	public Boolean getPBANDI_T_ANNOTAZ_GENERALI() {
		return PBANDI_T_ANNOTAZ_GENERALI;
	}


	public void setPBANDI_T_ANNOTAZ_GENERALI(Boolean pBANDI_T_ANNOTAZ_GENERALI) {
		PBANDI_T_ANNOTAZ_GENERALI = pBANDI_T_ANNOTAZ_GENERALI;
	}


	public Boolean getPBANDI_T_ABBATTIM_GARANZIE() {
		return PBANDI_T_ABBATTIM_GARANZIE;
	}


	public void setPBANDI_T_ABBATTIM_GARANZIE(Boolean pBANDI_T_ABBATTIM_GARANZIE) {
		PBANDI_T_ABBATTIM_GARANZIE = pBANDI_T_ABBATTIM_GARANZIE;
	}


	public Boolean getPBANDI_T_PROCEDURE_CONCORS() {
		return PBANDI_T_PROCEDURE_CONCORS;
	}


	public void setPBANDI_T_PROCEDURE_CONCORS(Boolean pBANDI_T_PROCEDURE_CONCORS) {
		PBANDI_T_PROCEDURE_CONCORS = pBANDI_T_PROCEDURE_CONCORS;
	}


	public Boolean getPBANDI_T_CREDITORIE() {
		return PBANDI_T_CREDITORIE;
	}


	public void setPBANDI_T_CREDITORIE(Boolean pBANDI_T_CREDITORIE) {
		PBANDI_T_CREDITORIE = pBANDI_T_CREDITORIE;
	}


	public Boolean getPBANDI_T_ALLUNG_PIANO_AMMORT() {
		return PBANDI_T_ALLUNG_PIANO_AMMORT;
	}


	public void setPBANDI_T_ALLUNG_PIANO_AMMORT(Boolean pBANDI_T_ALLUNG_PIANO_AMMORT) {
		PBANDI_T_ALLUNG_PIANO_AMMORT = pBANDI_T_ALLUNG_PIANO_AMMORT;
	}


	@Override
	public String toString() {
		return "BoxListVO [PBANDI_T_TRANSAZIONI_BANCA=" + PBANDI_T_TRANSAZIONI_BANCA
				+ ", PBANDI_T_SEGNALAZ_CORTE_CONTI=" + PBANDI_T_SEGNALAZ_CORTE_CONTI + ", PBANDI_T_SALDO_STRALCIO="
				+ PBANDI_T_SALDO_STRALCIO + ", PBANDI_T_REVOCA_BANCARIA=" + PBANDI_T_REVOCA_BANCARIA
				+ ", PBANDI_T_PIANO_RIENTRO=" + PBANDI_T_PIANO_RIENTRO + ", PBANDI_T_PASSAGGIO_PERDITA="
				+ PBANDI_T_PASSAGGIO_PERDITA + ", PBANDI_T_MESSA_IN_MORA=" + PBANDI_T_MESSA_IN_MORA
				+ ", PBANDI_T_LIBERAZ_GARANTE=" + PBANDI_T_LIBERAZ_GARANTE + ", PBANDI_T_LIBERAZ_BANCA="
				+ PBANDI_T_LIBERAZ_BANCA + ", PBANDI_T_ISCRIZIONE_RUOLO=" + PBANDI_T_ISCRIZIONE_RUOLO
				+ ", PBANDI_T_ESCUSS_CONFIDI=" + PBANDI_T_ESCUSS_CONFIDI + ", PBANDI_T_CESSIONE_QUOTA_FP="
				+ PBANDI_T_CESSIONE_QUOTA_FP + ", PBANDI_T_AZIONE_RECUP_BANCA=" + PBANDI_T_AZIONE_RECUP_BANCA
				+ ", PBANDI_T_ANNOTAZ_GENERALI=" + PBANDI_T_ANNOTAZ_GENERALI + ", PBANDI_T_ABBATTIM_GARANZIE="
				+ PBANDI_T_ABBATTIM_GARANZIE + ", PBANDI_T_PROCEDURE_CONCORS=" + PBANDI_T_PROCEDURE_CONCORS
				+ ", PBANDI_T_CREDITORIE=" + PBANDI_T_CREDITORIE + ", PBANDI_T_ALLUNG_PIANO_AMMORT="
				+ PBANDI_T_ALLUNG_PIANO_AMMORT + "]";
	}
	
	
}
