/*
 * Copyright Regione Piemonte - 2024 
 * SPDX-License-Identifier: EUPL-1.2 
*/

import { DettaglioLiquidazioneVo } from "./dettaglio-liquidazione-vo";

export class DettaglioAttoDiLiquidazioneVO { 
    constructor(
        public annoAtto: string,
        public numeroAtto: string,
        public descAtto: string,
        public importoTotaleAtto: number,
        public descStatoAtto: string,
        public dtInserimentoAtto: Date,
        public dtAggiornamentoAtto: Date,
        public dtAggiornamentoBilancio: Date,
        public dtEmissioneAtto: Date,
        public dtScadenzaAtto: Date,
        public dtCompletamentoAtto: Date,
        public dtAnnullamentoAtto: Date,
        public dtRicezioneAtto: Date,
        public dtRifiutoRagioneria: Date,
        public dtRichiestaModifica: Date,
        public testoRichiestaModifica: string,
        public noteAtto: string,
        public liquidazioni: Array<DettaglioLiquidazioneVo>,
        public disettoreAppartenenza: string,
        public dienteCompetenza: string,
        public difunzionarioLiquidatore: string,
        public dinumeroTelefono: string,
        public didirigente: string,
        public dimodalitaAgevolazione: string,
        public dicausaleErogazione: string,
        public diquietanzante: string,
        public dicodiceFiscale: string,
        public difattura: boolean,
        public diestrattoCopiaProvvedimento: boolean,
        public didocumentazioneGiustificativa: boolean,
        public didichiarazione: boolean,
        public dialtro: string,
        public didataInserimento: Date,
        public didataAggiornamento: Date,
        public dimodalitaErogazione: string,
        public diestremiBancari: string,
        public dibeneficiarioCedente: string,
        public dibeneficiarioCeduto: string,
        public didataInserimentoBeneficiario: Date,
        public didataAggiornamentoBeneficiario: Date,
        public dimodalitaErogazioneBeneficiario: string,
        public diestremiBancariBeneficiario: string,
        public dbcodiceBeneficiarioBilancio: string,
        public dbdenominazione: string,
        public dbragioneSocialeAgg: string,
        public dbindirizzo: string,
        public dbcomune: string,
        public dbprovincia: string,
        public dbcodiceFiscale: string,
        public dbpartitaIVA: string,
        public dbdataInserimento: Date,
        public dbdataAggiornamento: Date,
        public dbemail: string,
        public dbtelefono: string,
        public dbfax: string,
        public dbindirizzoSecondaria: string,
        public dbcomuneSecondaria: string,
        public dbprovinciaSecondaria: string,
        public drtipoSoggetto: string,
        public drtipoRitenuta: string,
        public draliquotaRitenuta: string,
        public drsommeNonSoggette: string,
        public drsituazioneINPS: string,
        public drinpsaltraCassa: string,
        public drattivitaINPS: string,
        public drimponibile: string,
        public draltraCassaPrevid: string,
        public drrischioINAIL: string,
        public drperiodoAttivitaDal: Date,
        public drperiodoAttivitaAL: Date,
        public esito: boolean,
        public numeroDocumentoSpesa: string,
        public descStatoDocumento: string,
        public codiceErrore: string,
        public descStatoDocumentoContabilia: string
    ) { }
}