/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

SELECT
ID_SETTORE_ATTIVITA,
ID_ATTIVITA_ECONOMICA,
ID_ATTIVITA_ATECO,
COD_SETTORE,
DESC_SETTORE,
DESC_ATTIVITA_ECONOMICA,
COD_ATECO,
DESC_ATECO,
COD_ATECO||' - ' ||DESC_ATECO COD_DESC_ATECO,
COD_IGRUE_T6,
LIVELLO
FROM  PBANDI_D_SETTORE_ATTIVITA SETTORE 
join PBANDI_D_ATTIVITA_ATECO ATTATECO using (ID_SETTORE_ATTIVITA)
JOIN  PBANDI_D_ATTIVITA_ECONOMICA ATTECONOMICA USING ( ID_ATTIVITA_ECONOMICA)
WHERE   
        (TRUNC(SYSDATE)   >= NVL(TRUNC(ATTATECO.DT_INIZIO_VALIDITA), TRUNC(SYSDATE)-1)
and TRUNC(sysdate)        < NVL(TRUNC(ATTATECO.DT_FINE_VALIDITA), TRUNC(sysdate)  +1))
and (TRUNC(sysdate)       >= NVL(TRUNC(ATTECONOMICA.DT_INIZIO_VALIDITA), TRUNC(sysdate)-1)
and TRUNC(sysdate)        < NVL(TRUNC(ATTECONOMICA.DT_FINE_VALIDITA), TRUNC(sysdate)  +1))
and (TRUNC(sysdate)       >= NVL(TRUNC(SETTORE.DT_INIZIO_VALIDITA), TRUNC(sysdate)-1)
AND TRUNC(SYSDATE)        < NVL(TRUNC(SETTORE.DT_FINE_VALIDITA), TRUNC(SYSDATE)  +1))
order by COD_ATECO