/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

SELECT IND.CAP,
IND.CIVICO,
SOGG.CODICE_FISCALE_SOGGETTO CODICE_FISCALE,
P.CODICE_VISUALIZZATO,
ENTE.DENOMINAZIONE_ENTE_GIURIDICO DENOMINAZIONE,
IND.DESC_INDIRIZZO INDIRIZZO,
REC.EMAIL,
REC.FAX,
ENTE.ID_ENTE_GIURIDICO,
IND.ID_COMUNE,
IND.ID_COMUNE_ESTERO,
IND.ID_INDIRIZZO,
IND.ID_NAZIONE,
SP.ID_PROGETTO,
IND.ID_PROVINCIA,
IND.ID_REGIONE,
SE.ID_RECAPITI,
SE.ID_SEDE,
SEDE.PARTITA_IVA,
SOGG.ID_SOGGETTO,
REC.TELEFONO
FROM PBANDI.PBANDI_T_SOGGETTO SOGG,
  PBANDI_T_ENTE_GIURIDICO ENTE,
  PBANDI_R_SOGGETTO_PROGETTO SP,
  PBANDI_R_SOGG_PROGETTO_SEDE SE,
   PBANDI_T_SEDE SEDE,
  PBANDI_T_INDIRIZZO IND,
  PBANDI_T_PROGETTO P,
  PBANDI_T_RECAPITI REC
WHERE SOGG.ID_SOGGETTO            = ENTE.ID_SOGGETTO
AND SOGG.ID_SOGGETTO              = SP.ID_SOGGETTO
AND P.ID_PROGETTO=SP.ID_PROGETTO
AND SE.PROGR_SOGGETTO_PROGETTO = SP.PROGR_SOGGETTO_PROGETTO
AND SE.ID_TIPO_SEDE            =1 
AND SE.ID_SEDE            =SEDE.ID_SEDE
AND SE.ID_RECAPITI=REC.ID_RECAPITI(+)
AND NVL(TRUNC( SP.DT_FINE_VALIDITA), TRUNC(SYSDATE +1)) > TRUNC(SYSDATE)
AND NVL(TRUNC( ente.DT_FINE_VALIDITA), TRUNC(SYSDATE +1)) > TRUNC(SYSDATE)
AND IND.ID_INDIRIZZO = SE.ID_INDIRIZZO 
ORDER BY SP.DT_INIZIO_VALIDITA,ENTE.ID_ENTE_GIURIDICO  DESC