/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

 SELECT  PBANDI_T_PROGETTO.id_progetto,
  PBANDI_D_RUOLO_ENTE_COMPETENZA.DESC_BREVE_RUOLO_ENTE,
  PBANDI_T_DOMANDA.progr_bando_linea_intervento,
  PBANDI_T_ENTE_COMPETENZA.desc_ente,
  PBANDI_T_INDIRIZZO.desc_indirizzo || PBANDI_T_INDIRIZZO.civico as indirizzo,
  PBANDI_T_INDIRIZZO.cap,
  PBANDI_D_COMUNE.desc_comune,
  PBANDI_D_PROVINCIA.sigla_provincia 
FROM PBANDI_T_PROGETTO,
  PBANDI_T_DOMANDA,
  PBANDI_T_ENTE_COMPETENZA,
  PBANDI_T_INDIRIZZO,
  PBANDI_D_COMUNE,
  PBANDI_D_RUOLO_ENTE_COMPETENZA,
  PBANDI_D_PROVINCIA,
  PBANDI_V_BANDO_LINEA_ENTE_COMP  
WHERE PBANDI_T_DOMANDA.id_domanda                               = PBANDI_T_PROGETTO.id_domanda
and PBANDI_V_BANDO_LINEA_ENTE_COMP.PROGR_BANDO_LINEA_INTERVENTO = PBANDI_T_DOMANDA.PROGR_BANDO_LINEA_INTERVENTO
and  PBANDI_T_ENTE_COMPETENZA.ID_ENTE_COMPETENZA                = PBANDI_V_BANDO_LINEA_ENTE_COMP.ID_ENTE_COMPETENZA
AND PBANDI_D_COMUNE.id_comune                                   = PBANDI_T_INDIRIZZO.id_comune
and PBANDI_D_PROVINCIA.ID_PROVINCIA                             = PBANDI_D_COMUNE.ID_PROVINCIA
and PBANDI_V_BANDO_LINEA_ENTE_COMP.ID_RUOLO_ENTE_COMPETENZA     = PBANDI_D_RUOLO_ENTE_COMPETENZA.ID_RUOLO_ENTE_COMPETENZA
AND PBANDI_T_INDIRIZZO.id_indirizzo                             = PBANDI_V_BANDO_LINEA_ENTE_COMP.id_indirizzo  
and PBANDI_T_ENTE_COMPETENZA.ID_ENTE_COMPETENZA                 = PBANDI_V_BANDO_LINEA_ENTE_COMP.ID_ENTE_COMPETENZA