/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

SELECT DISTINCT
PBANDI_T_PROGETTO.CODICE_VISUALIZZATO  AS CODICE_PROGETTO ,
PBANDI_T_PROGETTO.TITOLO_PROGETTO,
DESC_MODALITA_PAGAMENTO,
TFILE.DT_INSERIMENTO  ,
TFILE.DT_AGGIORNAMENTO ,
NVL2(DT_PAGAMENTO,DT_PAGAMENTO,DT_VALUTA) AS DT_PAGAMENTO,
ID_PAGAMENTO,
DOCINDEX.ID_DOCUMENTO_INDEX ,
ID_FOLDER ,
FILE_ENTITA.ID_ENTITA ,
ID_MODALITA_PAGAMENTO,
PBANDI_T_FOLDER.ID_SOGGETTO_BEN,
FILE_ENTITA.ID_TARGET,
IMPORTO_PAGAMENTO,
TFILE.NOME_FILE,
TFILE.SIZE_FILE,
ID_DOCUMENTO_DI_SPESA,
NUMERO_DOCUMENTO ,
DT_EMISSIONE_DOCUMENTO ,
DESC_TIPO_DOCUMENTO_SPESA,
FORNITORE.CODICE_FISCALE_FORNITORE AS CF_FORNITORE,
NVL(FORNITORE.DENOMINAZIONE_FORNITORE,FORNITORE.COGNOME_FORNITORE||' '||FORNITORE.NOME_FORNITORE) AS NOME_FORNITORE ,
RBLI.NOME_BANDO_LINEA AS DESC_BANDO_LINEA,
RBLI.PROGR_BANDO_LINEA_INTERVENTO AS PROGR_BANDO_LINEA_INTERVENTO
FROM PBANDI_T_FILE TFILE
JOIN PBANDI_T_DOCUMENTO_INDEX DOCINDEX ON (DOCINDEX.ID_DOCUMENTO_INDEX=TFILE.ID_DOCUMENTO_INDEX)
JOIN PBANDI_T_FILE_ENTITA FILE_ENTITA ON FILE_ENTITA.ID_FILE=TFILE.ID_FILE AND FILE_ENTITA.ID_ENTITA=(SELECT ID_ENTITA FROM PBANDI_C_ENTITA WHERE UPPER(NOME_ENTITA)=UPPER('PBANDI_T_PAGAMENTO'))
JOIN PBANDI_T_PAGAMENTO ON (FILE_ENTITA.ID_TARGET=PBANDI_T_PAGAMENTO.ID_PAGAMENTO)
JOIN PBANDI_D_MODALITA_PAGAMENTO USING (ID_MODALITA_PAGAMENTO)
JOIN PBANDI_T_FOLDER USING (ID_FOLDER)
JOIN PBANDI_R_PAGAMENTO_DOC_SPESA USING(ID_PAGAMENTO)
JOIN PBANDI_T_DOCUMENTO_DI_SPESA USING (ID_DOCUMENTO_DI_SPESA)
JOIN PBANDI_T_FORNITORE FORNITORE USING(ID_FORNITORE)
JOIN PBANDI_D_TIPO_DOCUMENTO_SPESA   USING(ID_TIPO_DOCUMENTO_SPESA)
JOIN PBANDI_R_DOC_SPESA_PROGETTO  USING (ID_DOCUMENTO_DI_SPESA)
JOIN PBANDI_T_PROGETTO ON PBANDI_R_DOC_SPESA_PROGETTO.ID_PROGETTO=PBANDI_T_PROGETTO.ID_PROGETTO
JOIN PBANDI_T_DOMANDA  ON PBANDI_T_PROGETTO.ID_DOMANDA= PBANDI_T_DOMANDA.ID_DOMANDA
JOIN PBANDI_R_BANDO_LINEA_INTERVENT RBLI ON PBANDI_T_DOMANDA.PROGR_BANDO_LINEA_INTERVENTO = RBLI.PROGR_BANDO_LINEA_INTERVENTO
