/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

  SELECT CMS.ID_CARICA_MASS_DOC_SPESA,
        ID_SCARTI_CARICA_MAS_PAG,
        nvl(DESC_TIPO_DOC_SPESA,'') ||
        nvl2( NUMERO_DOCUMENTO,' '||NUMERO_DOCUMENTO,'') ||
        nvl2(DT_DOCUMENTO,' '||to_char(DT_DOCUMENTO,'dd/MM/YYYY'),'') ||
        nvl2(CODICE_FISCALE_FORNITORE,' '||CODICE_FISCALE_FORNITORE,'') desc_documento,
        nvl( DESC_MODALITA_PAGAMENTO,'') ||
        nvl2( IMPORTO_PAGAMENTO,' '||IMPORTO_PAGAMENTO,'') ||
        nvl2( DT_PAGAMENTO,' '||to_char(DT_PAGAMENTO,'dd/MM/YYYY'),'') desc_pagamento,
        SCARTI.CODICE_ERRORE,
        ERR.DESCRIZIONE ERRORE_WARNING,
        DT_VALIDAZIONE
 FROM PBANDI_T_CARICA_MASS_DOC_SPESA CMS 
 JOIN
 PBANDI_T_SCARTI_CARICA_MAS_PAG SCARTI
 ON CMS.ID_CARICA_MASS_DOC_SPESA=SCARTI.ID_CARICA_MASS_DOC_SPESA
 LEFT OUTER JOIN PBANDI_D_MODALITA_PAGAMENTO MODPAG ON
 SCARTI.DESC_BREVE_MODALITA_PAGAMENTO=MODPAG.DESC_BREVE_MODALITA_PAGAMENTO
 LEFT OUTER JOIN PBANDI_D_ERRORE_BATCH ERR 
 ON SCARTI.CODICE_ERRORE=ERR.CODICE_ERRORE