/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

select 
DT_AGGIORNAMENTO, PBANDI_R_CONTO_ECONOM_MOD_AGEV.ID_MODALITA_AGEVOLAZIONE, 
QUOTA_IMPORTO_AGEVOLATO, ID_CONTO_ECONOMICO, 
PBANDI_R_CONTO_ECONOM_MOD_AGEV.ID_UTENTE_INS, PBANDI_R_CONTO_ECONOM_MOD_AGEV.ID_UTENTE_AGG, DT_INSERIMENTO, 
QUOTA_IMPORTO_RICHIESTO, PERC_IMPORTO_AGEVOLATO, PBANDI_R_BANDO_MODALITA_AGEVOL.ID_BANDO
from PBANDI_R_CONTO_ECONOM_MOD_AGEV, PBANDI_R_BANDO_MODALITA_AGEVOL
where PBANDI_R_CONTO_ECONOM_MOD_AGEV.ID_MODALITA_AGEVOLAZIONE = PBANDI_R_BANDO_MODALITA_AGEVOL.ID_MODALITA_AGEVOLAZIONE
and QUOTA_IMPORTO_AGEVOLATO > 0
and PBANDI_R_BANDO_MODALITA_AGEVOL.FLAG_LIQUIDAZIONE = 'S'