/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

SELECT R.*,
  REG.DESC_BREVE_REGOLA
  ||' - '
  || REG.DESC_REGOLA AS DESC_REGOLA_COMPOSTA,
  ANA.DESC_TIPO_ANAGRAFICA
  ||NVL2(BEN.DESC_TIPO_BENEFICIARIO, ' - '
  ||BEN.DESC_TIPO_BENEFICIARIO, '') AS ANAGRAFICA_BENEFICIARIO,
  'Tipo anagrafica'                 AS TIPO_ASSOCIAZIONE
FROM PBANDI_R_REGOLA_TIPO_ANAG R,
  PBANDI_D_TIPO_BENEFICIARIO BEN,
  PBANDI_D_TIPO_ANAGRAFICA ANA,
  PBANDI_C_REGOLA REG
WHERE ANA.ID_TIPO_ANAGRAFICA(+) = R.ID_TIPO_ANAGRAFICA
AND BEN.ID_TIPO_BENEFICIARIO(+) = R.ID_TIPO_BENEFICIARIO
AND REG.ID_REGOLA               = R.ID_REGOLA
AND NVL(TRUNC(BEN.DT_FINE_VALIDITA), TRUNC(SYSDATE+1)) > TRUNC(SYSDATE)
AND NVL(TRUNC(ANA.DT_FINE_VALIDITA), TRUNC(SYSDATE+1)) > TRUNC(SYSDATE)
AND NVL(TRUNC(REG.DT_FINE_VALIDITA), TRUNC(SYSDATE+1)) > TRUNC(SYSDATE)