/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

select 
PBANDI_T_IRREGOLARITA.id_progetto,
PBANDI_T_IRREGOLARITA.ID_IRREGOLARITA,
DESC_TIPO_IRREGOLARITA TIPO_IRREGOLARITA,
NOTE_PRATICA_USATA,
ID_REVOCA,
QUOTA_IRREG,
IMPORTO_IRREGOLARITA,
PBANDI_T_IRREGOLARITA.DT_FINE_VALIDITA,
periodo.DESC_PERIODO_VISUALIZZATA,
DESC_MOTIVO_REVOCA MOTIVO_REVOCA_IRREGOLARITA,
PBANDI_T_IRREGOLARITA.IMPORTO_AGEVOLAZIONE_IRREG
from 
PBANDI_T_IRREGOLARITA 
left join PBANDI_D_TIPO_IRREGOLARITA using(ID_TIPO_IRREGOLARITA)
left join PBANDI_D_MOTIVO_REVOCA using(ID_MOTIVO_REVOCA)
left join PBANDI_R_REVOCA_IRREG on  PBANDI_T_IRREGOLARITA.ID_IRREGOLARITA =PBANDI_R_REVOCA_IRREG.ID_IRREGOLARITA, 
PBANDI_T_PERIODO periodo
WHERE 
PBANDI_T_IRREGOLARITA.ID_PERIODO = PERIODO.ID_PERIODO