/*
 * Copyright Regione Piemonte - 2024 
 * SPDX-License-Identifier: EUPL-1.2 
*/

import { EconomiaPerDatiGeneraliDTO } from "./economia-dati-generali-vo"
import { ImportoAgevolatoDTO } from "./importo-agevolato-vo"
import { ImportoDescrizioneDTO } from "./importo-descrizione-vo"
import { SedeDTO } from "./sede-vo"

export class DatiGeneraliDTO { 
    constructor(
        public acronimo: string,
        public codiceDichiarazione: string,
        public codiceProgetto: string,
        public civicoSedeLegale: string,
        public codIstatComuneSedeLegale: string,
        public comuneSedeLegale: string,
        public cup: string,
        public descrizioneBando: string,
        public descBreveLineaNormativa: string,
        public dtConcessione: Date,
        public dtDichiarazione: Date,
        public dtPresentazioneDomanda: Date,
        public descrizioneBeneficiario: string,
        public flagFirmaCartacea: string,
        public idBandoLinea: number,
        public idDichiarazione: number,
        public idDimensioneImpresa: number,
        public idDocumentoIndexDichiarazione: number,
        public idDocIndexComunicFineProgetto: number,
        public idFormaGiuridica: number,
        public idProcesso: number,
        public idRegione: number,
        public importoAgevolato: number,
        public importiAgevolati: Array<ImportoAgevolatoDTO>,
        public importoCertificatoNettoUltimaPropAppr: number,
        public revoche: Array<ImportoDescrizioneDTO>,
        public recuperi: Array<ImportoDescrizioneDTO>,
        public preRecuperi: Array<ImportoDescrizioneDTO>,
        public erogazioni: Array<ImportoDescrizioneDTO>,
        public importoRendicontato: number,
        public importoQuietanzato: number,
        public importoValidatoNettoRevoche: number,
        public importoSoppressioni: number,
        public importoCofinanziamentoPubblico: number,
        public importoCofinanziamentoPrivato: number,
        public importoAmmesso: number,
        public isCapofila: boolean,
        public isGestitoGefo: boolean,
        public pIvaSedeLegale: string,
        public sedeIntervento: string,
        public sedeLegale: string,
        public pIvaSedeIntervento: string,
        public protocollo: string,
        public regolaDematAttiva: boolean,
        public statoDichiarazione: string,
        public titoloBando: string,
        public titoloProgetto: string,
        public viaSedeLegale: string,
        public idComunicazFineProg: number,
        public statoDichiarazionePiuGreen: string,
        public flagFirmaCartaceaPiuGreen: string,
        public idDocIndexComunicFineProgettoPiuGreen: number,
        public protocolloPiuGreen: string,
        public idComunicazFineProgPiuGreen: number,
        public dtComunicazione: string,
        public dtComunicazionePiuGreen: string,
        public flagPubblicoPrivato: number,
        public codUniIpa: string,
        public idEnteGiuridico: number,
        public sedi: Array<SedeDTO>,
        public idLineaDiIntervento: number,
        public idTipoOperazione: number,
        public economie: Array<EconomiaPerDatiGeneraliDTO>,
        public isBandoCultura: boolean,
        public importoAmmessoVociDiEntrata: number,
    ) { }
}