select 
SOG.CODICE_FISCALE_SOGGETTO,
PF.COGNOME,
PF.NOME,
PF.SESSO,
PF.DT_NASCITA,
INDI.DESC_INDIRIZZO,
INDI.CAP,
INDI.CIVICO,
REC.EMAIL,
REC.TELEFONO,
REC.FAX,
NAZR.ID_NAZIONE ID_NAZIONE_RES,
NAZR.DESC_NAZIONE DESC_NAZIONE_RES,
REGRE.ID_REGIONE ID_REGIONE_RES,
REGRE.DESC_REGIONE DESC_REGIONE_RES,
PROVR.ID_PROVINCIA ID_PROVINCIA_RES,
PROVR.DESC_PROVINCIA DESC_PROVINCIA_RES,
COMUR.ID_COMUNE ID_COMUNE_RES,
COMUR.DESC_COMUNE DESC_COMUNE_RES,
COMUREST.ID_COMUNE ID_COMUNE_ESTERO_RES,
COMUREST.DESC_COMUNE DESC_COMUNE_ESTERO_RES,
NAZN.ID_NAZIONE ID_NAZIONE_NASCITA,
NAZN.DESC_NAZIONE DESC_NAZIONE_NASCITA,
REGN.ID_REGIONE ID_REGIONE_NASCITA,
REGN.DESC_REGIONE DESC_REGIONE_NASCITA,
PROVN.ID_PROVINCIA ID_PROVINCIA_NASCITA,
PROVN.DESC_PROVINCIA DESC_PROVINCIA_NASCITA,
COMUN.id_COMUNE id_COMUNE_NASCITA,
COMUN.DESC_COMUNE DESC_COMUNE_NASCITA,
COMUNEST.ID_COMUNE id_COMUNE_ESTERO_NASCITA,
COMUNEST.DESC_COMUNE DESC_COMUNE_ESTERO_NASCITA
from PBANDI_T_SOGGETTO SOG, PBANDI_R_SOGGETTO_PROGETTO SP, PBANDI_T_PERSONA_FISICA PF, 
PBANDI_T_INDIRIZZO INDI, PBANDI_T_RECAPITI REC,
PBANDI_D_COMUNE COMUR, PBANDI_D_COMUNE COMUREST, PBANDI_D_NAZIONE NAZR, PBANDI_D_PROVINCIA PROVR, PBANDI_D_REGIONE REGRE,
PBANDI_D_COMUNE COMUN, PBANDI_D_COMUNE COMUNEST, PBANDI_D_NAZIONE NAZN, PBANDI_D_PROVINCIA PROVN, PBANDI_D_REGIONE REGN
where SOG.ID_SOGGETTO = PF.ID_SOGGETTO(+)
AND SOG.ID_SOGGETTO = SP.ID_SOGGETTO(+)
AND SP.ID_INDIRIZZO_PERSONA_FISICA = INDI.ID_INDIRIZZO(+)
AND SP.ID_RECAPITI_PERSONA_FISICA = REC.ID_RECAPITI(+)
AND INDI.ID_NAZIONE = NAZR.ID_NAZIONE(+)
AND INDI.ID_COMUNE = COMUR.ID_COMUNE(+)
AND INDI.ID_COMUNE_ESTERO = COMUREST.ID_COMUNE(+)
AND INDI.ID_PROVINCIA = PROVR.ID_PROVINCIA(+)
AND INDI.ID_REGIONE = REGRE.ID_REGIONE(+)
AND PF.ID_COMUNE_ITALIANO_NASCITA = COMUN.ID_COMUNE(+)
AND PF.ID_COMUNE_ESTERO_NASCITA = COMUNEST.ID_COMUNE(+)
AND PF.ID_NAZIONE_NASCITA = NAZN.ID_NAZIONE(+)
AND COMUN.ID_PROVINCIA = PROVN.ID_PROVINCIA(+)
AND PROVN.ID_REGIONE = REGN.ID_REGIONE(+)
AND SOG.ID_TIPO_SOGGETTO = 1
GROUP BY 
SOG.CODICE_FISCALE_SOGGETTO,
PF.COGNOME,
PF.NOME,
PF.SESSO,
PF.DT_NASCITA,
INDI.DESC_INDIRIZZO,
INDI.CAP,
INDI.CIVICO,
REC.EMAIL,
REC.TELEFONO,
REC.FAX,
NAZR.ID_NAZIONE,
NAZR.DESC_NAZIONE,
REGRE.ID_REGIONE,
REGRE.DESC_REGIONE,
PROVR.ID_PROVINCIA,
PROVR.DESC_PROVINCIA,
COMUR.ID_COMUNE,
COMUR.DESC_COMUNE,
COMUREST.ID_COMUNE,
COMUREST.DESC_COMUNE,
NAZN.ID_NAZIONE,
NAZN.DESC_NAZIONE,
REGN.ID_REGIONE,
REGN.DESC_REGIONE,
PROVN.ID_PROVINCIA,
PROVN.DESC_PROVINCIA,
COMUN.id_COMUNE,
COMUN.DESC_COMUNE,
COMUNEST.id_COMUNE,
COMUNEST.DESC_COMUNE
order by 
PF.COGNOME, 
PF.NOME, 
PF.SESSO, 
PF.DT_NASCITA