/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

/* ---------------------------------------------------------------------- */
/* Script generated with: DeZign for Databases v6.2.1                     */
/* Target DBMS:           Oracle 11g                                      */
/* Project file:          Area_Crediti_modello_fisico.dez                 */
/* Project name:                                                          */
/* Author:                                                                */
/* Script type:           Database creation script                        */
/* Created on:            2021-11-05 20:23                                */
/* ---------------------------------------------------------------------- */


/* ---------------------------------------------------------------------- */
/* Sequences                                                              */
/* ---------------------------------------------------------------------- */



CREATE SEQUENCE SEQ_PBANDI_T_SOGG_STATO_AZI
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    noorder;

CREATE SEQUENCE SEQ_PBANDI_T_SOGG_RATING
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    noorder;

CREATE SEQUENCE SEQ_PBANDI_R_SOG_PROG_STA_CRED
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    noorder;

CREATE SEQUENCE SEQ_PBANDI_R_SOG_PROG_CLA_RISC
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    noorder;
	
-- Monitoraggio
--PBANDI_T_REVOCA_BANCARIA
CREATE SEQUENCE SEQ_PBANDI_T_REVOCA_BANCARIA
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    noorder;
	
--PBANDI_T_AZIONE_RECUP_BANCA
CREATE SEQUENCE SEQ_PBANDI_T_AZION_RECUP_BANCA
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    noorder;
	
--PBANDI_T_LIBERAZ_GARANTE
CREATE SEQUENCE SEQ_PBANDI_T_LIBERAZ_GARANTE
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    noorder;
	
--PBANDI_T_ABBATTIM_GARANZIE
CREATE SEQUENCE SEQ_PBANDI_T_ABBATTIM_GARANZIE
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    noorder;
	
--PBANDI_T_ESCUSS_CONFIDI
CREATE SEQUENCE SEQ_PBANDI_T_ESCUSS_CONFIDI
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    noorder;
	
--PBANDI_T_PIANO_RIENTRO  
CREATE SEQUENCE SEQ_PBANDI_T_PIANO_RIENTRO
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    noorder;

--PBANDI_T_SALDO_STRALCIO
CREATE SEQUENCE SEQ_PBANDI_T_SALDO_STRALCIO
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    noorder;
	
--PBANDI_T_PASSAGGIO_PERDITA 
CREATE SEQUENCE SEQ_PBANDI_T_PASSAGGIO_PERDITA
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    noorder;
	
--PBANDI_T_LIBERAZ_BANCA
CREATE SEQUENCE SEQ_PBANDI_T_LIBERAZ_BANCA
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    noorder;
	
--PBANDI_T_MESSA_IN_MORA
CREATE SEQUENCE SEQ_PBANDI_T_MESSA_IN_MORA
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    noorder;
	
--PBANDI_T_ANNOTAZ_GENERALI
CREATE SEQUENCE SEQ_PBANDI_T_ANNOTAZ_GENERALI
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    nocycle
    noorder;
	
/* ---------------------------------------------------------------------- */
/* Tables                                                                 */
/* ---------------------------------------------------------------------- */


/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_D_STATO_AZIENDA"                                     */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_D_STATO_AZIENDA (
    ID_STATO_AZIENDA NUMBER(3) NOT NULL,
    DESC_BREVE_STATO_AZIENDA VARCHAR2(20) NOT NULL,
    DESC_STATO_AZIENDA VARCHAR2(255) NOT NULL,
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    CONSTRAINT PK_PBANDI_D_STATO_AZIENDA PRIMARY KEY (ID_STATO_AZIENDA)
);

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_T_SOGG_STATO_AZIENDA"                                */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_T_SOGG_STATO_AZIENDA (
    ID_SOGGETTO_STATO_AZIENDA NUMBER(8) NOT NULL,
    ID_SOGGETTO NUMBER(8) NOT NULL,
    ID_STATO_AZIENDA NUMBER(3) NOT NULL,
    ID_UTENTE_INS NUMBER(8) NOT NULL,
    ID_UTENTE_AGG NUMBER(8),
    DT_INSERIMENTO DATE NOT NULL,
    DT_AGGIORNAMENTO DATE,
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    CONSTRAINT PK_PBANDI_T_SOGG_STATO_AZIENDA PRIMARY KEY (ID_SOGGETTO_STATO_AZIENDA)
);

CREATE INDEX IE1_PBANDI_T_SOG_STATO_AZIENDA ON PBANDI_T_SOGG_STATO_AZIENDA (ID_SOGGETTO);

CREATE INDEX IE2_PBANDI_T_SOG_STATO_AZIENDA ON PBANDI_T_SOGG_STATO_AZIENDA (ID_STATO_AZIENDA);

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_D_STATO_CREDITO_FP"                                  */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_D_STATO_CREDITO_FP (
    ID_STATO_CREDITO_FP NUMBER(3) NOT NULL,
    DESC_BREVE_STATO_CREDITO_FP VARCHAR2(20) NOT NULL,
    DESC_STATO_CREDITO_FP VARCHAR2(255) NOT NULL,
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    CONSTRAINT PK_PBANDI_D_STATO_CREDITO_FP PRIMARY KEY (ID_STATO_CREDITO_FP)
);

COMMENT ON TABLE PBANDI_D_STATO_CREDITO_FP IS 'Tabella stati credito Finpiemonte';

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_R_SOGG_PROG_STA_CRED_FP"                             */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_R_SOGG_PROG_STA_CRED_FP (
    ID_SOGG_PROG_STATO_CREDITO_FP NUMBER(8) NOT NULL,
    PROGR_SOGGETTO_PROGETTO NUMBER(8) NOT NULL,
    ID_STATO_CREDITO_FP NUMBER(3) NOT NULL,
    ID_UTENTE_INS NUMBER(8) NOT NULL,
    ID_UTENTE_AGG NUMBER(8),
    DT_INSERIMENTO DATE NOT NULL,
    DT_AGGIORNAMENTO DATE,
    CONSTRAINT PK_PBANDI_R_SOGG_PROG_STA_CRED PRIMARY KEY (ID_SOGG_PROG_STATO_CREDITO_FP)
);

CREATE INDEX IE1_PBANDI_R_SOG_PROG_STA_CRED ON PBANDI_R_SOGG_PROG_STA_CRED_FP (PROGR_SOGGETTO_PROGETTO);

CREATE INDEX IE2_PBANDI_R_SOG_PROG_STA_CRED ON PBANDI_R_SOGG_PROG_STA_CRED_FP (ID_STATO_CREDITO_FP);

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_D_RATING"                                            */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_D_RATING (
    ID_RATING NUMBER(3) NOT NULL,
    CODICE_RATING VARCHAR2(3) NOT NULL,
    DESC_BREVE_RATING VARCHAR2(20) NOT NULL,
    DESC_RATING VARCHAR2(255) NOT NULL,
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    ID_PROVIDER NUMBER(3) NOT NULL,
    CONSTRAINT PK_PBANDI_D_RATING PRIMARY KEY (ID_RATING)
);

CREATE INDEX IE1_PBANDI_PBANDI_D_RATING ON PBANDI_D_RATING (ID_PROVIDER);

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_T_SOGGETTO_RATING"                                   */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_T_SOGGETTO_RATING (
    ID_SOGGETTO_RATING NUMBER(8) NOT NULL,
    ID_SOGGETTO NUMBER(8) NOT NULL,
    ID_RATING NUMBER(3) NOT NULL,
    DT_CLASSIFICAZIONE DATE NOT NULL,
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    ID_UTENTE_INS NUMBER(8) NOT NULL,
    ID_UTENTE_AGG NUMBER(8),
    DT_INSERIMENTO DATE NOT NULL,
    DT_AGGIORNAMENTO DATE,
    CONSTRAINT PK_PBANDI_T_SOGGETTO_RATING PRIMARY KEY (ID_SOGGETTO_RATING)
);

CREATE INDEX IE1_PBANDI_T_SOGGETTO_RATING ON PBANDI_T_SOGGETTO_RATING (ID_SOGGETTO);

CREATE INDEX IE2_PBANDI_T_SOGGETTO_RATING ON PBANDI_T_SOGGETTO_RATING (ID_RATING);

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_D_CLASSE_RISCHIO"                                    */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_D_CLASSE_RISCHIO (
    ID_CLASSE_RISCHIO NUMBER(3) NOT NULL,
    DESC_BREVE_CLASSE_RISCHIO VARCHAR2(20) NOT NULL,
    DESC_CLASSE_RISCHIO VARCHAR2(255) NOT NULL,
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    CONSTRAINT PK_PBANDI_D_CLASSE_RISCHIO PRIMARY KEY (ID_CLASSE_RISCHIO)
);

COMMENT ON TABLE PBANDI_D_CLASSE_RISCHIO IS 'Tabella stati credito Finpiemonte';

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_R_SOGG_PROG_CLA_RISCHIO"                             */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_R_SOGG_PROG_CLA_RISCHIO (
    ID_SOGG_PROG_CLA_RISCHIO NUMBER(8) NOT NULL,
    PROGR_SOGGETTO_PROGETTO NUMBER(8) NOT NULL,
    ID_CLASSE_RISCHIO NUMBER(3) NOT NULL,
    ID_UTENTE_INS NUMBER(8) NOT NULL,
    ID_UTENTE_AGG NUMBER(8),
    DT_INSERIMENTO DATE NOT NULL,
    DT_AGGIORNAMENTO DATE,
    CONSTRAINT PK_PBANDI_R_SOGG_PROG_CLA_RISC PRIMARY KEY (ID_SOGG_PROG_CLA_RISCHIO)
);


CREATE INDEX IE1_PBANDI_R_SOG_PROG_CLA_RISC ON PBANDI_R_SOGG_PROG_CLA_RISCHIO (PROGR_SOGGETTO_PROGETTO);

CREATE INDEX IE2_PBANDI_R_SOG_PROG_CLA_RISC ON PBANDI_R_SOGG_PROG_CLA_RISCHIO (ID_CLASSE_RISCHIO);

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_D_PROVIDER"                                          */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_D_PROVIDER (
    ID_PROVIDER NUMBER(3) NOT NULL,
    DESC_PROVIDER VARCHAR2(255) NOT NULL,
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    CONSTRAINT PK_PBANDI_D_PROVIDER PRIMARY KEY (ID_PROVIDER)
);

-- Monitoraggio
/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_D_TIPO_MONIT_CRED"                                          */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_D_TIPO_MONIT_CRED (
    ID_TIPO_MONIT_CRED NUMBER(3) NOT NULL,
    DESC_BREVE_TIPO_MONIT_CRED VARCHAR2(40) NOT NULL,
    DESC_TIPO_MONIT_CRED VARCHAR2(255) NOT NULL,
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    CONSTRAINT PK_PBANDI_D_TIPO_MONIT_CRED PRIMARY KEY (ID_TIPO_MONIT_CRED)
);

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_D_ATTIVITA_MONIT_CRED"                               */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_D_ATTIVITA_MONIT_CRED (
    ID_ATTIVITA_MONIT_CRED NUMBER(3) NOT NULL,
    ID_TIPO_MONIT_CRED NUMBER(3) NOT NULL,
    DESC_BREVE_ATT_MONIT_CRED VARCHAR2(40) NOT NULL,
    DESC_ATT_MONIT_CRED VARCHAR2(255) NOT NULL,
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    CONSTRAINT PK_PBANDI_D_ATTIV_MONIT_CRED PRIMARY KEY (ID_ATTIVITA_MONIT_CRED)
);

CREATE INDEX IE_PBANDI_D_ATTIV_MONIT_CRED_1 ON PBANDI_D_ATTIVITA_MONIT_CRED (ID_TIPO_MONIT_CRED);

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_T_REVOCA_BANCARIA"                                   */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_T_REVOCA_BANCARIA (
    ID_REVOCA_BANCARIA NUMBER(8) NOT NULL,
    ID_PROGETTO NUMBER(8) NOT NULL,
    DT_RICEZIONE_COMUNICAZ DATE,
    DT_REVOCA DATE,
    IMP_DEBITO_RESIDUO_BANCA NUMBER(13,2),
    IMP_DEBITO_RESIDUO_FP NUMBER(13,2),
    PERC_COFINANZ_FP NUMBER(5,2),
    NUM_PROTOCOLLO NUMBER(4),
    NOTE VARCHAR2(4000),
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    ID_UTENTE_INS NUMBER(8) NOT NULL,
    ID_UTENTE_AGG NUMBER(8),
    DT_INSERIMENTO DATE NOT NULL,
    DT_AGGIORNAMENTO DATE,
    CONSTRAINT PK_PBANDI_T_REVOCA_BANCARIA PRIMARY KEY (ID_REVOCA_BANCARIA)
);

CREATE INDEX IE1_PBANDI_T_REVOCA_BANCARIA_1 ON PBANDI_T_REVOCA_BANCARIA (ID_PROGETTO);

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_T_AZIONE_RECUP_BANCA"                                */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_T_AZIONE_RECUP_BANCA (
    ID_AZIONE_RECUPERO_BANCA NUMBER(8) NOT NULL,
    ID_PROGETTO NUMBER(8) NOT NULL,
    ID_ATTIVITA_AZIONE NUMBER(3) NOT NULL,
    DT_AZIONE DATE,
    NUM_PROTOCOLLO NUMBER(4),
    NOTE VARCHAR2(4000),
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    ID_UTENTE_INS NUMBER(8) NOT NULL,
    ID_UTENTE_AGG NUMBER(8),
    DT_INSERIMENTO DATE NOT NULL,
    DT_AGGIORNAMENTO DATE,
    CONSTRAINT PK_PBANDI_T_AZIONE_RECUP_BANCA PRIMARY KEY (ID_AZIONE_RECUPERO_BANCA)
);

CREATE INDEX IE_PBANDI_T_AZIO_RECUP_BANCA_1 ON PBANDI_T_AZIONE_RECUP_BANCA (ID_PROGETTO);

CREATE INDEX IE_PBANDI_T_AZIO_RECUP_BANCA_2 ON PBANDI_T_AZIONE_RECUP_BANCA (ID_ATTIVITA_AZIONE);

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_T_LIBERAZ_GARANTE"                                   */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_T_LIBERAZ_GARANTE (
    ID_LIBERAZ_GARANTE NUMBER(8) NOT NULL,
    ID_PROGETTO NUMBER(8),
    DT_LIBERAZ_GARANTE DATE,
    IMP_LIBERAZIONE NUMBER(13,2),
    DENOM_GARANTE_LIBERATO VARCHAR(400),
    NOTE VARCHAR2(4000),
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    ID_UTENTE_INS NUMBER(8) NOT NULL,
    ID_UTENTE_AGG NUMBER(8),
    DT_INSERIMENTO DATE NOT NULL,
    DT_AGGIORNAMENTO DATE,
    CONSTRAINT PK_PBANDI_T_LIBERAZ_GARANTE PRIMARY KEY (ID_LIBERAZ_GARANTE)
);

CREATE INDEX IE1_PBANDI_T_LIBERAZ_GARANTE_1 ON PBANDI_T_LIBERAZ_GARANTE (ID_PROGETTO);

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_T_ABBATTIM_GARANZIE"                                 */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_T_ABBATTIM_GARANZIE (
    ID_ABBATTIM_GARANZIE NUMBER(8) NOT NULL,
    ID_PROGETTO NUMBER(8) NOT NULL,
    ID_ATTIVITA_GARANZIE NUMBER(3) NOT NULL,
    DT_LIBERAZ_GARANTE DATE,
    IMP_LIBERAZIONE NUMBER(13,2),
    DENOM_GARANTE_LIBERATO VARCHAR(400),
    NOTE VARCHAR2(4000),
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    ID_UTENTE_INS NUMBER(8) NOT NULL,
    ID_UTENTE_AGG NUMBER(8),
    DT_INSERIMENTO DATE NOT NULL,
    DT_AGGIORNAMENTO DATE,
    CONSTRAINT PK_PBANDI_T_ABBATTIM_GARANZIE PRIMARY KEY (ID_ABBATTIM_GARANZIE)
);

CREATE INDEX IE_PBANDI_T_ABBATTI_GARANZIE_1 ON PBANDI_T_ABBATTIM_GARANZIE (ID_PROGETTO);

CREATE INDEX IE_PBANDI_T_ABBATTI_GARANZIE_2 ON PBANDI_T_ABBATTIM_GARANZIE (ID_ATTIVITA_GARANZIE);

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_T_ESCUSS_CONFIDI"                                    */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_T_ESCUSS_CONFIDI (
    ID_ESCUSS_CONFIDI NUMBER(8) NOT NULL,
    ID_PROGETTO NUMBER(8) NOT NULL,
    ID_ATTIVITA_GARANZIA_CONFIDI NUMBER(3),
    DENOM_CONFIDI VARCHAR(400),
    DT_ESCUSS_CONFIDI DATE,
    DT_PAGAM_CONFIDI DATE,
    PERC_GARANZIA NUMBER(5,2),
    NOTE VARCHAR2(4000),
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    ID_UTENTE_INS NUMBER(8) NOT NULL,
    ID_UTENTE_AGG NUMBER(8),
    DT_INSERIMENTO DATE NOT NULL,
    DT_AGGIORNAMENTO DATE,
    CONSTRAINT PK_PBANDI_T_ESCUSS_CONFIDI PRIMARY KEY (ID_ESCUSS_CONFIDI)
);

CREATE INDEX IE_PBANDI_T_ESCUSS_CONFIDI_1 ON PBANDI_T_ESCUSS_CONFIDI (ID_ATTIVITA_GARANZIA_CONFIDI);

CREATE INDEX IE_PBANDI_T_ESCUSS_CONFIDI_2 ON PBANDI_T_ESCUSS_CONFIDI (ID_PROGETTO);

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_T_PIANO_RIENTRO"                                     */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_T_PIANO_RIENTRO (
    ID_PIANO_RIENTRO NUMBER(8) NOT NULL,
    ID_PROGETTO NUMBER(8) NOT NULL,
    DT_PROPOSTA DATE,
    IMP_QUOTA_CAPITALE NUMBER(13,2),
    IMP_AGEVOLAZIONE NUMBER(13,2),
    ID_ATTIVITA_ESITO NUMBER(3),
    DT_ESITO DATE,
    ID_ATTIVITA_RECUPERO NUMBER(3),
    NOTE VARCHAR2(4000),
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    ID_UTENTE_INS NUMBER(8) NOT NULL,
    ID_UTENTE_AGG NUMBER(8),
    DT_INSERIMENTO DATE NOT NULL,
    DT_AGGIORNAMENTO DATE,
    CONSTRAINT PK_PBANDI_T_PIANO_RIENTRO PRIMARY KEY (ID_PIANO_RIENTRO)
);

CREATE INDEX IE_PBANDI_T_PIANO_RIENTRO_1 ON PBANDI_T_PIANO_RIENTRO (ID_PROGETTO);

CREATE INDEX IE_PBANDI_T_PIANO_RIENTRO_2 ON PBANDI_T_PIANO_RIENTRO (ID_ATTIVITA_ESITO);

CREATE INDEX IE_PBANDI_T_PIANO_RIENTRO_3 ON PBANDI_T_PIANO_RIENTRO (ID_ATTIVITA_RECUPERO);

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_T_SALDO_STRALCIO"                                    */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_T_SALDO_STRALCIO (
    ID_SALDO_STRALCIO NUMBER(8) NOT NULL,
    ID_PROGETTO NUMBER(8) NOT NULL,
    ID_ATTIVITA_RECUP_MORA NUMBER(3),
    DT_PROPOSTA DATE,
    DT_ACCETTAZIONE DATE,
    IMP_DEBITORE NUMBER(13,2),
    IMP_CONFIDI NUMBER(13,2),
    ID_ATTIVITA_ESITO NUMBER(3),
    DT_ESITO DATE,
    DT_PAGAM_DEBITORE DATE,
    DT_PAGAM_CONFIDI DATE,
    ID_ATTIVITA_RECUPERO NUMBER(3),
    IMP_RECUPERATO NUMBER(13,2),
    IMP_PERDITA NUMBER(13,2),
    NOTE VARCHAR2(4000),
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    ID_UTENTE_INS NUMBER(8) NOT NULL,
    ID_UTENTE_AGG NUMBER(8),
    DT_INSERIMENTO DATE NOT NULL,
    DT_AGGIORNAMENTO DATE,
    CONSTRAINT PK_PBANDI_T_SALDO_STRALCIO PRIMARY KEY (ID_SALDO_STRALCIO)
);

CREATE INDEX IE_PBANDI_T_SALDO_STRALCIO_1 ON PBANDI_T_SALDO_STRALCIO (ID_PROGETTO);

CREATE INDEX IE_PBANDI_T_SALDO_STRALCIO_2 ON PBANDI_T_SALDO_STRALCIO (ID_ATTIVITA_RECUP_MORA);

CREATE INDEX IE_PBANDI_T_SALDO_STRALCIO_3 ON PBANDI_T_SALDO_STRALCIO (ID_ATTIVITA_ESITO);

CREATE INDEX IE_PBANDI_T_SALDO_STRALCIO_4 ON PBANDI_T_SALDO_STRALCIO (ID_ATTIVITA_RECUPERO);

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_T_PASSAGGIO_PERDITA"                                 */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_T_PASSAGGIO_PERDITA (
    ID_PASSAGGIO_PERDITA NUMBER(8) NOT NULL,
    ID_PROGETTO NUMBER(8) NOT NULL,
    DT_PASSAGGIO_PERDITA DATE,
    IMP_PERDITA_COMPLESSIVA NUMBER(13,2),
    IMP_PERDITA_CAPITALE NUMBER(13,2),
    IMP_PERDITA_INTERESSI NUMBER(13,2),
    IMP_PERDITA_AGEVOLAZ NUMBER(13,2),
    IMP_PERDITA_MORA NUMBER(13,2),
    NOTE VARCHAR2(4000),
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    ID_UTENTE_INS NUMBER(8) NOT NULL,
    ID_UTENTE_AGG NUMBER(8),
    DT_INSERIMENTO DATE NOT NULL,
    DT_AGGIORNAMENTO DATE,
    CONSTRAINT PK_PBANDI_T_PASSAGGIO_PERDITA PRIMARY KEY (ID_PASSAGGIO_PERDITA)
);

CREATE INDEX IE_PBANDI_T_PASSAGG_PERDITA_1 ON PBANDI_T_PASSAGGIO_PERDITA (ID_PROGETTO);

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_T_LIBERAZ_BANCA"                                     */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_T_LIBERAZ_BANCA (
    ID_LIBERAZ_BANCA NUMBER(8) NOT NULL,
    ID_PROGETTO NUMBER(8),
	ID_ATTIVITA_LIBERAZIONE NUMBER(3),
    DENOM_GARANTE_LIBERATO VARCHAR2(400),
    NOTE VARCHAR2(4000),
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    ID_UTENTE_INS NUMBER(8) NOT NULL,
    ID_UTENTE_AGG NUMBER(8),
    DT_INSERIMENTO DATE NOT NULL,
    DT_AGGIORNAMENTO DATE,
    CONSTRAINT PK_PBANDI_T_LIBERAZ_BANCA PRIMARY KEY (ID_LIBERAZ_BANCA)
);

CREATE INDEX IE_PBANDI_T_LIBERAZ_BANCA_1 ON PBANDI_T_LIBERAZ_BANCA (ID_PROGETTO);
CREATE INDEX IE_PBANDI_T_LIBERAZ_BANCA_2 ON PBANDI_T_LIBERAZ_BANCA (ID_ATTIVITA_LIBERAZIONE);


/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_T_MESSA_IN_MORA"                                     */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_T_MESSA_IN_MORA (
    ID_MESSA_IN_MORA NUMBER(8) NOT NULL,
    ID_PROGETTO NUMBER(8),
    ID_ATTIVITA_MORA NUMBER(3),
    IMP_MESSA_IN_MORA_COMPLESSIVA NUMBER(13,2),
    IMP_QUOTA_CAPITALE_REVOCA NUMBER(13,2),
    IMP_AGEVOLAZ_REVOCA NUMBER(13,2),
    IMP_CREDITO_RESIDUO NUMBER(13,2),
    IMP_INTERESSI_MORA NUMBER(13,2),
    DT_NOTIFICA DATE,
    NOTE VARCHAR2(4000),
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    ID_UTENTE_INS NUMBER(8) NOT NULL,
    ID_UTENTE_AGG NUMBER(8),
    DT_INSERIMENTO DATE NOT NULL,
    DT_AGGIORNAMENTO DATE,
    CONSTRAINT PK_PBANDI_T_MESSA_IN_MORA PRIMARY KEY (ID_MESSA_IN_MORA)
);

CREATE INDEX IE_PBANDI_T_MESSA_IN_MORA_1 ON PBANDI_T_MESSA_IN_MORA (ID_PROGETTO);

CREATE INDEX IE_PBANDI_T_MESSA_IN_MORA_2 ON PBANDI_T_MESSA_IN_MORA (ID_ATTIVITA_MORA);

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_T_ANNOTAZ_GENERALI"                                  */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_T_ANNOTAZ_GENERALI (
    ID_ANNOTAZ_GENERALE NUMBER(8) NOT NULL,
    ID_PROGETTO NUMBER(8) NOT NULL,
    NOTE VARCHAR2(4000),
    DT_INIZIO_VALIDITA DATE NOT NULL,
    DT_FINE_VALIDITA DATE,
    ID_UTENTE_INS NUMBER(8) NOT NULL,
    ID_UTENTE_AGG NUMBER(8),
    DT_INSERIMENTO DATE NOT NULL,
    DT_AGGIORNAMENTO DATE,
    CONSTRAINT PK_PBANDI_T_ANNOTAZ_GENERALI PRIMARY KEY (ID_ANNOTAZ_GENERALE)
);

CREATE INDEX IE_PBANDI_T_ANNOTAZ_GENERALI_1 ON PBANDI_T_ANNOTAZ_GENERALI (ID_PROGETTO);


/* ---------------------------------------------------------------------- */
/* Foreign key constraints                                                */
/* ---------------------------------------------------------------------- */


ALTER TABLE PBANDI_T_SOGG_STATO_AZIENDA ADD CONSTRAINT FK_PBANDI_T_SOGGETTO_28 
    FOREIGN KEY (ID_SOGGETTO) REFERENCES PBANDI.PBANDI_T_SOGGETTO (ID_SOGGETTO);

ALTER TABLE PBANDI_T_SOGG_STATO_AZIENDA ADD CONSTRAINT FK_PBANDI_D_STATO_AZIENDA_01 
    FOREIGN KEY (ID_STATO_AZIENDA) REFERENCES PBANDI_D_STATO_AZIENDA (ID_STATO_AZIENDA);

ALTER TABLE PBANDI_R_SOGG_PROG_STA_CRED_FP ADD CONSTRAINT FK_PBANDI_R_SOGG_PROGETTO_04 
    FOREIGN KEY (PROGR_SOGGETTO_PROGETTO) REFERENCES PBANDI.PBANDI_R_SOGGETTO_PROGETTO (PROGR_SOGGETTO_PROGETTO);

ALTER TABLE PBANDI_R_SOGG_PROG_STA_CRED_FP ADD CONSTRAINT FK_PBANDI_D_STATO_CRED_FP_01 
    FOREIGN KEY (ID_STATO_CREDITO_FP) REFERENCES PBANDI_D_STATO_CREDITO_FP (ID_STATO_CREDITO_FP);

ALTER TABLE PBANDI_T_SOGGETTO_RATING ADD CONSTRAINT FK_PBANDI_D_RATING_01 
    FOREIGN KEY (ID_RATING) REFERENCES PBANDI_D_RATING (ID_RATING);

ALTER TABLE PBANDI_T_SOGGETTO_RATING ADD CONSTRAINT FK_PBANDI_T_SOGGETTO_29 
    FOREIGN KEY (ID_SOGGETTO) REFERENCES PBANDI.PBANDI_T_SOGGETTO (ID_SOGGETTO);

ALTER TABLE PBANDI_R_SOGG_PROG_CLA_RISCHIO ADD CONSTRAINT FK_PBANDI_D_CLASSE_RISCHIO_01 
    FOREIGN KEY (ID_CLASSE_RISCHIO) REFERENCES PBANDI_D_CLASSE_RISCHIO (ID_CLASSE_RISCHIO);

ALTER TABLE PBANDI_R_SOGG_PROG_CLA_RISCHIO ADD CONSTRAINT FK_PBANDI_R_SOGG_PROGETTO_05 
    FOREIGN KEY (PROGR_SOGGETTO_PROGETTO) REFERENCES PBANDI.PBANDI_R_SOGGETTO_PROGETTO (PROGR_SOGGETTO_PROGETTO);

ALTER TABLE PBANDI_D_RATING ADD CONSTRAINT FK_PBANDI_D_PROVIDER_01 
    FOREIGN KEY (ID_PROVIDER) REFERENCES PBANDI_D_PROVIDER (ID_PROVIDER);
	
-- Monitoraggio
ALTER TABLE PBANDI_D_ATTIVITA_MONIT_CRED ADD CONSTRAINT FK_PBANDI_D_TIPO_MONIT_CRED_01 
    FOREIGN KEY (ID_TIPO_MONIT_CRED) REFERENCES PBANDI_D_TIPO_MONIT_CRED (ID_TIPO_MONIT_CRED);
ALTER TABLE PBANDI_T_REVOCA_BANCARIA ADD CONSTRAINT FK_PBANDI_T_PROGETTO_60 
    FOREIGN KEY (ID_PROGETTO) REFERENCES PBANDI.PBANDI_T_PROGETTO (ID_PROGETTO);

ALTER TABLE PBANDI_T_AZIONE_RECUP_BANCA ADD CONSTRAINT FK_PBANDI_T_PROGETTO_61 
    FOREIGN KEY (ID_PROGETTO) REFERENCES PBANDI.PBANDI_T_PROGETTO (ID_PROGETTO);

ALTER TABLE PBANDI_T_AZIONE_RECUP_BANCA ADD CONSTRAINT FK_PBANDI_D_ATT_MONIT_CRED_01 
    FOREIGN KEY (ID_ATTIVITA_AZIONE) REFERENCES PBANDI_D_ATTIVITA_MONIT_CRED (ID_ATTIVITA_MONIT_CRED);

ALTER TABLE PBANDI_T_LIBERAZ_GARANTE ADD CONSTRAINT FK_PBANDI_T_PROGETTO_62 
    FOREIGN KEY (ID_PROGETTO) REFERENCES PBANDI.PBANDI_T_PROGETTO (ID_PROGETTO);

ALTER TABLE PBANDI_T_ABBATTIM_GARANZIE ADD CONSTRAINT FK_PBANDI_T_PROGETTO_63 
    FOREIGN KEY (ID_PROGETTO) REFERENCES PBANDI.PBANDI_T_PROGETTO (ID_PROGETTO);

ALTER TABLE PBANDI_T_ABBATTIM_GARANZIE ADD CONSTRAINT FK_PBANDI_D_ATT_MONIT_CRED_02 
    FOREIGN KEY (ID_ATTIVITA_GARANZIE) REFERENCES PBANDI_D_ATTIVITA_MONIT_CRED (ID_ATTIVITA_MONIT_CRED);

ALTER TABLE PBANDI_T_ESCUSS_CONFIDI ADD CONSTRAINT FK_PBANDI_T_PROGETTO_64 
    FOREIGN KEY (ID_PROGETTO) REFERENCES PBANDI.PBANDI_T_PROGETTO (ID_PROGETTO);

ALTER TABLE PBANDI_T_ESCUSS_CONFIDI ADD CONSTRAINT FK_PBANDI_D_ATT_MONIT_CRED_03 
    FOREIGN KEY (ID_ATTIVITA_GARANZIA_CONFIDI) REFERENCES PBANDI_D_ATTIVITA_MONIT_CRED (ID_ATTIVITA_MONIT_CRED);

ALTER TABLE PBANDI_T_PIANO_RIENTRO ADD CONSTRAINT FK_PBANDI_T_PROGETTO_65 
    FOREIGN KEY (ID_PROGETTO) REFERENCES PBANDI.PBANDI_T_PROGETTO (ID_PROGETTO);

ALTER TABLE PBANDI_T_PIANO_RIENTRO ADD CONSTRAINT FK_PBANDI_D_ATT_MONIT_CRED_05 
    FOREIGN KEY (ID_ATTIVITA_ESITO) REFERENCES PBANDI_D_ATTIVITA_MONIT_CRED (ID_ATTIVITA_MONIT_CRED);

ALTER TABLE PBANDI_T_PIANO_RIENTRO ADD CONSTRAINT FK_PBANDI_D_ATT_MONIT_CRED_04 
    FOREIGN KEY (ID_ATTIVITA_RECUPERO) REFERENCES PBANDI_D_ATTIVITA_MONIT_CRED (ID_ATTIVITA_MONIT_CRED);

ALTER TABLE PBANDI_T_SALDO_STRALCIO ADD CONSTRAINT FK_PBANDI_T_PROGETTO_66 
    FOREIGN KEY (ID_PROGETTO) REFERENCES PBANDI.PBANDI_T_PROGETTO (ID_PROGETTO);

ALTER TABLE PBANDI_T_SALDO_STRALCIO ADD CONSTRAINT FK_PBANDI_D_ATT_MONIT_CRED_06 
    FOREIGN KEY (ID_ATTIVITA_RECUP_MORA) REFERENCES PBANDI_D_ATTIVITA_MONIT_CRED (ID_ATTIVITA_MONIT_CRED);

ALTER TABLE PBANDI_T_SALDO_STRALCIO ADD CONSTRAINT FK_PBANDI_D_ATT_MONIT_CRED_07 
    FOREIGN KEY (ID_ATTIVITA_ESITO) REFERENCES PBANDI_D_ATTIVITA_MONIT_CRED (ID_ATTIVITA_MONIT_CRED);

ALTER TABLE PBANDI_T_SALDO_STRALCIO ADD CONSTRAINT FK_PBANDI_D_ATT_MONIT_CRED_08 
    FOREIGN KEY (ID_ATTIVITA_RECUPERO) REFERENCES PBANDI_D_ATTIVITA_MONIT_CRED (ID_ATTIVITA_MONIT_CRED);

ALTER TABLE PBANDI_T_PASSAGGIO_PERDITA ADD CONSTRAINT FK_PBANDI_T_PROGETTO_67 
    FOREIGN KEY (ID_PROGETTO) REFERENCES PBANDI.PBANDI_T_PROGETTO (ID_PROGETTO);

ALTER TABLE PBANDI_T_LIBERAZ_BANCA ADD CONSTRAINT FK_PBANDI_T_PROGETTO_68 
    FOREIGN KEY (ID_PROGETTO) REFERENCES PBANDI.PBANDI_T_PROGETTO (ID_PROGETTO);

ALTER TABLE PBANDI_T_LIBERAZ_BANCA ADD CONSTRAINT FK_PBANDI_D_ATT_MONIT_CRED_09 
    FOREIGN KEY (ID_ATTIVITA_LIBERAZIONE) REFERENCES PBANDI_D_ATTIVITA_MONIT_CRED (ID_ATTIVITA_MONIT_CRED);

ALTER TABLE PBANDI_T_MESSA_IN_MORA ADD CONSTRAINT FK_PBANDI_T_PROGETTO_70 
    FOREIGN KEY (ID_PROGETTO) REFERENCES PBANDI.PBANDI_T_PROGETTO (ID_PROGETTO);

ALTER TABLE PBANDI_T_MESSA_IN_MORA ADD CONSTRAINT FK_PBANDI_D_ATT_MONIT_CRED_10 
    FOREIGN KEY (ID_ATTIVITA_MORA) REFERENCES PBANDI_D_ATTIVITA_MONIT_CRED (ID_ATTIVITA_MONIT_CRED);

ALTER TABLE PBANDI_T_ANNOTAZ_GENERALI ADD CONSTRAINT FK_PBANDI_T_PROGETTO_69 
    FOREIGN KEY (ID_PROGETTO) REFERENCES PBANDI.PBANDI_T_PROGETTO (ID_PROGETTO);


ALTER TABLE PBANDI_T_SOGG_STATO_AZIENDA ADD
(
 CONSTRAINT FK_PBANDI_T_UTENTE_298 
 FOREIGN KEY (ID_UTENTE_INS) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE),
  CONSTRAINT FK_PBANDI_T_UTENTE_299 
 FOREIGN KEY (ID_UTENTE_AGG) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE)
    ON DELETE SET NULL);
    
ALTER TABLE PBANDI_R_SOGG_PROG_STA_CRED_FP ADD
(
 CONSTRAINT FK_PBANDI_T_UTENTE_300 
 FOREIGN KEY (ID_UTENTE_INS) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE),
  CONSTRAINT FK_PBANDI_T_UTENTE_301 
 FOREIGN KEY (ID_UTENTE_AGG) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE)
    ON DELETE SET NULL);
 
ALTER TABLE PBANDI_T_SOGGETTO_RATING ADD
(
 CONSTRAINT FK_PBANDI_T_UTENTE_302 
 FOREIGN KEY (ID_UTENTE_INS) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE),
  CONSTRAINT FK_PBANDI_T_UTENTE_303 
 FOREIGN KEY (ID_UTENTE_AGG) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE)
    ON DELETE SET NULL);
    
ALTER TABLE PBANDI_R_SOGG_PROG_CLA_RISCHIO ADD
(
 CONSTRAINT FK_PBANDI_T_UTENTE_304 
 FOREIGN KEY (ID_UTENTE_INS) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE),
  CONSTRAINT FK_PBANDI_T_UTENTE_305 
 FOREIGN KEY (ID_UTENTE_AGG) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE)
    ON DELETE SET NULL);

ALTER TABLE PBANDI_T_REVOCA_BANCARIA ADD
(
 CONSTRAINT FK_PBANDI_T_UTENTE_306 
 FOREIGN KEY (ID_UTENTE_INS) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE),
  CONSTRAINT FK_PBANDI_T_UTENTE_307 
 FOREIGN KEY (ID_UTENTE_AGG) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE)
    ON DELETE SET NULL);

ALTER TABLE PBANDI_T_AZIONE_RECUP_BANCA ADD
(
 CONSTRAINT FK_PBANDI_T_UTENTE_308 
 FOREIGN KEY (ID_UTENTE_INS) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE),
  CONSTRAINT FK_PBANDI_T_UTENTE_309 
 FOREIGN KEY (ID_UTENTE_AGG) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE)
    ON DELETE SET NULL);
    
ALTER TABLE PBANDI_T_ABBATTIM_GARANZIE ADD
(
 CONSTRAINT FK_PBANDI_T_UTENTE_312 
 FOREIGN KEY (ID_UTENTE_INS) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE),
  CONSTRAINT FK_PBANDI_T_UTENTE_313 
 FOREIGN KEY (ID_UTENTE_AGG) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE)
    ON DELETE SET NULL);

ALTER TABLE PBANDI_T_ESCUSS_CONFIDI ADD
(
 CONSTRAINT FK_PBANDI_T_UTENTE_314 
 FOREIGN KEY (ID_UTENTE_INS) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE),
  CONSTRAINT FK_PBANDI_T_UTENTE_315 
 FOREIGN KEY (ID_UTENTE_AGG) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE)
    ON DELETE SET NULL);

ALTER TABLE PBANDI_T_PIANO_RIENTRO ADD
(
 CONSTRAINT FK_PBANDI_T_UTENTE_316 
 FOREIGN KEY (ID_UTENTE_INS) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE),
  CONSTRAINT FK_PBANDI_T_UTENTE_317 
 FOREIGN KEY (ID_UTENTE_AGG) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE)
    ON DELETE SET NULL);    

ALTER TABLE PBANDI_T_SALDO_STRALCIO ADD
(
 CONSTRAINT FK_PBANDI_T_UTENTE_318 
 FOREIGN KEY (ID_UTENTE_INS) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE),
  CONSTRAINT FK_PBANDI_T_UTENTE_319 
 FOREIGN KEY (ID_UTENTE_AGG) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE)
    ON DELETE SET NULL);  

ALTER TABLE PBANDI_T_PASSAGGIO_PERDITA ADD
(
 CONSTRAINT FK_PBANDI_T_UTENTE_320 
 FOREIGN KEY (ID_UTENTE_INS) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE),
  CONSTRAINT FK_PBANDI_T_UTENTE_321 
 FOREIGN KEY (ID_UTENTE_AGG) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE)
    ON DELETE SET NULL);    

ALTER TABLE PBANDI_T_LIBERAZ_BANCA ADD
(
 CONSTRAINT FK_PBANDI_T_UTENTE_322 
 FOREIGN KEY (ID_UTENTE_INS) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE),
  CONSTRAINT FK_PBANDI_T_UTENTE_323 
 FOREIGN KEY (ID_UTENTE_AGG) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE)
    ON DELETE SET NULL);
    
ALTER TABLE PBANDI_T_MESSA_IN_MORA ADD
(
 CONSTRAINT FK_PBANDI_T_UTENTE_324 
 FOREIGN KEY (ID_UTENTE_INS) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE),
  CONSTRAINT FK_PBANDI_T_UTENTE_325 
 FOREIGN KEY (ID_UTENTE_AGG) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE)
    ON DELETE SET NULL);

ALTER TABLE PBANDI_T_ANNOTAZ_GENERALI ADD
(
 CONSTRAINT FK_PBANDI_T_UTENTE_326 
 FOREIGN KEY (ID_UTENTE_INS) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE),
  CONSTRAINT FK_PBANDI_T_UTENTE_327 
 FOREIGN KEY (ID_UTENTE_AGG) 
 REFERENCES PBANDI.PBANDI_T_UTENTE (ID_UTENTE)
    ON DELETE SET NULL);
