/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/


CREATE OR REPLACE FORCE VIEW PBANDI_V_PROGETTI_BANDO
(
   PROGR_BANDO_LINEA_INTERVENTO,
   ID_BANDO,
   ID_LINEA_DI_INTERVENTO,
   ID_PROGETTO,
   CODICE_PROGETTO,
   CODICE_VISUALIZZATO,
   DT_AGGIORNAMENTO,
   ID_DOMANDA,
   NUMERO_DOMANDA,
   ID_PROGETTO_FINANZ
)
AS
   SELECT c.progr_bando_linea_intervento,
          c.id_bando,
          c.id_linea_di_intervento,
          a.id_progetto,
		  a.codice_progetto,
          a.codice_visualizzato,
          a.dt_aggiornamento,
          b.id_domanda,
          b.numero_domanda,
		  a.id_progetto_finanz
     FROM PBANDI_T_PROGETTO a,
          PBANDI_T_DOMANDA b,
          PBANDI_R_BANDO_LINEA_INTERVENT c
    WHERE b.id_domanda = a.id_domanda
          AND c.progr_bando_linea_intervento = b.progr_bando_linea_intervento;


--
ALTER TABLE  PBANDI_T_BANDO ADD FLAG_MACRO_VOCE_SPESA NUMBER;

ALTER TABLE PBANDI_T_BANDO ADD (
  CONSTRAINT CHK_FLAG_MACRO_VOCE_SPESA
  CHECK (FLAG_MACRO_VOCE_SPESA IN (-1)));
  
COMMENT ON COLUMN PBANDI_T_BANDO.FLAG_MACRO_VOCE_SPESA IS '-1=Non viene considerata la macrovoce nella configurazione delle voci di spesa';

-- PBANDI_D_VOCE_DI_ENTRATA 
CREATE TABLE PBANDI_D_VOCE_DI_ENTRATA
 (
  ID_VOCE_DI_ENTRATA NUMBER(8) NOT NULL,
  DESCRIZIONE_BREVE VARCHAR2(20) NOT NULL,
  DESCRIZIONE VARCHAR2(200) NOT NULL,
  INDICAZIONI VARCHAR2(200),
  FLAG_EDIT  VARCHAR2(1),
  FLAG_RISORSE_PROPRIE NUMBER(1)  DEFAULT 0 NOT NULL,
  DT_INIZIO_VALIDITA DATE,
  DT_FINE_VALIDITA DATE
  )
TABLESPACE PBANDI_TBL;

COMMENT ON TABLE  PBANDI_D_VOCE_DI_ENTRATA IS 'Tabella voci di entrata';
COMMENT ON COLUMN PBANDI_D_VOCE_DI_ENTRATA.FLAG_EDIT IS 'S=Deve essere imputato il campo previsto per il valore della colonna "INDICAZIONI" che dovrà essere definita a livello di Conto Economico (Rigo Conto Economico)';
COMMENT ON COLUMN PBANDI_D_VOCE_DI_ENTRATA.FLAG_RISORSE_PROPRIE IS '0=No risorsa propria, 1=Risorsa propria';

 --PK
ALTER TABLE PBANDI_D_VOCE_DI_ENTRATA  ADD 
(CONSTRAINT PK_PBANDI_D_VOCE_DI_ENTRATA  PRIMARY KEY (ID_VOCE_DI_ENTRATA)
USING INDEX TABLESPACE PBANDI_IDX);

-- CK
ALTER TABLE PBANDI_D_VOCE_DI_ENTRATA ADD (
  CONSTRAINT CHK_FLAG_EDIT
  CHECK (FLAG_EDIT IN ('S')));

ALTER TABLE PBANDI_D_VOCE_DI_ENTRATA ADD (
  CONSTRAINT CHK_FLAG_RISORSE_PROPRIE
  CHECK (FLAG_RISORSE_PROPRIE IN (0,1)));

CREATE SEQUENCE SEQ_PBANDI_D_VOCE_DI_ENTRATA
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

-- PBANDI_R_BANDO_VOCE_ENTRATA
CREATE TABLE PBANDI_R_BANDO_VOCE_ENTRATA
 (
  ID_BANDO NUMBER(8)  NOT NULL,
  ID_VOCE_DI_ENTRATA NUMBER(8) NOT NULL,
  ID_UTENTE_INS NUMBER(8)  NOT NULL,
  ID_UTENTE_AGG NUMBER(8)
  )
TABLESPACE PBANDI_TBL;

COMMENT ON TABLE  PBANDI_R_BANDO_VOCE_ENTRATA IS 'Tabella associazione Bando - Voci di entrata';

--PK
ALTER TABLE PBANDI_R_BANDO_VOCE_ENTRATA  ADD 
(CONSTRAINT PK_PBANDI_R_BANDO_VOCE_ENTRATA  PRIMARY KEY (ID_BANDO,ID_VOCE_DI_ENTRATA)
USING INDEX TABLESPACE PBANDI_IDX);

--FK
ALTER TABLE PBANDI_R_BANDO_VOCE_ENTRATA ADD (
  CONSTRAINT FK_PBANDI_D_VOCE_DI_ENTRATA_01
  FOREIGN KEY (ID_VOCE_DI_ENTRATA) 
  REFERENCES PBANDI_D_VOCE_DI_ENTRATA (ID_VOCE_DI_ENTRATA),
  CONSTRAINT FK_PBANDI_T_BANDO_10
  FOREIGN KEY (ID_BANDO) 
  REFERENCES PBANDI_T_BANDO (ID_BANDO),
  CONSTRAINT FK_PBANDI_T_UTENTE_266 
  FOREIGN KEY (ID_UTENTE_INS) 
  REFERENCES PBANDI_T_UTENTE (ID_UTENTE),
  CONSTRAINT FK_PBANDI_T_UTENTE_267
  FOREIGN KEY (ID_UTENTE_AGG) 
  REFERENCES PBANDI_T_UTENTE (ID_UTENTE)
  ON DELETE SET NULL);
  
-- INDEX  
CREATE INDEX IE1_PBANDI_R_BANDO_VOCE_ENTRAT ON PBANDI_R_BANDO_VOCE_ENTRATA
(ID_VOCE_DI_ENTRATA)
TABLESPACE PBANDI_IDX;
  
CREATE INDEX IE2_PBANDI_R_BANDO_VOCE_ENTRAT ON PBANDI_R_BANDO_VOCE_ENTRATA
(ID_UTENTE_INS)
TABLESPACE PBANDI_IDX;

CREATE INDEX IE3_PBANDI_R_BANDO_VOCE_ENTRAT ON PBANDI_R_BANDO_VOCE_ENTRATA
(ID_UTENTE_AGG)
TABLESPACE PBANDI_IDX;    
  
  
  
-- PBANDI_D_TIPOL_VOCE_DI_SPESA 
CREATE TABLE PBANDI_D_TIPOL_VOCE_DI_SPESA
 (
  ID_TIPOLOGIA_VOCE_DI_SPESA  NUMBER(3)  NOT NULL,
  DESCRIZIONE VARCHAR2(200) NULL,
  PERC_QUOTA_CONTRIBUTO  NUMBER(5,2)
  )
TABLESPACE PBANDI_TBL;
 
COMMENT ON TABLE  PBANDI_D_TIPOL_VOCE_DI_SPESA IS 'Tipologia voce di spesa';

 --PK
ALTER TABLE PBANDI_D_TIPOL_VOCE_DI_SPESA  ADD 
(CONSTRAINT PK_PBANDI_D_TIPOL_VOCE_SPESA  PRIMARY KEY (ID_TIPOLOGIA_VOCE_DI_SPESA)
USING INDEX TABLESPACE PBANDI_IDX); 


/* Già create
--PBANDI_D_VOCE_DI_SPESA 
ALTER TABLE PBANDI_D_VOCE_DI_SPESA ADD 
(ID_TIPOLOGIA_VOCE_DI_SPESA  NUMBER(3));

ALTER TABLE PBANDI_D_VOCE_DI_SPESA ADD 
(FLAG_EDIT  VARCHAR2(1));
*/

COMMENT ON COLUMN PBANDI_D_VOCE_DI_SPESA.ID_TIPOLOGIA_VOCE_DI_SPESA IS 'La colonna verrà valorizzata per le voci di spesa dei Bandi Cultura';
COMMENT ON COLUMN PBANDI_D_VOCE_DI_SPESA.FLAG_EDIT IS 'S=Deve essere imputato il campo previsto per il valore della colonna "INDICAZIONI" che dovrà essere definita a livello di Conto Economico (Rigo Conto Economico)';

--FK
ALTER TABLE PBANDI_D_VOCE_DI_SPESA ADD (
  CONSTRAINT FK_PBANDI_D_TIPOL_VOC_SPESA_01
  FOREIGN KEY (ID_TIPOLOGIA_VOCE_DI_SPESA) 
  REFERENCES PBANDI_D_TIPOL_VOCE_DI_SPESA (ID_TIPOLOGIA_VOCE_DI_SPESA));

-- INDEX  
CREATE INDEX IE1_PBANDI_D_VOCE_DI_SPESA ON PBANDI_D_VOCE_DI_SPESA
(ID_TIPOLOGIA_VOCE_DI_SPESA)
TABLESPACE PBANDI_IDX;

--PBANDI_T_DOMANDA
ALTER TABLE PBANDI_T_DOMANDA ADD ID_ALIQUOTA_RITENUTA   NUMBER(3);
--FK
ALTER TABLE PBANDI_T_DOMANDA ADD (
  CONSTRAINT FK_PBANDI_D_ALIQUOTA_RITENU_02
  FOREIGN KEY (ID_ALIQUOTA_RITENUTA) 
  REFERENCES PBANDI_D_ALIQUOTA_RITENUTA (ID_ALIQUOTA_RITENUTA));
  
COMMENT ON COLUMN PBANDI_T_DOMANDA.ID_ALIQUOTA_RITENUTA IS 'Ritenuta IRES';

--PBANDI_T_PROGETTO
ALTER TABLE PBANDI_T_PROGETTO ADD ID_ALIQUOTA_RITENUTA   NUMBER(3);
--FK
ALTER TABLE PBANDI_T_PROGETTO ADD (
  CONSTRAINT FK_PBANDI_D_ALIQUOTA_RITENU_03
  FOREIGN KEY (ID_ALIQUOTA_RITENUTA) 
  REFERENCES PBANDI_D_ALIQUOTA_RITENUTA (ID_ALIQUOTA_RITENUTA));
  
CREATE INDEX IE9_PBANDI_T_PROGETTO ON PBANDI_T_PROGETTO
(ID_ALIQUOTA_RITENUTA)
TABLESPACE PBANDI_IDX;

COMMENT ON COLUMN PBANDI_T_PROGETTO.ID_ALIQUOTA_RITENUTA IS 'Ritenuta IRES';


--PBANDI_T_RIGO_CONTO_ECONOMICO
ALTER TABLE PBANDI_T_RIGO_CONTO_ECONOMICO MODIFY ID_VOCE_DI_SPESA NULL;

ALTER TABLE PBANDI_T_RIGO_CONTO_ECONOMICO ADD 
(ID_VOCE_DI_ENTRATA   NUMBER(8),
 COMPLETAMENTO VARCHAR2(200));
COMMENT ON COLUMN PBANDI_T_RIGO_CONTO_ECONOMICO.ID_VOCE_DI_ENTRATA IS 'La colonna verrà valorizzata per il conto economico dei Bandi Cultura';
COMMENT ON COLUMN PBANDI_T_RIGO_CONTO_ECONOMICO.COMPLETAMENTO_VOCE_ENTRATA IS 'Le voci di entrata che nel file sono marcate con FLAG_EDIT = ‘S’ prevedono un’informazione di completamento, di tipo descrittivo a valorizzazione libera';

--FK
ALTER TABLE PBANDI_T_RIGO_CONTO_ECONOMICO ADD (
  CONSTRAINT FK_PBANDI_D_VOCE_DI_ENTRATA_02
  FOREIGN KEY (ID_VOCE_DI_ENTRATA) 
  REFERENCES PBANDI_D_VOCE_DI_ENTRATA (ID_VOCE_DI_ENTRATA));
  
-- INDEX  
CREATE INDEX IE_PBANDI_T_RIGO_CONTO_ECON_02 ON PBANDI_T_RIGO_CONTO_ECONOMICO
(ID_VOCE_DI_ENTRATA)
TABLESPACE PBANDI_IDX;


ALTER TABLE PBANDI_T_QUOTA_PARTE_DOC_SPESA ADD 
(IMP_VALIDATO   NUMBER(17,2));
COMMENT ON COLUMN PBANDI_T_QUOTA_PARTE_DOC_SPESA.IMPORTO_VALIDATO IS 'La colonna verrà valorizzata per il validato dei Bandi Cultura';

-- PBANDI_R_PAG_QTCL_PARTE_DOC_SP
CREATE TABLE PBANDI_R_PAG_QTCL_PARTE_DOC_SP
 (
  ID_PAGAMENTO NUMBER(8)  NOT NULL,
  ID_QUOTA_PARTE_DOC_SPESA NUMBER(8) NOT NULL,
  ID_UTENTE_INS NUMBER(8)  NOT NULL,
  ID_UTENTE_AGG NUMBER(8)
  )
TABLESPACE PBANDI_TBL;

COMMENT ON TABLE  PBANDI_R_PAG_QTCL_PARTE_DOC_SP IS 'Per Beneficiari Pubblici, i pagamenti (atti di liquidazione) verranno associati direttamente alle voci di spesa';

--PK
ALTER TABLE PBANDI_R_PAG_QTCL_PARTE_DOC_SP  ADD 
(CONSTRAINT PK_PBANDI_R_PAG_QTCL_PT_DOC_SP  PRIMARY KEY (ID_PAGAMENTO,ID_QUOTA_PARTE_DOC_SPESA)
USING INDEX TABLESPACE PBANDI_IDX);

--FK
ALTER TABLE PBANDI_R_PAG_QTCL_PARTE_DOC_SP ADD (
  CONSTRAINT FK_PBANDI_T_PAGAMENTO_04
  FOREIGN KEY (ID_PAGAMENTO) 
  REFERENCES PBANDI_T_PAGAMENTO (ID_PAGAMENTO),
  CONSTRAINT FK_PBANDI_T_QT_PARTE_DOC_SP_02
  FOREIGN KEY (ID_QUOTA_PARTE_DOC_SPESA) 
  REFERENCES PBANDI_T_QUOTA_PARTE_DOC_SPESA (ID_QUOTA_PARTE_DOC_SPESA),
  CONSTRAINT FK_PBANDI_T_UTENTE_268 
  FOREIGN KEY (ID_UTENTE_INS) 
  REFERENCES PBANDI_T_UTENTE (ID_UTENTE),
  CONSTRAINT FK_PBANDI_T_UTENTE_269
  FOREIGN KEY (ID_UTENTE_AGG) 
  REFERENCES PBANDI_T_UTENTE (ID_UTENTE)
  ON DELETE SET NULL);
  
 CREATE INDEX IE1_PBANDI_R_PAG_QTCL_PT_DC_SP ON PBANDI_R_PAG_QTCL_PARTE_DOC_SP
(ID_QUOTA_PARTE_DOC_SPESA)
TABLESPACE PBANDI_IDX;

--PBANDI_T_RETTIFICA_QUOTA_PARTE
CREATE TABLE PBANDI_T_RETTIFICA_QUOTA_PARTE
(
  ID_RETTIFICA_QUOTA_PARTE     NUMBER(8)        NOT NULL,
  DT_RETTIFICA                 DATE             NOT NULL,
  IMPORTO_RETTIFICA            NUMBER(15,2)     NOT NULL,
  RIFERIMENTO                  VARCHAR2(255),
  ID_QUOTA_PARTE_DOC_SPESA               NUMBER(8)        NOT NULL,
  ID_UTENTE_INS                NUMBER(8)        NOT NULL,
  ID_UTENTE_AGG                NUMBER(8)
)
TABLESPACE PBANDI_TBL;

COMMENT ON TABLE  PBANDI_T_RETTIFICA_QUOTA_PARTE IS 'Rettifiche di spesa per bandi Cultura';


ALTER TABLE PBANDI_T_RETTIFICA_QUOTA_PARTE ADD (
  CONSTRAINT PK_PBANDI_T_RETTIF_QUOTA_PARTE
  PRIMARY KEY
  (ID_RETTIFICA_QUOTA_PARTE)
  USING INDEX TABLESPACE PBANDI_IDX);

ALTER TABLE PBANDI_T_RETTIFICA_QUOTA_PARTE ADD (
  CONSTRAINT FK_PBANDI_T_QT_PARTE_DOC_SP_03 
  FOREIGN KEY (ID_QUOTA_PARTE_DOC_SPESA) 
  REFERENCES PBANDI_T_QUOTA_PARTE_DOC_SPESA (ID_QUOTA_PARTE_DOC_SPESA),
  CONSTRAINT FK_PBANDI_T_UTENTE_270 
  FOREIGN KEY (ID_UTENTE_INS) 
  REFERENCES PBANDI_T_UTENTE (ID_UTENTE),
  CONSTRAINT FK_PBANDI_T_UTENTE_271 
  FOREIGN KEY (ID_UTENTE_AGG) 
  REFERENCES PBANDI_T_UTENTE (ID_UTENTE));

CREATE INDEX IE1_PBANDI_T_RETT_QUOTA_PARTE ON PBANDI_T_RETTIFICA_QUOTA_PARTE
(ID_QUOTA_PARTE_DOC_SPESA)
TABLESPACE PBANDI_IDX;


/* Già creato
--PBANDI_R_BANDO_MODALITA_AGEVOL
ALTER TABLE PBANDI_R_BANDO_MODALITA_AGEVOL ADD 
(MINIMO_IMPORTO_AGEVOLATO   NUMBER(17,2));
*/

--PBANDI_T_CONTO_ECONOMICO
ALTER TABLE PBANDI_T_CONTO_ECONOMICO ADD 
(PERC_SP_GEN_FUNZ   NUMBER(5,2));


