/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

ALTER TABLE PBANDI_W_ATTIVITA_PREGRESSE MODIFY(DATA  NULL);


CREATE TABLE PBANDI_R_BANDO_DETT_INTERVENTO
(
  PROGR_BANDO_LINEA_INTERVENTO  NUMBER(8),
  COD_DETT_INTERVENTO           VARCHAR2(20),
  ID_TEMA_PRIORITARIO           NUMBER(3)
)
TABLESPACE PBANDI_SMALL_TBL;

ALTER TABLE PBANDI_R_BANDO_DETT_INTERVENTO ADD (
  CONSTRAINT PK_PBANDI_R_BANDO_DETT_INTERV
  PRIMARY KEY
  (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO)
   USING INDEX TABLESPACE PBANDI_SMALL_IDX);


CREATE INDEX IE_PBANDI_R_BANDO_DET_INTER_02 ON PBANDI_R_BANDO_DETT_INTERVENTO
(ID_TEMA_PRIORITARIO)
TABLESPACE PBANDI_SMALL_IDX;


ALTER TABLE PBANDI_R_BANDO_DETT_INTERVENTO ADD (
  CONSTRAINT FK_PBANDI_D_TEMA_PRIORITAR_04 
  FOREIGN KEY (ID_TEMA_PRIORITARIO) 
  REFERENCES PBANDI_D_TEMA_PRIORITARIO (ID_TEMA_PRIORITARIO),
  CONSTRAINT FK_PBANDI_R_BANDO_LINEA_INT_19 
  FOREIGN KEY (PROGR_BANDO_LINEA_INTERVENTO) 
  REFERENCES PBANDI_R_BANDO_LINEA_INTERVENT (PROGR_BANDO_LINEA_INTERVENTO));
  
CREATE INDEX IE_PBANDI_T_DICHIARAZ_SPESA_01 ON PBANDI_T_DICHIARAZIONE_SPESA
(ID_PROGETTO)
TABLESPACE PBANDI_SMALL_IDX;



