/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

/*
*** script da eseguire ad ogni rilascio
*/

-- PBANDI_D_ERRORE_BATCH
INSERT INTO PBANDI_D_ERRORE_BATCH
VALUES
('E169','Fondo di garanzia non caricato daq xml',null);
INSERT INTO PBANDI_D_ERRORE_BATCH
VALUES
('E170','pck_pbandi_caricamento_xml - MainFondi concluso con errori',null);
COMMIT;
--
-- CONFIGURAZIONE NUOVO TASK
-- PBANDI_D_TASK
Insert into PBANDI_D_TASK
   (ID_TASK, DESCR_BREVE_TASK, DESCR_TASK, ID_TIPO_TASK, ID_METODO_TASK)
 Values
   (55, 'GEST-AFFIDAMENTI', 'Gestione affidamenti', 9, 29);
-- PBANDI_T_STEP_PROCESSO
UPDATE PBANDI_T_STEP_PROCESSO SET ID_TASK = 55 WHERE ID_STEP_PROCESSO = 121; 
-- PBANDI_C_RUOLO_DI_PROCESSO
Insert into PBANDI_C_RUOLO_DI_PROCESSO
   (ID_RUOLO_DI_PROCESSO, CODICE, DESC_RUOLO_DI_PROCESSO, ID_DEFINIZIONE_PROCESSO)
 Values
   (10, 'Istruttore_Affidamenti', 'Ruolo di processo preposto alla validazione degli affidamenti', 9);
-- PBANDI_D_TIPO_ANAGRAFICA
Insert into PBANDI_D_TIPO_ANAGRAFICA
   (ID_TIPO_ANAGRAFICA, DESC_BREVE_TIPO_ANAGRAFICA, DESC_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA, ID_RUOLO_HELP, ID_CATEG_ANAGRAFICA)
 Values
   (25, 'ISTR-AFFIDAMENTI', 'Istruttore Affidamenti', TO_DATE('02/21/2018 10:43:57', 'MM/DD/YYYY HH24:MI:SS'), 
    2, 1);
-- PBANDI_R_RUOLO_TIPO_ANAGRAFICA
Insert into PBANDI_R_RUOLO_TIPO_ANAGRAFICA
   (ID_RUOLO_DI_PROCESSO, ID_TIPO_ANAGRAFICA, ID_RUOLO_TIPO_ANAGRAFICA)
 Values
   (10, 25, 104);
-- PBANDI_R_STEP_PROCESSO_RUOLO
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (105, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (117, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (118, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (119, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (120, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (121, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (122, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (138, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (139, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (144, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (145, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (146, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (155, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (157, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (163, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (164, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (165, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (166, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (168, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (169, 10);
-- PBANDI_D_PERMESSO
Insert into PBANDI_D_PERMESSO
   (ID_PERMESSO, DESC_BREVE_PERMESSO, DESC_PERMESSO, DT_INIZIO_VALIDITA)
 Values
   (155, 'OPEAGG0001', 'Gestione affidamenti', TO_DATE('02/21/2018 11:04:38', 'MM/DD/YYYY HH24:MI:SS'));
-- PBANDI_R_PERMESSO_TIPO_ANAGRAF
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (4, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (5, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (6, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (10, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (11, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (15, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (17, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (23, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (24, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (26, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (28, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (32, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (38, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (43, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (45, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (49, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (65, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (66, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (75, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (78, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (79, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (80, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (104, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (118, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (136, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_R_PERMESSO_TIPO_ANAGRAF
   (ID_PERMESSO, ID_TIPO_ANAGRAFICA, DT_INIZIO_VALIDITA)
 Values
   (155, 25, TO_DATE('01/01/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
--
COMMIT;
--
-- PBANDI_D_STATO_AFFIDAMENTO
Insert into PBANDI_D_STATO_AFFIDAMENTO
   (ID_STATO_AFFIDAMENTO, DESC_BREVE_STATO_AFFIDAMENTO, DESC_STATO_AFFIDAMENTO)
 Values
   (1, 'DAINVIARE', 'Da inviare');
Insert into PBANDI_D_STATO_AFFIDAMENTO
   (ID_STATO_AFFIDAMENTO, DESC_BREVE_STATO_AFFIDAMENTO, DESC_STATO_AFFIDAMENTO)
 Values
   (2, 'INVERIFICA', 'In verifica');
Insert into PBANDI_D_STATO_AFFIDAMENTO
   (ID_STATO_AFFIDAMENTO, DESC_BREVE_STATO_AFFIDAMENTO, DESC_STATO_AFFIDAMENTO)
 Values
   (3, 'VPARZIALE', 'Verifica parziale');
Insert into PBANDI_D_STATO_AFFIDAMENTO
   (ID_STATO_AFFIDAMENTO, DESC_BREVE_STATO_AFFIDAMENTO, DESC_STATO_AFFIDAMENTO)
 Values
   (4, 'VDEFINITIVA', 'Verifica definitiva');
COMMIT;
--
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 1);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 2);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 6);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 7);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 8);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 9);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 10);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 11);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 12);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 13);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 1, 15);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 16);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 17);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 18);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 19);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 20);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 22);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 24);
Insert into PBANDI_R_DOC_INDEX_TIPO_ANAG
   (ID_TIPO_ANAGRAFICA, ID_UTENTE_INS, ID_TIPO_DOCUMENTO_INDEX)
 Values
   (25, 0, 25);
COMMIT;

--
update PBANDI_C_VERSIONE
set VERSIONE_DB = '3.8.0';

insert into PBANDI_C_ENTITA
(ID_ENTITA, NOME_ENTITA, FLAG_DA_TRACCIARE) 
(select seq_PBANDI_C_ENTITA.nextval,tabs.TABLE_NAME,'S'
from all_tables tabs
where tabs.OWNER = (select decode(instr(user,'_RW'),0,user,replace(user,'_RW',null)) from dual)
and tabs.TABLE_NAME like 'PBANDI_%'
and not exists (select 'x' from pbandi_c_entita where tabs.TABLE_NAME = NOME_ENTITA));

commit;

declare
  cursor curAttr is select col.COLUMN_NAME,en.id_ENTITA,col.TABLE_NAME
                    from all_tab_cols col,PBANDI_C_ENTITA en
                    where col.owner = (select decode(instr(user,'_RW'),0,user,replace(user,'_RW',null)) from dual)
                    and col.TABLE_NAME like 'PBANDI_%'
                    and col.COLUMN_NAME not like 'SYS_%'
                    and col.TABLE_NAME = en.NOME_ENTITA
                    and not exists (select 'x' from PBANDI_C_ATTRIBUTO att 
                                    where col.COLUMN_NAME = att.NOME_ATTRIBUTO
                                    and att.id_entita = en.id_ENTITA);
                                    
  nPosiz  PLS_INTEGER := NULL;                                                                          
begin
  for recAttr in curAttr loop

    BEGIN
      SELECT POSITION
      INTO   nPosiz 
      FROM   all_CONSTRAINTS A,all_CONS_COLUMNS B
      WHERE  A.CONSTRAINT_TYPE = 'P'
      AND    A.TABLE_NAME      = recAttr.TABLE_NAME
      AND    A.CONSTRAINT_NAME = B.CONSTRAINT_NAME
      AND    COLUMN_NAME       = recAttr.COLUMN_NAME;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        nPosiz := NULL;
    END;
    
    insert into PBANDI_C_ATTRIBUTO
    (ID_ATTRIBUTO, 
     NOME_ATTRIBUTO, 
     FLAG_DA_TRACCIARE, 
     ID_ENTITA,
     KEY_POSITION_ID) 
    values
    (SEQ_PBANDI_C_ATTRIBUTO.NEXTVAL,
     recAttr.COLUMN_NAME,
     'N',
     recAttr.id_ENTITA,
     nPosiz);
  end loop;
  COMMIT;
end;
/

