/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

-- PBANDI_T_ECONOMIE
ALTER TABLE  PBANDI_T_ECONOMIE  RENAME COLUMN NOTE_UTILIZZO TO NOTE_RICEZIONE;
ALTER TABLE  PBANDI_T_ECONOMIE DROP CONSTRAINT FK_PBANDI_T_CONTO_ECONOMICO_05;
ALTER TABLE  PBANDI_T_ECONOMIE  RENAME COLUMN ID_CONTO_ECONOMICO_CEDENTE TO ID_PROGETTO_CEDENTE;
UPDATE PBANDI_T_ECONOMIE  te
SET  ID_PROGETTO_CEDENTE = (SELECT tp.ID_PROGETTO 
                                                FROM PBANDI_T_CONTO_ECONOMICO tc, PBANDI_T_PROGETTO tp 
                                                WHERE TC.ID_DOMANDA = TP.ID_DOMANDA AND 
                                                           te.ID_PROGETTO_CEDENTE = tc.ID_CONTO_ECONOMICO);
ALTER TABLE  PBANDI_T_ECONOMIE ADD DATA_CESSIONE DATE;
ALTER TABLE PBANDI_T_ECONOMIE  RENAME COLUMN DATA_RICEVIMENTO TO  DATA_RICEZIONE;
ALTER TABLE PBANDI_T_ECONOMIE ADD DATA_INSERIMENTO DATE; 
ALTER TABLE PBANDI_T_ECONOMIE ADD DATA_MODIFICA DATE;
ALTER TABLE PBANDI_T_ECONOMIE ADD ID_UTENTE_INS NUMBER(8);
ALTER TABLE PBANDI_T_ECONOMIE ADD ID_UTENTE_AGG NUMBER(8);

ALTER TABLE  PBANDI_T_ECONOMIE ADD 
CONSTRAINT FK_PBANDI_T_PROGETTO_45
FOREIGN KEY (ID_PROGETTO_CEDENTE)
REFERENCES PBANDI_T_PROGETTO (ID_PROGETTO);

-- INDEX
CREATE INDEX IE1_PBANDI_T_ECONOMIE ON PBANDI_T_ECONOMIE (ID_PROGETTO_CEDENTE)  TABLESPACE PBANDI_IDX;
CREATE INDEX IE2_PBANDI_T_ECONOMIE ON PBANDI_T_ECONOMIE (ID_PROGETTO_RICEVENTE)  TABLESPACE PBANDI_IDX;
--
--
-- PBANDI_R_ECONOM_SOGG_FINANZIAT
CREATE TABLE PBANDI_R_ECONOM_SOGG_FINANZIAT
(
ID_ECONOMIA  NUMBER(8)    NOT NULL,
ID_SOGGETTO_FINANZIATORE  NUMBER(3)    NOT NULL, -- PBANDI_D_SOGGETTO_FINANZIATORE   
PERC_QUOTA_SOGG_FINANZIAT NUMBER(5,2),        
ID_UTENTE_INS NUMBER(8)    NOT NULL,        
ID_UTENTE_AGG NUMBER(8) ,  
DT_INSERIMENTO DATE   NOT NULL,          
DT_AGGIORNAMENTO DATE ,      
IMP_QUOTA_ECON_SOGG_FINANZIAT NUMBER(13,2) 
); 


 --PK
ALTER TABLE PBANDI_R_ECONOM_SOGG_FINANZIAT ADD  
 ( 
  CONSTRAINT PK_PBANDI_R_ECON_SOGG_FINANZ PRIMARY KEY (ID_ECONOMIA,ID_SOGGETTO_FINANZIATORE)
  USING INDEX
  TABLESPACE PBANDI_IDX 
 );
--FK
ALTER TABLE PBANDI_R_ECONOM_SOGG_FINANZIAT ADD 
CONSTRAINT FK_PBANDI_R_ECON_SOGG_FIN_01
 FOREIGN KEY (ID_ECONOMIA)
 REFERENCES PBANDI_T_ECONOMIE (ID_ECONOMIA);
--FK
 ALTER TABLE PBANDI_R_ECONOM_SOGG_FINANZIAT ADD 
CONSTRAINT FK_PBANDI_R_ECON_SOGG_FIN_02
 FOREIGN KEY (ID_SOGGETTO_FINANZIATORE)
 REFERENCES PBANDI_D_SOGGETTO_FINANZIATORE (ID_SOGGETTO_FINANZIATORE);
 --
 -- CERTIFICAZIONE
 -- PBANDI_T_DETT_PROP_CERT_ANNUAL
 
ALTER TABLE PBANDI_T_DETT_PROP_CERT_ANNUAL ADD DATA_AGG DATE;
ALTER TABLE PBANDI_T_DETT_PROP_CERT_ANNUAL ADD ID_UTENTE_AGG NUMBER(8);

CREATE OR REPLACE TYPE ObjPropCertAnnual AS OBJECT
(idProgetto                      NUMBER(8),
 Importo_Recuperi                NUMBER(17,2),
 Importo_Revoche                 NUMBER(17,2),
 Importo_Soppressioni            NUMBER(17,2)
)
/
CREATE OR REPLACE TYPE PBANDI.LISTPROPCERTANNUAL AS TABLE OF ObjPropCertAnnual
/
Insert into PBANDI_D_NOME_BATCH
   (ID_NOME_BATCH, NOME_BATCH, DESC_BATCH)
 Values
   (19, 'PBAN-AGG-CERT-FOTOGRAF', 'Procedura che aggiorna la fotografia della proposta di certificazione');
Insert into PBANDI_D_ERRORE_BATCH
   (CODICE_ERRORE, DESCRIZIONE)
 Values
   ('E168', 'Errore nella procedura certificazione - Aggiorna fotografia anno contabile');
COMMIT;

-- INDEX
CREATE INDEX IE1_PBANDI_R_ECON_SOGG_FINANZ ON PBANDI_R_ECONOM_SOGG_FINANZIAT (ID_SOGGETTO_FINANZIATORE) TABLESPACE PBANDI_IDX;