/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

/*
*** script da eseguire ad ogni rilascio
*/

update PBANDI_C_VERSIONE
set VERSIONE_DB = '3.28.5';

-- Processo 4

Insert into PBANDI_T_PROCESSO
   (ID_PROCESSO, DESCR_PROCESSO)
 Values
   (4, 'Rendicontazione per SAL');


Insert into PBANDI_D_TASK
   (ID_TASK, DESCR_BREVE_TASK, DESCR_TASK, ID_TIPO_TASK)
 Values
   (79, 'CRONOPROGRAMMA_FASI', 'Cronoprogramma per fasi', 7);



Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK, ID_PROCESSO)
 Values
   (210, 9, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (211, 9, 1, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (212, 9, 2, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (213, 1, 3, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (214, 3, 4, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (215, 2, 8, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (216, 4, 8, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (217, 8, 5, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (219, 8, 7, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (220, 5, 10, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (222, 10, 11, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (224, 10, 13, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (225, 8, 14, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (226, 14, 15, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (227, 8, 16, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (228, 8, 17, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (229, 8, 18, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (230, 8, 55, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (231, 8, 20, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (232, 10, 21, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (233, 10, 22, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (234, 10, 23, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (235, 10, 25, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (236, 11, 26, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (238, 26, 24, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (239, 8, 27, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (240, 8, 28, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (241, 8, 33, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (242, 8, 54, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (243, 54, 37, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (244, 37, 38, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (245, 8, 35, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (246, 24, 45, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (247, 45, 46, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (248, 23, 47, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (249, 50, 49, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (250, 15, 49, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (251, 16, 49, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (252, 45, 50, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (253, 47, 51, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (254, 10, 39, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (255, 26, 40, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (256, 52, 29, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (257, 53, 31, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (258, 28, 52, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (259, 28, 53, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (260, 10, 56, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (261, 8, 57, 4);
Insert into PBANDI_T_STEP_PROCESSO
   (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
 Values
   (265, 8, 79, 4);


SET DEFINE OFF;
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (4, 5);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (5, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (5, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (8, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (8, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (8, 6);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (8, 7);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (9, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (9, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (9, 6);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (9, 7);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (10, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (10, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (10, 6);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (10, 7);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (10, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (13, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (13, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (13, 6);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (13, 7);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (13, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (14, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (14, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (14, 6);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (14, 7);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (14, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (15, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (15, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (15, 6);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (15, 7);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (15, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (16, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (16, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (17, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (17, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (18, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (18, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (19, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (19, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (20, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (20, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (20, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (21, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (21, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (21, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (21, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (21, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (22, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (22, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (23, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (23, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (24, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (24, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (25, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (25, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (25, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (26, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (26, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (30, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (30, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (31, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (38, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (38, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (39, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (39, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (39, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (43, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (43, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (44, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (44, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (45, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (45, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (46, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (46, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (55, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (55, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (55, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (56, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (56, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (56, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (57, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (57, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (57, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (63, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (63, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (64, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (64, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (64, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (65, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (65, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (65, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (66, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (66, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (66, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (68, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (68, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (68, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (69, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (69, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (69, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (104, 5);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (105, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (105, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (105, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (108, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (108, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (108, 6);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (108, 7);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (109, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (109, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (109, 6);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (109, 7);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (110, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (110, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (110, 6);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (110, 7);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (110, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (110, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (113, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (113, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (113, 6);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (113, 7);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (113, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (114, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (114, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (114, 6);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (114, 7);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (114, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (116, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (116, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (117, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (117, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (117, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (118, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (118, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (118, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (119, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (119, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (119, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (120, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (120, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (120, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (120, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (121, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (121, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (121, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (121, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (122, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (122, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (122, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (123, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (123, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (124, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (124, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (125, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (125, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (125, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (126, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (126, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (130, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (130, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (131, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (138, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (138, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (138, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (139, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (139, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (139, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (139, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (144, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (144, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (144, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (145, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (145, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (145, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (146, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (146, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (146, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (155, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (155, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (155, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (155, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (156, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (156, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (156, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (157, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (157, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (157, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (157, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (163, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (163, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (163, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (164, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (164, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (164, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (164, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (165, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (165, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (165, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (165, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (166, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (166, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (166, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (166, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (168, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (168, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (168, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (168, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (169, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (169, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (169, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (169, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (172, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (172, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (172, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (173, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (173, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (177, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (177, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (178, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (178, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (179, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (180, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (181, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (182, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (183, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (184, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (185, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (186, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (187, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (188, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (190, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (191, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (191, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (192, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (193, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (194, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (195, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (196, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (197, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (200, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (201, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (202, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (203, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (209, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (209, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (209, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (213, 5);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (214, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (214, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (214, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (217, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (217, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (217, 6);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (217, 7);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (219, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (219, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (219, 6);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (219, 7);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (219, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (219, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (222, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (222, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (222, 6);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (222, 7);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (222, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (225, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (225, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (226, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (226, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (226, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (227, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (227, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (227, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (228, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (228, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (228, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (229, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (229, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (229, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (229, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (230, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (230, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (230, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (230, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (231, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (231, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (231, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (232, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (232, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (233, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (233, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (234, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (234, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (234, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (235, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (235, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (238, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (238, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (239, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (241, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (241, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (241, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (242, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (242, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (242, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (242, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (243, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (243, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (243, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (244, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (244, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (244, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (245, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (245, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (245, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (246, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (246, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (246, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (246, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (247, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (247, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (247, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (248, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (248, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (248, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (248, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (252, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (252, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (252, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (253, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (253, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (253, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (253, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (254, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (254, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (254, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (254, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (255, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (255, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (255, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (255, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (256, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (256, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (256, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (256, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (257, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (257, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (257, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (257, 10);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (260, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (260, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (260, 9);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (261, 2);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (261, 4);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (265, 6);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (266, 6);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (268, 5);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (269, 1);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (269, 3);
Insert into PBANDI_R_STEP_PROCESSO_RUOLO
   (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
 Values
   (269, 10);
COMMIT;



-- qtes
insert into pbandi_d_task (ID_TASK, DESCR_BREVE_TASK, DESCR_TASK, ID_TIPO_TASK, ID_METODO_TASK, ID_MULTI_TASK, ID_METODO_TASK_INTEGR)
values (101, 'GESTIONE-QTES', 'Gestione QTES', 7, null, null, null);

insert into pbandi_t_step_processo (ID_STEP_PROCESSO, ID_TASK_PREC, ID_TASK, ID_PROCESSO)
values (271, 8, 101, 4);

insert into PBANDI_R_STEP_PROCESSO_RUOLO (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
values (271, 1);

insert into PBANDI_R_STEP_PROCESSO_RUOLO (ID_STEP_PROCESSO, ID_RUOLO_DI_PROCESSO)
values (271, 2);
--
commit;

-- PBANDI_C_PARAMETRI_COMPENSI
insert into PBANDI_C_PARAMETRI_COMPENSI (ID_PARAMETRO_COMPENSO, CATEGORIA, ORE_SETTIMANALI, COMPENSO_DOVUTO_MENSILE, GIORNI_LAVORABILI_SETTIMANALI, ORARIO_MEDIO_GIORNALIERO, BUDGET_INIZIALE_TIROCINANTE, BUDGET_INIZIALE_IMPRESA, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA)
values (1, 1, 30, 450.00, 4, 7.50, 2700.00, 1800.00, to_date('07-09-2023', 'dd-mm-yyyy'), null);
insert into PBANDI_C_PARAMETRI_COMPENSI (ID_PARAMETRO_COMPENSO, CATEGORIA, ORE_SETTIMANALI, COMPENSO_DOVUTO_MENSILE, GIORNI_LAVORABILI_SETTIMANALI, ORARIO_MEDIO_GIORNALIERO, BUDGET_INIZIALE_TIROCINANTE, BUDGET_INIZIALE_IMPRESA, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA)
values (2, 2, 30, 450.00, 5, 6.00, 2700.00, 1800.00, to_date('07-09-2023', 'dd-mm-yyyy'), null);
insert into PBANDI_C_PARAMETRI_COMPENSI (ID_PARAMETRO_COMPENSO, CATEGORIA, ORE_SETTIMANALI, COMPENSO_DOVUTO_MENSILE, GIORNI_LAVORABILI_SETTIMANALI, ORARIO_MEDIO_GIORNALIERO, BUDGET_INIZIALE_TIROCINANTE, BUDGET_INIZIALE_IMPRESA, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA)
values (3, 3, 30, 450.00, 6, 5.00, 2700.00, 1800.00, to_date('07-09-2023', 'dd-mm-yyyy'), null);
insert into PBANDI_C_PARAMETRI_COMPENSI (ID_PARAMETRO_COMPENSO, CATEGORIA, ORE_SETTIMANALI, COMPENSO_DOVUTO_MENSILE, GIORNI_LAVORABILI_SETTIMANALI, ORARIO_MEDIO_GIORNALIERO, BUDGET_INIZIALE_TIROCINANTE, BUDGET_INIZIALE_IMPRESA, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA)
values (4, 4, 40, 600.00, 5, 8.00, 3600.00, 900.00, to_date('07-09-2023', 'dd-mm-yyyy'), null);
insert into PBANDI_C_PARAMETRI_COMPENSI (ID_PARAMETRO_COMPENSO, CATEGORIA, ORE_SETTIMANALI, COMPENSO_DOVUTO_MENSILE, GIORNI_LAVORABILI_SETTIMANALI, ORARIO_MEDIO_GIORNALIERO, BUDGET_INIZIALE_TIROCINANTE, BUDGET_INIZIALE_IMPRESA, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA)
values (5, 5, 40, 600.00, 6, 6.67, 3600.00, 900.00, to_date('07-09-2023', 'dd-mm-yyyy'), null);
COMMIT;
-- PBANDI_D_TIPO_DOCUMENTO_SPESA
insert into PBANDI_D_TIPO_DOCUMENTO_SPESA (ID_TIPO_DOCUMENTO_SPESA, DESC_BREVE_TIPO_DOC_SPESA, DESC_TIPO_DOCUMENTO_SPESA, DT_INIZIO_VALIDITA, DT_FINE_VALIDITA)
values (92, 'CMT', 'Compenso mensile tirocinante', to_date('07-09-2023 18:37:09', 'dd-mm-yyyy hh24:mi:ss'), null);
insert into PBANDI_D_TIPO_DOCUMENTO_SPESA (ID_TIPO_DOCUMENTO_SPESA, DESC_BREVE_TIPO_DOC_SPESA, DESC_TIPO_DOCUMENTO_SPESA, DT_INIZIO_VALIDITA, DT_FINE_VALIDITA)
values (93, 'CIA', 'Compenso impresa artigiana', to_date('07-09-2023 18:37:09', 'dd-mm-yyyy hh24:mi:ss'), null);
-- PBANDI_D_VOCE_DI_SPESA
insert into PBANDI_D_VOCE_DI_SPESA (ID_VOCE_DI_SPESA, ID_VOCE_DI_SPESA_PADRE, DESC_VOCE_DI_SPESA, DT_INIZIO_VALIDITA, DT_FINE_VALIDITA, COD_TIPO_VOCE_DI_SPESA, ID_VOCE_DI_SPESA_MONIT, ID_TIPOLOGIA_VOCE_DI_SPESA, FLAG_EDIT, FLAG_SPESE_GESTIONE)
values (seq_pbandi_d_voce_di_spesa.NEXTVAL, NULL, 'Spese della impresa artigiana', to_date('07-09-2023 17:24:36', 'dd-mm-yyyy hh24:mi:ss'), null, 'SIA', null, null, '', '');

/*
-- PBANDI_D_TEMPLATE_NOTIFICA
insert into PBANDI_D_TEMPLATE_NOTIFICA (ID_TEMPLATE_NOTIFICA, DESCR_BREVE_TEMPLATE_NOTIFICA, COMP_SUBJECT, COMP_MESSAGE, ID_ENTITA)
values (32, 'NotificaDecessoBeneficiario', 'Notifica decesso beneficiario', '<div id="notifica"><p>Si notifica che in data ${data} il beneficiario con codice fiscale ${cod_fiscale} e denominazione ${denominazione} è deceduto.', null);

insert into PBANDI_D_TEMPLATE_NOTIFICA (ID_TEMPLATE_NOTIFICA, DESCR_BREVE_TEMPLATE_NOTIFICA, COMP_SUBJECT, COMP_MESSAGE, ID_ENTITA)
values (33, 'NotificaCambioResidenzaBeneficiario', 'Notifica cambio residenza beneficiario', '<div id="notifica"><p>Si notifica che in data ${data} il beneficiario con codice fiscale ${cod_fiscale} e denominazione ${denominazione} ha cambiato residenza.', null);

insert into PBANDI_D_TEMPLATE_NOTIFICA (ID_TEMPLATE_NOTIFICA, DESCR_BREVE_TEMPLATE_NOTIFICA, COMP_SUBJECT, COMP_MESSAGE, ID_ENTITA)
values (34, 'NotificaRinunciaBeneficiario', 'Notifica rinuncia beneficiario', '<div id="notifica"><p>Si notifica che in data ${data} il beneficiario con codice fiscale ${cod_fiscale} e denominazione ${denominazione} ha comunicato la rinuncia al buono.', null);

insert into PBANDI_D_TEMPLATE_NOTIFICA (ID_TEMPLATE_NOTIFICA, DESCR_BREVE_TEMPLATE_NOTIFICA, COMP_SUBJECT, COMP_MESSAGE, ID_ENTITA)
values (35, 'NotificaPresenzaAltreMisure', 'Notifica presenza altre misure beneficiario', '<div id="notifica"><p>Si notifica che per il beneficiario con codice fiscale ${cod_fiscale} e denominazione ${denominazione} è stata riscontrata la presenza di altre misure. Di seguito un dettaglio: ${descr_notifica}.', null);

insert into PBANDI_D_TEMPLATE_NOTIFICA (ID_TEMPLATE_NOTIFICA, DESCR_BREVE_TEMPLATE_NOTIFICA, COMP_SUBJECT, COMP_MESSAGE, ID_ENTITA)
values (36, 'NotificaModificaISEE', 'Notifica modifica ISEE', '<div id="notifica"><p>Si notifica che per il beneficiario con codice fiscale ${cod_fiscale} e denominazione ${denominazione} è stata riscontrata una modifica all''ISEE. Di seguito un dettaglio: ${descr_notifica}.', null);

insert into PBANDI_D_TEMPLATE_NOTIFICA (ID_TEMPLATE_NOTIFICA, DESCR_BREVE_TEMPLATE_NOTIFICA, COMP_SUBJECT, COMP_MESSAGE, ID_ENTITA)
values (37, 'NotificaCambioIBAN', 'NotificaCambioIBAN', '<div id="notifica"><p>Si notifica che per il beneficiario con codice fiscale ${cod_fiscale} e denominazione ${denominazione} è stata ricevuta una modifica dell''IBAN. Di seguito l''IBAN indicato dal beneficiario: ${iban}.', null);
--
*/






declare
  cursor curAttr is select col.COLUMN_NAME,en.id_ENTITA,col.TABLE_NAME
                    from all_tab_cols col,PBANDI_C_ENTITA en
                    where col.owner = (select decode(instr(user,'_RW'),0,user,replace(user,'_RW',null)) from dual)
                    and col.TABLE_NAME like 'PBANDI_%'
                    and col.COLUMN_NAME not like 'SYS_%'
                    and col.TABLE_NAME = en.NOME_ENTITA
                    and not exists (select 'x' from PBANDI_C_ATTRIBUTO att 
                                    where col.COLUMN_NAME = att.NOME_ATTRIBUTO
                                    and att.id_entita = en.id_ENTITA);
                                    
  nPosiz  PLS_INTEGER := NULL;                                                                          
begin
  for recAttr in curAttr loop

    BEGIN
      SELECT POSITION
      INTO   nPosiz 
      FROM   all_CONSTRAINTS A,all_CONS_COLUMNS B
      WHERE  A.CONSTRAINT_TYPE = 'P'
      AND    A.TABLE_NAME      = recAttr.TABLE_NAME
      AND    A.CONSTRAINT_NAME = B.CONSTRAINT_NAME
      AND    COLUMN_NAME       = recAttr.COLUMN_NAME;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        nPosiz := NULL;
    END;
    
    insert into PBANDI_C_ATTRIBUTO
    (ID_ATTRIBUTO, 
     NOME_ATTRIBUTO, 
     FLAG_DA_TRACCIARE, 
     ID_ENTITA,
     KEY_POSITION_ID) 
    values
    (SEQ_PBANDI_C_ATTRIBUTO.NEXTVAL,
     recAttr.COLUMN_NAME,
     'N',
     recAttr.id_ENTITA,
     nPosiz);
  end loop;
  COMMIT;
end;
/