/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

--PBANDI_R_BANDO_LINEA_INTERVENT
ALTER TABLE PBANDI_R_BANDO_LINEA_INTERVENT ADD ID_LINEA_AZIONE  NUMBER(5);
-- PBANDI_D_LINEA_AZIONE
CREATE TABLE PBANDI_D_LINEA_AZIONE
(ID_LINEA_AZIONE  NUMBER(5),
COD_CLASSIFICAZIONE_LA VARCHAR2(200),
COD_LINEA_AZIONE VARCHAR2(50)
);
-- PK
ALTER TABLE PBANDI_D_LINEA_AZIONE ADD 
(CONSTRAINT PK_PBANDI_D_LINEA_AZIONE PRIMARY KEY (ID_LINEA_AZIONE)
USING INDEX  TABLESPACE PBANDI_IDX);
-- PBANDI_R_BANDO_LINEA_INTERVENT
-- FK 
ALTER TABLE PBANDI_R_BANDO_LINEA_INTERVENT ADD
CONSTRAINT FK_PBANDI_D_LINEA_AZIONE_01
FOREIGN KEY (ID_LINEA_AZIONE) 
REFERENCES PBANDI_D_LINEA_AZIONE (ID_LINEA_AZIONE);
-- INDEX
CREATE INDEX IE6_PBANDI_R_BANDO_LIN_INTERV ON PBANDI_R_BANDO_LINEA_INTERVENT (ID_LINEA_AZIONE) TABLESPACE PBANDI_IDX;
--
-- PBANDI_T_PROGETTO
ALTER TABLE PBANDI_T_PROGETTO ADD  COD_PROCEDURA_ORIG VARCHAR2(30);
ALTER TABLE PBANDI_T_PROGETTO ADD ID_TIPO_TERRITORIO NUMBER(5);
ALTER TABLE PBANDI_T_PROGETTO MODIFY ID_TIPO_TERRITORIO DEFAULT 7;
ALTER TABLE PBANDI_T_PROGETTO MODIFY COD_PROCEDURA_ORIG DEFAULT 5;
-- 
--PBANDI_D_TIPO_TERRITORIO 
 CREATE TABLE PBANDI_D_TIPO_TERRITORIO
 (
ID_TIPO_TERRITORIO  NUMBER(5),
COD_CLASSIFICAZIONE_TT VARCHAR2(200),
DESCR_CLASSIFICAZIONE_TT VARCHAR2(1000)
);
--PK
ALTER TABLE PBANDI_D_TIPO_TERRITORIO ADD 
(CONSTRAINT PK_PBANDI_D_TIPO_TERRITORIO PRIMARY KEY (ID_TIPO_TERRITORIO)
USING INDEX  TABLESPACE PBANDI_IDX);
--FK
ALTER TABLE PBANDI_T_PROGETTO ADD
CONSTRAINT FK_PBANDI_T_PROGETTO_46
FOREIGN KEY (ID_TIPO_TERRITORIO) 
REFERENCES PBANDI_D_TIPO_TERRITORIO (ID_TIPO_TERRITORIO);
--INDEX
CREATE INDEX IE7_PBANDI_T_PROGETTO ON PBANDI_T_PROGETTO (ID_TIPO_TERRITORIO) TABLESPACE PBANDI_IDX;
--