/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

--PBANDI_T_TRACCIAMENTO
ALTER TABLE PBANDI_T_TRACCIAMENTO ADD (DETTAGLIO_ERRORE CLOB)  LOB (DETTAGLIO_ERRORE) STORE AS (TABLESPACE PBANDI_MEDIUM_LOB  INDEX (TABLESPACE PBANDI_MEDIUM_LOB));

--PBANDI_W_CARICAMENTO_XML
ALTER TABLE PBANDI_W_CARICAMENTO_XML
 ADD (XML_VALID XMLTYPE);
 
COMMENT ON COLUMN PBANDI_W_CARICAMENTO_XML.XML_VALID IS 'In questa colonna l''Xml viene validato con lo schema XSD';

--PBANDI_S_CARICAMENTO_XML
ALTER TABLE PBANDI_S_CARICAMENTO_XML
 ADD (FLAG_VALIDO  VARCHAR2(2));
 
--PBANDI_C_XSD
CREATE TABLE PBANDI_C_XSD
(
  ID_XSD             INTEGER,
  NOME_XSD           VARCHAR2(100),
  NOME_ELEM          VARCHAR2(100),
  NOME_ELEM_PADRE    VARCHAR2(100),
  NOME_ELEM_PADRE_2  VARCHAR2(100),
  FLAG_REQUIRED      NUMBER(1),
  TIPO_ELEM          VARCHAR2(30),
  ID_XSD_ELEM_OPT    INTEGER,
  DT_INIZIO_VALIDITA DATE,
  DT_FINE_VALIDITA   DATE
)
TABLESPACE PBANDI_SMALL_TBL;



ALTER TABLE PBANDI_C_XSD ADD (
  CONSTRAINT PK_PBANDI_C_XSD
  PRIMARY KEY
  (ID_XSD)
  USING INDEX TABLESPACE PBANDI_SMALL_IDX,
  CONSTRAINT AK1_PBANDI_C_XSD
  UNIQUE (NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2)
  USING INDEX TABLESPACE PBANDI_SMALL_IDX);

 

COMMENT ON TABLE PBANDI_C_XSD IS 'Definizione XSD per validazione elementi obbligatori ';
COMMENT ON COLUMN PBANDI_C_XSD.ID_XSD_ELEM_OPT IS 'Elemento alternativo se elemento corrente non valorizzato ';


--PBANDI_D_INVIO_ANOMALIE_FLUSSI
CREATE TABLE PBANDI_D_INVIO_ANOMALIE_FLUSSI
(
  ID_INVIO_ANOMALIE_FLUSSI  NUMBER(6),
  EMAIL                     VARCHAR2(200),
  ID_NOME_BATCH  			NUMBER(3)  NOT NULL,
  DT_INIZIO_VALIDITA        DATE       NOT NULL,
  DT_FINE_VALIDITA          DATE
)
TABLESPACE PBANDI_SMALL_TBL;



ALTER TABLE PBANDI_D_INVIO_ANOMALIE_FLUSSI ADD (
  CONSTRAINT PK_PBANDI_D_INVIO_ANOM_FLUSSI
  PRIMARY KEY
  (ID_INVIO_ANOMALIE_FLUSSI)
  USING INDEX TABLESPACE PBANDI_SMALL_IDX);

ALTER TABLE PBANDI_D_INVIO_ANOMALIE_FLUSSI ADD (
  CONSTRAINT FK_PBANDI_D_NOME_BATCH_03
  FOREIGN KEY (ID_NOME_BATCH) 
  REFERENCES PBANDI_D_NOME_BATCH (ID_NOME_BATCH)
  );

--PBANDI_D_ERRORE_BATCH
ALTER TABLE PBANDI_D_ERRORE_BATCH
 ADD (FLAG_NOTIFICA_MAIL  VARCHAR2(1));
 
COMMENT ON COLUMN PBANDI_D_ERRORE_BATCH.FLAG_NOTIFICA_MAIL IS 'Settare a "S" se si vuole inviare i log con il codice relativo tramite email';

--PBANDI_T_DETT_PROPOSTA_CERTIF
ALTER TABLE PBANDI_T_DETT_PROPOSTA_CERTIF
 ADD (IMP_CERTIFICAZIONE_NETTO_BCK  NUMBER(17,2));


COMMENT ON COLUMN PBANDI_T_DETT_PROPOSTA_CERTIF.IMP_CERTIFICAZIONE_NETTO_BCK IS 'Backup del valore della colonna IMPORTO_CERTIFICATO_NETTO quando questo è negativo';
