/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

-- PBANDI_T_DETT_PROP_CERT_ANNUAL
ALTER TABLE PBANDI_T_DETT_PROP_CERT_ANNUAL  RENAME COLUMN IMPORTO_REVOCHE TO IMPORTO_REVOCHE_RILEV_CUM;
ALTER TABLE PBANDI_T_DETT_PROP_CERT_ANNUAL  RENAME COLUMN IMPORTO_RECUPERI TO IMPORTO_RECUPERI_CUM;
ALTER TABLE PBANDI_T_DETT_PROP_CERT_ANNUAL  RENAME COLUMN IMPORTO_SOPPRESSIONI TO IMPORTO_SOPPRESSIONI_CUM;
ALTER TABLE PBANDI_T_DETT_PROP_CERT_ANNUAL  RENAME COLUMN IMPORTO_EROGAZIONI TO IMPORTO_EROGAZIONI_CUM;
ALTER TABLE PBANDI_T_DETT_PROP_CERT_ANNUAL  RENAME COLUMN IMPORTO_PAGAMENTI_VALIDATI TO IMPORTO_PAGAM_VALID_CUM;
ALTER TABLE PBANDI_T_DETT_PROP_CERT_ANNUAL  RENAME COLUMN IMPORTO_CERTIFICAZIONE_NETTO TO IMPORTO_CERTIF_NETTO_ANNUAL;
ALTER TABLE PBANDI_T_DETT_PROP_CERT_ANNUAL  DROP COLUMN TOTALE_EROGAZIONI_CUMULATE;
ALTER TABLE  PBANDI_T_DETT_PROP_CERT_ANNUAL DROP COLUMN AVANZAMENTO_ANNUALE;
--
-- PBANDI_V_CERTIF_CUM_ANNI_PREC
DROP VIEW PBANDI_V_CERTIF_CUM_ANNI_PREC;
--
CREATE OR REPLACE VIEW PBANDI.PBANDI_V_CERTIF_CUM_ANNI_PREC
AS
     (SELECT ID_PROGETTO,
            SUM (NVL (pca.IMPORTO_REVOCHE_RILEV_CUM, 0)) IMPORTO_REVOCHE_RILEV_CUM,
            SUM (NVL (pca.IMPORTO_RECUPERI_CUM, 0)) IMPORTO_RECUPERI_CUM,
            SUM (NVL (pca.IMPORTO_SOPPRESSIONI_CUM, 0)) IMPORTO_SOPPRESSIONI_CUM,
            SUM (NVL (pca.IMPORTO_EROGAZIONI_CUM, 0)) IMPORTO_EROGAZIONI_CUM,
            SUM (NVL (pca.IMPORTO_PAGAM_VALID_CUM, 0)) IMPORTO_PAGAM_VALID_CUM,
            SUM (NVL (pca.IMPORTO_CERTIF_NETTO_ANNUAL, 0)) IMPORTO_CERTIF_NETTO_ANNUAL
       FROM PBANDI_T_DETT_PROP_CERT_ANNUAL pca,
            PBANDI_T_PROPOSTA_CERTIFICAZ pc,
            PBANDI_T_DETT_PROPOSTA_CERTIF dpc
      WHERE     pca.ID_PROPOSTA_CERTIFICAZ = pc.ID_PROPOSTA_CERTIFICAZ
            AND dpc.ID_DETT_PROPOSTA_CERTIF = pca.ID_DETT_PROPOSTA_CERTIF
            AND pc.ID_PERIODO IS NOT NULL
            AND pc.ID_STATO_PROPOSTA_CERTIF IN (16, 17)
   GROUP BY ID_PROGETTO
   );
--
--PBANDI_T_FORNITORE
ALTER TABLE PBANDI_T_FORNITORE ADD COD_UNI_IPA VARCHAR2(16);
-- PBANDI_W_FONDI_GARANZIA - PBANDI_T_FONDI_GARANZIA
ALTER TABLE PBANDI_W_FONDI_GARANZIA RENAME  COLUMN FORMA_ECONOMICA TO FORMA_GIURIDICA;
ALTER TABLE PBANDI_T_FONDI_GARANZIA RENAME  COLUMN FORMA_ECONOMICA TO FORMA_GIURIDICA;
ALTER TABLE PBANDI_W_FONDI_GARANZIA ADD (DATA_IMPEGNO DATE, DATA_DISIMPEGNO DATE);
ALTER TABLE PBANDI_T_FONDI_GARANZIA ADD (DATA_IMPEGNO DATE, DATA_DISIMPEGNO DATE);
-- PBANDI_T_PROGETTO
ALTER TABLE PBANDI_T_PROGETTO ADD ID_TIPO_PROCEDURA_ORIG NUMBER(3);
--FK
ALTER TABLE   PBANDI_T_PROGETTO ADD (
  CONSTRAINT FK_PBANDI_D_TIPO_PROC_ORIG_02
  FOREIGN KEY (ID_TIPO_PROCEDURA_ORIG)
  REFERENCES PBANDI_D_TIPO_PROCEDURA_ORIG (ID_TIPO_PROCEDURA_ORIG));
-- INDEX
CREATE INDEX IE6_PBANDI_T_PROGETTO ON PBANDI_T_PROGETTO (ID_TIPO_PROCEDURA_ORIG) TABLESPACE PBANDI_IDX;
--  PBANDI_T_FORNITORE
ALTER TABLE PBANDI_T_FORNITORE ADD FLAG_PUBBLICO_PRIVATO NUMBER (1);
