/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

ALTER TABLE  PBANDI_R_SOGG_PROGETTO_SEDE ADD FLAG_PEC_CONFERMATA VARCHAR2(1);
COMMENT ON COLUMN PBANDI_R_SOGG_PROGETTO_SEDE.FLAG_PEC_CONFERMATA IS 'S=Confermata, N=Non confermata';
ALTER TABLE PBANDI_R_SOGG_PROGETTO_SEDE ADD CONSTRAINT CHK_FLAG_PEC_CONFERMATA
    CHECK (FLAG_PEC_CONFERMATA in ('S','N'));

--
-- PBANDI_R_SUBCONTRATTO_AFFIDAMENTO

DROP TABLE PBANDI_R_SUBCONTRATTO_AFFID;

CREATE TABLE PBANDI_R_SUBCONTRATTO_AFFID
(
ID_SUBCONTRATTO_AFFIDAMENTO NUMBER(8)NOT NULL,
ID_FORNITORE NUMBER(8) NOT NULL,
ID_APPALTO NUMBER(8) NOT NULL,
ID_SUBCONTRAENTE NUMBER (8) NOT NULL,
DT_SUBCONTRATTO DATE NOT NULL,
NOME_SUBCONTRATTO VARCHAR2(500) NOT NULL,
RIFERIMENTO_SUBCONTRATTO VARCHAR2(100) NOT NULL,
IMPORTO_SUBCONTRATTO NUMBER(17,2) NOT NULL,
DT_INVIO_VERIFICA_AFFIDAMENTO DATE,
FLAG_INVIO_VERIFICA_AFFID VARCHAR2(2)
);

alter table PBANDI_R_SUBCONTRATTO_AFFID
  add constraint CHK_FLAG_INVIO_VERIFICA_AFFID
  check (FLAG_INVIO_VERIFICA_AFFID IN ('SI', NULL));

-- PK
ALTER TABLE PBANDI_R_SUBCONTRATTO_AFFID ADD 
(CONSTRAINT PK_PBANDI_R_SUBCONTRATTO_AFFID 
 PRIMARY KEY (ID_SUBCONTRATTO_AFFIDAMENTO)
USING INDEX TABLESPACE PBANDI_IDX);
-- FK
ALTER TABLE PBANDI_R_SUBCONTRATTO_AFFID ADD (
  CONSTRAINT fk_pbandi_t_fornitore_04
  FOREIGN KEY (ID_FORNITORE) 
  REFERENCES pbandi_t_fornitore (ID_FORNITORE));
-- FK
ALTER TABLE PBANDI_R_SUBCONTRATTO_AFFID ADD (
  CONSTRAINT fk_pbandi_t_appalto_08
  FOREIGN KEY (ID_APPALTO) 
  REFERENCES pbandi_t_appalto(ID_APPALTO));
-- FK
ALTER TABLE PBANDI_R_SUBCONTRATTO_AFFID ADD (
  CONSTRAINT fk_pbandi_t_fornitore_05
  FOREIGN KEY (ID_SUBCONTRAENTE) 
  REFERENCES pbandi_t_fornitore (ID_FORNITORE));

-- IDX
CREATE INDEX IE1_PBANDI_R_SUBCONTRAT_AFFID  ON PBANDI_R_SUBCONTRATTO_AFFID (ID_APPALTO) TABLESPACE PBANDI_IDX;
CREATE INDEX IE2_PBANDI_R_SUBCONTRAT_AFFID  ON PBANDI_R_SUBCONTRATTO_AFFID (ID_SUBCONTRAENTE) TABLESPACE PBANDI_IDX;

alter table PBANDI_R_SUBCONTRATTO_AFFID
  add constraint AK1_PBANDI_R_SUBCONTR_AFFID unique (ID_FORNITORE, ID_APPALTO, ID_SUBCONTRAENTE);

-- SEQ
CREATE SEQUENCE SEQ_PBANDI_R_SUBCONTR_AFFID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_T_DICH_MENS_WS"                                      */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_T_DICH_MENS_WS (
    ID_DICHIARAZIONE_SPESA NUMBER(8) NOT NULL,
    ANNO NUMBER NOT NULL,
    MESE VARCHAR2(2) NOT NULL,
    ESITO VARCHAR2(2),
    ID_PROGETTO NUMBER(8) NOT NULL,
    FLAG_SABBATICO VARCHAR2(1),
    DT_INSERIMENTO DATE NOT NULL,
    DT_AGGIORNAMENTO DATE,
    ID_UTENTE_AGG NUMBER(8),
    DT_FINE_VALIDITA DATE,
    CONSTRAINT PK_PBANDI_T_DICH_MENS_WS PRIMARY KEY (ID_DICHIARAZIONE_SPESA, ANNO, MESE) USING INDEX TABLESPACE PBANDI_IDX
);

CREATE INDEX IDX_PBANDI_T_DICH_MENS_WS_1 ON PBANDI_T_DICH_MENS_WS (ID_PROGETTO)  TABLESPACE PBANDI_IDX;

CREATE INDEX IDX_PBANDI_T_DICH_MENS_WS_2 ON PBANDI_T_DICH_MENS_WS (ID_UTENTE_AGG)  TABLESPACE PBANDI_IDX;

ALTER TABLE PBANDI_T_DICH_MENS_WS ADD CONSTRAINT CC_PBANDI_T_DICH_MENS_WS_ESITO 
    CHECK (esito in ('OK','KO'));

ALTER TABLE PBANDI_T_DICH_MENS_WS ADD CONSTRAINT CC_PBANDI_T_DICH_MENS_WS_01 
    CHECK (flag_sabbatico in ('S'));

COMMENT ON TABLE PBANDI_T_DICH_MENS_WS IS 'Tabella di validazione mensilità su dichiarazione di spesa';

COMMENT ON COLUMN PBANDI_T_DICH_MENS_WS.FLAG_SABBATICO IS 'S=Mensilità dichiarazione su cui non è richiesta la validazione';

/* ---------------------------------------------------------------------- */
/* Add table "PBANDI_C_CONFIG_CUP_WS"                                     */
/* ---------------------------------------------------------------------- */

CREATE TABLE PBANDI_C_CONFIG_CUP_WS (
    COD_SPORTELLO VARCHAR2(40) NOT NULL,
    COD_AREA_TERRIT VARCHAR2(40) NOT NULL,
    DESC_AREA_TERRIT VARCHAR2(255),
    NUM_DETERMINA VARCHAR2(40),
    DT_DETERMINA DATE,
    CUP VARCHAR2(20),
    CONSTRAINT PK_PBANDI_C_CONFIG_CUP_WS PRIMARY KEY (COD_SPORTELLO, COD_AREA_TERRIT)
);

ALTER TABLE PBANDI_T_DICH_MENS_WS ADD CONSTRAINT FK_PBANDI_T_DICHIARAZ_SPESA_11 
    FOREIGN KEY (ID_DICHIARAZIONE_SPESA) REFERENCES PBANDI_T_DICHIARAZIONE_SPESA (ID_DICHIARAZIONE_SPESA);

ALTER TABLE PBANDI_T_DICH_MENS_WS ADD CONSTRAINT FK_PBANDI_T_PROGETTO_94 
    FOREIGN KEY (ID_PROGETTO) REFERENCES PBANDI_T_PROGETTO (ID_PROGETTO);

ALTER TABLE PBANDI_T_DICH_MENS_WS ADD CONSTRAINT FK_PBANDI_T_UTENTE_416 
    FOREIGN KEY (ID_UTENTE_AGG) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
	
-- PBANDI_D_ITER
alter table PBANDI_D_ITER ADD PERC_IMPORTO_CONTRIB  NUMBER(5,2);

-- pbandi_r_bando_linea_intervent
alter table pbandi_r_bando_linea_intervent ADD FLAG_ART58 varchar2(2);
alter table pbandi_r_bando_linea_intervent
  add constraint CHK_FLAG_ART58
  check (FLAG_ART58 IN ('SI','NO',NULL));

--  PBANDI_R_PROGETTO_ITER
ALTER TABLE PBANDI_R_PROGETTO_ITER ADD ESTREMI_ATTO_APPROVAZIONE VARCHAR2(200);

--PBANDI_R_SOGG_BANDO_LIN_INT
ALTER TABLE PBANDI_R_SOGG_BANDO_LIN_INT DROP PRIMARY KEY;

ALTER TABLE PBANDI_R_SOGG_BANDO_LIN_INT ADD (
  CONSTRAINT PK_PBANDI_R_SOGG_BANDO_LIN_INT
 PRIMARY KEY
 (ID_SOGGETTO, ID_TIPO_ANAGRAFICA,PROGR_BANDO_LINEA_INTERVENTO)
    USING INDEX 
    TABLESPACE PBANDI_IDX);


-- PBANDI_C_MODELLO_QTES 
CREATE TABLE PBANDI_C_MODELLO_QTES 
( ID_MODELLO_QTES NUMBER(3) NOT NULL, 
  NOME_MODELLO_QTES VARCHAR2(255) NOT NULL, 
  VERSIONE_MODELLO_QTES VARCHAR2(3) NOT NULL, 
  DESC_BREVE_MODELLO_QTES VARCHAR2(10)NOT NULL,
  HTML_QTES CLOB NOT NULL, 
  ID_UTENTE_INS NUMBER(8) NOT NULL, 
  ID_UTENTE_AGG NUMBER(8),
  CONSTRAINT PK_PBANDI_C_MODELLO_QTES PRIMARY KEY (ID_MODELLO_QTES) USING INDEX TABLESPACE PBANDI_IDX
);
-- fk
ALTER TABLE PBANDI_C_MODELLO_QTES ADD CONSTRAINT fk_pbandi_t_utente_417 
    FOREIGN KEY (ID_UTENTE_INS) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
-- idx
CREATE INDEX IDX_PBANDI_C_MODELLO_QTES_01 ON PBANDI_C_MODELLO_QTES (ID_UTENTE_INS)  TABLESPACE PBANDI_IDX;

-- PBANDI_R_MOD_QTES_BAN_LI_INT
CREATE TABLE PBANDI_R_MOD_QTES_BAN_LI_INT 
(ID_MODELLO_QTES NUMBER(3) NOT NULL, 
 PROGR_BANDO_LINEA_INTERVENTO NUMBER(8) NOT NULL, 
 ID_UTENTE_INS NUMBER(8) NOT NULL, 
 ID_UTENTE_AGG NUMBER(8), 
   CONSTRAINT PK_PBANDI_R_MOD_QTES_LI_INT PRIMARY KEY (ID_MODELLO_QTES, PROGR_BANDO_LINEA_INTERVENTO)
 );
 -- fk
 ALTER TABLE PBANDI_R_MOD_QTES_BAN_LI_INT  ADD CONSTRAINT fk_pbandi_t_utente_418 
    FOREIGN KEY (ID_UTENTE_INS) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
 ALTER TABLE PBANDI_R_MOD_QTES_BAN_LI_INT  ADD CONSTRAINT fk_pbandi_t_utente_419 
    FOREIGN KEY (ID_UTENTE_AGG) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
 ALTER TABLE PBANDI_R_MOD_QTES_BAN_LI_INT  ADD CONSTRAINT fk_pbandi_r_bando_linea_int_34
    FOREIGN KEY (PROGR_BANDO_LINEA_INTERVENTO) REFERENCES PBANDI_R_BANDO_LINEA_INTERVENT (PROGR_BANDO_LINEA_INTERVENTO);
 ALTER TABLE PBANDI_R_MOD_QTES_BAN_LI_INT  ADD CONSTRAINT fk_pbandi_c_modello_qtes_01
    FOREIGN KEY (ID_MODELLO_QTES) REFERENCES PBANDI_C_MODELLO_QTES (ID_MODELLO_QTES);
 
 -- idx
CREATE INDEX IDX_PBANDI_R_MOD_QTES_LI_01 ON PBANDI_R_MOD_QTES_BAN_LI_INT (ID_UTENTE_INS)  TABLESPACE PBANDI_IDX;
CREATE INDEX IDX_PBANDI_R_MOD_QTES_LI_02 ON PBANDI_R_MOD_QTES_BAN_LI_INT (ID_UTENTE_AGG)  TABLESPACE PBANDI_IDX;
CREATE INDEX IDX_PBANDI_R_MOD_QTES_LI_03 ON PBANDI_R_MOD_QTES_BAN_LI_INT (PROGR_BANDO_LINEA_INTERVENTO)  TABLESPACE PBANDI_IDX;

 -- seq
 CREATE SEQUENCE SEQ_PBANDI_R_MOD_QTES_LI_INT
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  

-- PBANDI_T_QTES_HTML_PROGETTO
CREATE TABLE PBANDI_T_QTES_HTML_PROGETTO 
(ID_QTES_HTML_PROGETTO NUMBER(8) NOT NULL, 
   ID_PROGETTO NUMBER(8) NOT NULL, 
   HTML_QTES_PROGETTO CLOB NOT NULL, 
   DT_INSERIMENTO DATE NOT NULL, 
   DT_AGGIORNAMENTO DATE, 
   ID_UTENTE_INS NUMBER(8) NOT NULL, 
   ID_UTENTE_AGG NUMBER(8), 
   CONSTRAINT PK_PBANDI_T_QTES_HTML_PROGETTO PRIMARY KEY (ID_QTES_HTML_PROGETTO) USING INDEX TABLESPACE PBANDI_IDX
);

-- fk
 ALTER TABLE PBANDI_T_QTES_HTML_PROGETTO   ADD CONSTRAINT fk_pbandi_t_utente_420 
    FOREIGN KEY (ID_UTENTE_INS) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
 ALTER TABLE PBANDI_T_QTES_HTML_PROGETTO   ADD CONSTRAINT fk_pbandi_t_utente_421 
    FOREIGN KEY (ID_UTENTE_AGG) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
 ALTER TABLE PBANDI_T_QTES_HTML_PROGETTO   ADD CONSTRAINT fk_pbandi_t_progetto_95
    FOREIGN KEY (ID_PROGETTO) REFERENCES PBANDI_T_PROGETTO (ID_PROGETTO);

 -- idx
CREATE INDEX IDX_PBANDI_T_QTES_HTML_PROG_01 ON PBANDI_T_QTES_HTML_PROGETTO (ID_UTENTE_INS)  TABLESPACE PBANDI_IDX;
CREATE INDEX IDX_PBANDI_T_QTES_HTML_PROG_02 ON PBANDI_T_QTES_HTML_PROGETTO (ID_UTENTE_AGG)  TABLESPACE PBANDI_IDX;
CREATE INDEX IDX_PBANDI_T_QTES_HTML_PROG_03 ON PBANDI_T_QTES_HTML_PROGETTO (ID_PROGETTO)  TABLESPACE PBANDI_IDX;

 -- seq
 CREATE SEQUENCE SEQ_PBANDI_T_QTES_HTML_PROG
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  
  -- PBANDI_D_FASI_QTES
CREATE TABLE PBANDI_D_FASI_QTES  
( ID_COLONNA_QTES  NUMBER(8) NOT NULL, 
  DESC_COLONNA_QTES   VARCHAR2(200)NOT NULL,
  DESC_BREVE_COLONNA_QTES VARCHAR2(10)NOT NULL,
   CONSTRAINT PK_PBANDI_D_FASI_QTES PRIMARY KEY (ID_COLONNA_QTES) USING INDEX TABLESPACE PBANDI_IDX
);

 -- seq
 CREATE SEQUENCE SEQ_PBANDI_D_FASI_QTES
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  
-- PBANDI_T_DATI_QTES_PROGETTO
CREATE TABLE PBANDI_T_DATI_QTES_PROGETTO  
 (ID_PROGETTO NUMBER(8) NOT NULL, 
 ID_COLONNA_QTES NUMBER(3) NOT NULL,
 ESTREMI_ATTO_APPROVAZIONE VARCHAR2(200) NOT NULL,
 DT_INSERIMENTO DATE NOT NULL, 
 DT_AGGIORNAMENTO DATE, 
 ID_UTENTE_INS NUMBER(8,0) NOT NULL, 
 ID_UTENTE_AGG NUMBER(8,0), 
 CONSTRAINT PK_PBANDI_T_DATI_QTES_PROGETTO PRIMARY KEY (ID_PROGETTO, ID_COLONNA_QTES) USING INDEX TABLESPACE PBANDI_IDX
 );
 
 -- fk
 ALTER TABLE PBANDI_T_DATI_QTES_PROGETTO   ADD CONSTRAINT fk_pbandi_t_utente_422 
    FOREIGN KEY (ID_UTENTE_INS) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
 ALTER TABLE PBANDI_T_DATI_QTES_PROGETTO   ADD CONSTRAINT fk_pbandi_t_utente_423 
    FOREIGN KEY (ID_UTENTE_AGG) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
 ALTER TABLE PBANDI_T_DATI_QTES_PROGETTO   ADD CONSTRAINT fk_pbandi_t_progetto_96
    FOREIGN KEY (ID_PROGETTO) REFERENCES PBANDI_T_PROGETTO (ID_PROGETTO);
  ALTER TABLE PBANDI_T_DATI_QTES_PROGETTO   ADD CONSTRAINT fk_PBANDI_D_FASI_QTES_01
    FOREIGN KEY (ID_COLONNA_QTES) REFERENCES PBANDI_D_FASI_QTES (ID_COLONNA_QTES);
 -- idx
CREATE INDEX IDX_PBANDI_T_DATI_QTES_PROG_01 ON PBANDI_T_DATI_QTES_PROGETTO (ID_UTENTE_INS)  TABLESPACE PBANDI_IDX;
CREATE INDEX IDX_PBANDI_T_DATI_QTES_PROG_02 ON PBANDI_T_DATI_QTES_PROGETTO(ID_UTENTE_AGG)  TABLESPACE PBANDI_IDX;
CREATE INDEX IDX_PBANDI_T_DATI_QTES_PROG_03 ON PBANDI_T_DATI_QTES_PROGETTO (ID_PROGETTO)  TABLESPACE PBANDI_IDX;
CREATE INDEX IDX_PBANDI_T_DATI_QTES_PROG_04 ON PBANDI_T_DATI_QTES_PROGETTO (ID_COLONNA_QTES)  TABLESPACE PBANDI_IDX;
 -- seq
 CREATE SEQUENCE SEQ_PBANDI_T_DATI_QTES_PROG
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

