/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

--- In aggiunta a quanto già stato configurato in collaudo

-- PBANDI_R_BANDO_LIN_TIPO_PERIOD
ALTER TABLE PBANDI_R_BANDO_LIN_TIPO_PERIOD
ADD ID_PERIODO NUMBER(8);
--FK
ALTER TABLE PBANDI_R_BANDO_LIN_TIPO_PERIOD ADD
CONSTRAINT FK_PBANDI_T_PERIODO_06
FOREIGN KEY (ID_PERIODO) 
REFERENCES PBANDI_T_PERIODO (ID_PERIODO);
--INDEX
CREATE INDEX IE1_PBANDI_R_BANDO_LIN_TIPO_P ON  PBANDI_R_BANDO_LIN_TIPO_PERIOD (ID_PERIODO) TABLESPACE PBANDI_IDX;

---

-- PBANDI.PBANDI_V_PROP_ASSE_SIF
CREATE OR REPLACE FORCE VIEW PBANDI.PBANDI_V_PROP_ASSE_SIF
(
   ID_PROPOSTA_CERTIFICAZ,
   ID_ASSE,
   DESC_BREVE_LINEA,
   DESC_LINEA,
   COSTO_AMMESSO,
   CONTRIBUTO_PUBBLICO_CONCESSO,
   IMPORTO_EROGAZIONI --
)
AS
   WITH PROP_ASSE
        AS (SELECT                                           /*+MATERIALIZE */
                   a.id_proposta_certificaz,
                   a.id_progetto,
                   e.id_linea_di_intervento,
                   PCK_PBANDI_CERTIfICAZIONE.ReturnAsse (
                      e.id_linea_di_intervento)
                      id_asse,
                   NVL (costo_ammesso, 0) costo_ammesso,
                   NVL (contributo_pubblico_concesso, 0)
                      contributo_pubblico_concesso,
                   NVL (a.importo_erogazioni,0)  importo_erogazioni --
              FROM PBANDI_T_DETT_PROPOSTA_CERTIF a,
                   PBANDI_T_PROPOSTA_CERTIFICAZ b,
                   PBANDI_T_PROGETTO c,
                   PBANDI_T_DOMANDA d,
                   PBANDI_R_BANDO_LINEA_INTERVENT e
             WHERE     a.id_proposta_certificaz = b.id_proposta_certificaz
                   AND a.id_progetto = c.id_progetto
                   AND c.id_domanda = d.id_domanda
                   AND e.progr_bando_linea_intervento =
                          d.progr_bando_linea_intervento
                   AND e.flag_sif = 'S')
     SELECT a.id_proposta_certificaz,
            a.id_asse,
            MIN (b.desc_breve_linea) desc_breve_linea,
            MIN (b.desc_linea) desc_linea,
            SUM (a.costo_ammesso) costo_ammesso,
            SUM (a.contributo_pubblico_concesso) contributo_pubblico_concesso,
            SUM (a.IMPORTO_EROGAZIONI) importo_erogazioni --
       FROM PROP_ASSE a, pbandi_d_linea_di_intervento b
      WHERE a.id_asse = b.id_linea_di_intervento
   GROUP BY a.id_proposta_certificaz, a.id_asse;

-- PBANDI_T_PROGETTO
ALTER TABLE PBANDI_T_PROGETTO MODIFY COD_PROCEDURA_ORIG DEFAULT NULL;
ALTER TABLE PBANDI_T_PROGETTO MODIFY ID_TIPO_PROCEDURA_ORIG DEFAULT 5;

-- REVOCHE IRREGOLARITA'
--PBANDI_D_CLASS_REVOCA_IRREG
 CREATE TABLE PBANDI_D_CLASS_REVOCA_IRREG
 (
ID_CLASS_REVOCA_IRREG NUMBER(5),
DESCRIZIONE VARCHAR2(1000)
);
--PK
ALTER TABLE PBANDI_D_CLASS_REVOCA_IRREG ADD 
(CONSTRAINT PK_PBANDI_D_CLASS_REVOCA_IRREG PRIMARY KEY (ID_CLASS_REVOCA_IRREG)
USING INDEX  TABLESPACE PBANDI_IDX);
--PBANDI_T_DETT_REVOCA_IRREG 
 CREATE TABLE PBANDI_T_DETT_REVOCA_IRREG 
 (
ID_DETT_REVOCA_IRREG  NUMBER(5),
ID_REVOCA NUMBER(8),
ID_IRREGOLARITA NUMBER(8), 
ID_CLASS_REVOCA_IRREG NUMBER(5),
IMPORTO NUMBER(17,2),
IMPORTO_AUDIT NUMBER(17,2),
TIPOLOGIA VARCHAR2(500)
);
--PK
ALTER TABLE PBANDI_T_DETT_REVOCA_IRREG  ADD 
(CONSTRAINT PK_PBANDI_T_DETT_REVOCA_IRREG  PRIMARY KEY (ID_DETT_REVOCA_IRREG)
USING INDEX  TABLESPACE PBANDI_IDX);
--FK
ALTER TABLE PBANDI_T_DETT_REVOCA_IRREG ADD
CONSTRAINT FK_PBANDI_D_CLASS_REV_IRREG_01
FOREIGN KEY (ID_CLASS_REVOCA_IRREG) 
REFERENCES PBANDI_D_CLASS_REVOCA_IRREG (ID_CLASS_REVOCA_IRREG);
--FK
ALTER TABLE PBANDI_T_DETT_REVOCA_IRREG ADD
CONSTRAINT FK_PBANDI_R_REVOCA_IRREG_01
FOREIGN KEY (ID_REVOCA,ID_IRREGOLARITA) 
REFERENCES PBANDI_R_REVOCA_IRREG (ID_REVOCA,ID_IRREGOLARITA);
--INDEX
CREATE UNIQUE INDEX AK1_PBANDI_T_DETT_REVOCA_IRREG ON PBANDI_T_DETT_REVOCA_IRREG (ID_REVOCA,ID_IRREGOLARITA,ID_CLASS_REVOCA_IRREG) TABLESPACE PBANDI_IDX;

-- PBANDI_R_DS_DETT_REVOCA_IRREG 
CREATE TABLE PBANDI_R_DS_DETT_REVOCA_IRREG 
 (
ID_DETT_REVOCA_IRREG  NUMBER(5),
ID_DICHIARAZIONE_SPESA NUMBER (8),  
IMPORTO_IRREGOLARE_DS  NUMBER(17,2)
);
--PK
ALTER TABLE  PBANDI_R_DS_DETT_REVOCA_IRREG  ADD 
(CONSTRAINT PK_PBANDI_R_DS_DETT_REV_IRREG  PRIMARY KEY (ID_DETT_REVOCA_IRREG, ID_DICHIARAZIONE_SPESA)
USING INDEX  TABLESPACE PBANDI_IDX);
--FK
ALTER TABLE PBANDI_R_DS_DETT_REVOCA_IRREG ADD
CONSTRAINT FK_PBANDI_T_DETT_REV_IRREG_01
FOREIGN KEY (ID_DETT_REVOCA_IRREG) 
REFERENCES PBANDI_T_DETT_REVOCA_IRREG (ID_DETT_REVOCA_IRREG);
--FK
ALTER TABLE PBANDI_R_DS_DETT_REVOCA_IRREG ADD
CONSTRAINT FK_PBANDI_T_DICHIARAZ_SPESA_06
FOREIGN KEY (ID_DICHIARAZIONE_SPESA) 
REFERENCES PBANDI_T_DICHIARAZIONE_SPESA (ID_DICHIARAZIONE_SPESA);
--INDEX
CREATE INDEX IE1_PBANDI_R_DS_DETT_REV_IRREG ON PBANDI_R_DS_DETT_REVOCA_IRREG (ID_DICHIARAZIONE_SPESA) TABLESPACE PBANDI_IDX;
--PBANDI_C_MODELLO
ALTER TABLE PBANDI_C_MODELLO ADD FRONTESPIZIO BLOB;

/* Modifica sospesa in produzione -- > Gli ambienti di test e pre-prod sono già stati aggiornati

-- PBANDI_R_ECONOM_SOGG_FINANZIAT
ALTER TABLE PBANDI_R_ECONOM_SOGG_FINANZIAT ADD TIPOLOGIA_PROGETTO VARCHAR2(1);
COMMENT ON COLUMN PBANDI_R_ECONOM_SOGG_FINANZIAT.TIPOLOGIA_PROGETTO  IS 'C = CEDENTE E R = RICEVENTE';
ALTER TABLE PBANDI_R_ECONOM_SOGG_FINANZIAT ADD (
  CONSTRAINT CHK_TIPOLOGIA_PROGETTO
  CHECK (TIPOLOGIA_PROGETTO IN ('R', 'C', NULL))); --
--PK
ALTER TABLE PBANDI_R_ECONOM_SOGG_FINANZIAT DROP CONSTRAINT PK_PBANDI_R_ECON_SOGG_FINANZ;
DROP INDEX PK_PBANDI_R_ECON_SOGG_FINANZ;
UPDATE PBANDI_R_ECONOM_SOGG_FINANZIAT SET TIPOLOGIA_PROGETTO = 'C';
COMMIT;
ALTER TABLE  PBANDI_R_ECONOM_SOGG_FINANZIAT  ADD 
(CONSTRAINT PK_PBANDI_R_ECON_SOGG_FINANZ  PRIMARY KEY (ID_ECONOMIA, ID_SOGGETTO_FINANZIATORE,TIPOLOGIA_PROGETTO)
USING INDEX  TABLESPACE PBANDI_IDX);
*/ 

--PBANDI_T_CHECKLIST
ALTER TABLE PBANDI_T_CHECKLIST ADD IMPORTO_IRREGOLARITA NUMBER(17,2);

-- FONDI DI GARANZIA
DROP TABLE PBANDI_W_FONDI_GARANZIA;
DROP TABLE PBANDI_T_FONDI_GARANZIA;
--
-- 
CREATE TABLE PBANDI_T_FONDI_GARANZIA
(
  ID_FONDO                           NUMBER(10),
  ID_BANDO                           NUMBER(8),
  DATA_INVIO                        DATE,
  CODICE_DOMANDA              VARCHAR2(60),
  CODICE_FISCALE                 VARCHAR2(16),
  FLAG_SOGGETTO_PUBBLICO      VARCHAR2(1),
  CODICE_UNI_IPA                       VARCHAR2(10),
  DENOMINAZIONE_SOGGETTO      VARCHAR2(255),
  FORMA_GIURIDICA                     VARCHAR2(10),
  SETTORE_ATTIVITA_ECONOMICA  VARCHAR2(120),
  TITOLO_PROGETTO             VARCHAR2(500),
  TIPO_AIUTO                       VARCHAR2(2),
  CODICE_REGIONE               VARCHAR2(3),
  CODICE_PROVINCIA            VARCHAR2(3),
  CODICE_COMUNE               VARCHAR2(6),
  FINANZIAMENTO_AMMESSO       NUMBER(13,2),
  FINANZIAMENTO_EROGATO        NUMBER(13,2),
  IMPORTO_CONCESSO_GARANTI    NUMBER(13,2),
  IMPORTO_CONCESSO_FONDO       NUMBER(13,2),
  IMPORTO_GARANZIA            NUMBER(13,2),
  TIPOLOGIA_IMPEGNO           VARCHAR2(5),
  CODICE_IMPEGNO                VARCHAR2(20),
  DATA_IMPEGNO                   DATE,
  IMPORTO_IMPEGNO             NUMBER(13,2),
  CODICE_DISIMPEGNO           VARCHAR2(20),
  DATA_DISIMPEGNO              DATE,
  IMPORTO_DISIMPEGNO        NUMBER(13,2),
  CAUSALE_DISIMPEGNO         VARCHAR2(3),
  IMPORTO_ESCUSSO             NUMBER(13,2)
);

-- PBANDI_T_CHECKLIST
ALTER TABLE PBANDI_T_CHECKLIST ADD FLAG_MODOL VARCHAR2(1) DEFAULT 'N';
--
-- SEQUENCE
CREATE SEQUENCE SEQ_PBANDI_T_DETT_REVOCA_IRREG 
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
