/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

---
-- PBANDI_T_DATI_QTES_PROGETTO
DROP TABLE PBANDI_T_DATI_QTES_PROGETTO;
-- PBANDI_T_DATI_PROGETTO_QTES
CREATE TABLE PBANDI_T_DATI_PROGETTO_QTES  
 (ID_DATI_QTES NUMBER(8) NOT NULL,
 ID_PROGETTO NUMBER(8) NOT NULL, 
 ID_COLONNA_QTES NUMBER(3) NOT NULL,
 ESTREMI_ATTO_APPROVAZIONE VARCHAR2(200),
 ESTREMI_ATTO_APPROVAZIONE_CCC VARCHAR2(200),
 DT_INSERIMENTO DATE NOT NULL, 
 DT_AGGIORNAMENTO DATE, 
 ID_UTENTE_INS NUMBER(8,0) NOT NULL, 
 ID_UTENTE_AGG NUMBER(8,0), 
 CONSTRAINT PK_PBANDI_T_DATI_PROGETTO_QTES  PRIMARY KEY (ID_DATI_QTES) USING INDEX TABLESPACE PBANDI_IDX
 );
 
 -- fk
 ALTER TABLE PBANDI_T_DATI_PROGETTO_QTES    ADD CONSTRAINT fk_pbandi_t_utente_422 
    FOREIGN KEY (ID_UTENTE_INS) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
 ALTER TABLE PBANDI_T_DATI_PROGETTO_QTES   ADD CONSTRAINT fk_pbandi_t_utente_423 
    FOREIGN KEY (ID_UTENTE_AGG) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
 ALTER TABLE PBANDI_T_DATI_PROGETTO_QTES    ADD CONSTRAINT fk_pbandi_t_progetto_96
    FOREIGN KEY (ID_PROGETTO) REFERENCES PBANDI_T_PROGETTO (ID_PROGETTO);
  ALTER TABLE PBANDI_T_DATI_PROGETTO_QTES    ADD CONSTRAINT fk_PBANDI_D_FASI_QTES_01
    FOREIGN KEY (ID_COLONNA_QTES) REFERENCES PBANDI_D_FASI_QTES (ID_COLONNA_QTES);
 -- idx
CREATE INDEX IDX_PBANDI_T_DATI_PROG_QTES_01 ON PBANDI_T_DATI_PROGETTO_QTES (ID_UTENTE_INS)  TABLESPACE PBANDI_IDX;
CREATE INDEX IDX_PBANDI_T_DATI_PROG_QTES_02 ON PBANDI_T_DATI_PROGETTO_QTES (ID_UTENTE_AGG)  TABLESPACE PBANDI_IDX;
CREATE INDEX IDX_PBANDI_T_DATI_PROG_QTES_03 ON PBANDI_T_DATI_PROGETTO_QTES  (ID_PROGETTO)  TABLESPACE PBANDI_IDX;
CREATE INDEX IDX_PBANDI_T_DATI_PROG_QTES_04 ON PBANDI_T_DATI_PROGETTO_QTES  (ID_COLONNA_QTES)  TABLESPACE PBANDI_IDX;

-- PBANDI_T_QTES_HTML_PROGETTO 
DROP INDEX IDX_PBANDI_T_QTES_HTML_PROG_03;
create unique index AK1_PBANDI_T_QTES_HTML_PROG on PBANDI_T_QTES_HTML_PROGETTO (ID_PROGETTO)
  tablespace PBANDI_IDX;

-- PBANDI_R_ITER_FASI_QTES
create table PBANDI_R_ITER_FASI_QTES
(ID_ITER    NUMBER(3) not null,
 ID_COLONNA_QTES number(8) not null, 
 CONSTRAINT PK_PBANDI_R_ITER_FASI_QTES PRIMARY KEY (ID_ITER, ID_COLONNA_QTES) USING INDEX TABLESPACE PBANDI_IDX 
);
-- IDX
CREATE INDEX IDX_PBANDI_R_ITER_FASI_QTES_1 ON PBANDI_R_ITER_FASI_QTES (ID_COLONNA_QTES)  TABLESPACE PBANDI_IDX;

-- FK
ALTER TABLE PBANDI_R_ITER_FASI_QTES ADD CONSTRAINT FK_PBANDI_D_ITER_04 
    FOREIGN KEY (ID_ITER) REFERENCES PBANDI_D_ITER  (ID_ITER);
ALTER TABLE PBANDI_R_ITER_FASI_QTES ADD CONSTRAINT FK_PBANDI_D_FASI_QTES_02 
    FOREIGN KEY (ID_COLONNA_QTES) REFERENCES PBANDI_D_FASI_QTES  (ID_COLONNA_QTES);
	

-- PBANDI_R_MODELLO_FASI_QTES
create table PBANDI_R_MODELLO_FASI_QTES
(ID_COLONNA_QTES   NUMBER(8) not null,
 ID_MODELLO_QTES number(3) not null, 
 ordinamento number(3),
 CONSTRAINT PK_PBANDI_R_MODELLO_FASI_QTES PRIMARY KEY (ID_COLONNA_QTES,ID_MODELLO_QTES) USING INDEX TABLESPACE PBANDI_IDX 
);

-- IDX
CREATE INDEX IDX_PBANDI_R_MOD_FAS_QTES_1 ON PBANDI_R_MODELLO_FASI_QTES (ID_MODELLO_QTES)  TABLESPACE PBANDI_IDX;

-- FK
ALTER TABLE PBANDI_R_MODELLO_FASI_QTES ADD CONSTRAINT fk_pbandi_c_modello_qtes_02
    FOREIGN KEY (ID_MODELLO_QTES) REFERENCES PBANDI_C_MODELLO_QTES  (ID_MODELLO_QTES);
ALTER TABLE PBANDI_R_MODELLO_FASI_QTES ADD CONSTRAINT FK_PBANDI_D_FASI_QTES_03 
    FOREIGN KEY (ID_COLONNA_QTES) REFERENCES PBANDI_D_FASI_QTES  (ID_COLONNA_QTES);
	
-- PBANDI_T_DATI_QTES_PROGETTO
--alter table PBANDI_T_DATI_QTES_PROGETTO modify estremi_atto_approvazione null;

/*
-- PBANDI_T_PROPOSTA_EROGAZIONE
ALTER TABLE PBANDI_T_PROPOSTA_EROGAZIONE ADD flag_finistr varchar2(2);
ALTER TABLE PBANDI_T_PROPOSTA_EROGAZIONE add constraint chk_flag_finistr
  check (flag_finistr IN ('SI','NO',NULL));
*/  
/*   -- mc 12-09-2023 già rilasciate
-- PBANDI_C_ALLEGATI
CREATE TABLE PBANDI_C_ALLEGATI 
(ID_ALLEGATO NUMBER(3) NOT NULL,
 NOME_ALLEGATO VARCHAR2(255) NOT NULL ENABLE, --(UK)
 DESC_BREVE_ALLEGATO VARCHAR2(10) NOT NULL ENABLE, 
 HTML_ALLEGATO CLOB NOT NULL ENABLE, 
 ID_UTENTE_INS NUMBER(8) NOT NULL ENABLE, 
 ID_UTENTE_AGG NUMBER(8),
 CONSTRAINT PK_PBANDI_C_ALLEGATI  PRIMARY KEY (ID_ALLEGATO) USING INDEX TABLESPACE PBANDI_IDX
);
-- AK
alter table PBANDI_C_ALLEGATI 
  add constraint AK1_PBANDI_C_ALLEGATI  unique (NOME_ALLEGATO)
  using index  tablespace PBANDI_IDX;
	
--  PBANDI_R_AL_TIP_DOC_BAN_LI_INT   
 CREATE TABLE PBANDI_R_AL_TIP_DOC_BAN_LI_INT
(ID_ALLEGATO NUMBER(3) NOT NULL, 
 ID_TIPO_DOCUMENTO_SPESA NUMBER(3) NOT NULL, 
 PROGR_BANDO_LINEA_INTERVENTO NUMBER(8) NOT NULL, 
 ID_UTENTE_INS NUMBER(8) NOT NULL, 
 ID_UTENTE_AGG NUMBER(8),
 CONSTRAINT PK_PBANDI_R_AL_TIP_DOC_BAN_LI PRIMARY KEY (ID_ALLEGATO,ID_TIPO_DOCUMENTO_SPESA, PROGR_BANDO_LINEA_INTERVENTO) USING INDEX TABLESPACE PBANDI_IDX
);

-- FK
 ALTER TABLE PBANDI_R_AL_TIP_DOC_BAN_LI_INT   ADD CONSTRAINT fk_pbandi_t_utente_424 
    FOREIGN KEY (ID_UTENTE_INS) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
 ALTER TABLE PBANDI_R_AL_TIP_DOC_BAN_LI_INT   ADD CONSTRAINT fk_pbandi_t_utente_425 
    FOREIGN KEY (ID_UTENTE_AGG) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
 ALTER TABLE PBANDI_R_AL_TIP_DOC_BAN_LI_INT   ADD CONSTRAINT fk_PBANDI_C_ALLEGATI_01 
    FOREIGN KEY (ID_ALLEGATO) REFERENCES PBANDI_C_ALLEGATI (ID_ALLEGATO); 
ALTER TABLE PBANDI_R_AL_TIP_DOC_BAN_LI_INT   ADD CONSTRAINT fk_pbandi_d_tipo_doc_spesa_04
    FOREIGN KEY (ID_TIPO_DOCUMENTO_SPESA) REFERENCES PBANDI_D_TIPO_DOCUMENTO_SPESA (ID_TIPO_DOCUMENTO_SPESA);
  ALTER TABLE PBANDI_R_AL_TIP_DOC_BAN_LI_INT   ADD CONSTRAINT fk_pbandi_r_bando_linea_int_35
    FOREIGN KEY (PROGR_BANDO_LINEA_INTERVENTO) REFERENCES PBANDI_R_BANDO_LINEA_INTERVENT (PROGR_BANDO_LINEA_INTERVENTO);
	
	
-- IDX
 CREATE INDEX IDX_PBANDI_R_AL_TIP_DOC_BAN_01 ON PBANDI_R_AL_TIP_DOC_BAN_LI_INT (ID_UTENTE_INS)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_R_AL_TIP_DOC_BAN_02 ON PBANDI_R_AL_TIP_DOC_BAN_LI_INT (ID_UTENTE_AGG)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_R_AL_TIP_DOC_BAN_03 ON PBANDI_R_AL_TIP_DOC_BAN_LI_INT (ID_TIPO_DOCUMENTO_SPESA)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_R_AL_TIP_DOC_BAN_04 ON PBANDI_R_AL_TIP_DOC_BAN_LI_INT (PROGR_BANDO_LINEA_INTERVENTO)  TABLESPACE PBANDI_IDX;
*/

-- PBANDI_R_PROGETTO_FASE_MONIT
alter table PBANDI_R_PROGETTO_FASE_MONIT add ESTREMI_ATTO_AMMINISTRATIVO varchar2(200);

-- PBANDI_R_BANDO_LINEA_FASIMONIT
alter table PBANDI_R_BANDO_LINEA_FASIMONIT add FLAG_ESTREMI_VIS_OBB varchar2(2);

alter table PBANDI_R_BANDO_LINEA_FASIMONIT
  add constraint CHK_FLAG_ESTREMI_VIS_OBB
  check (FLAG_ESTREMI_VIS_OBB IN ('V', 'VO', NULL));
/*
-- PBANDI_R_PROGETTO_FASE_MONIT
ALTER TABLE PBANDI_R_PROGETTO_FASE_MONIT ADD ESTREMI_ATTO_APPROVAZIONE_CERT varchar2(200);
*/

-- PBANDI_T_DATI_QTES_PROGETTO
--ALTER TABLE PBANDI_T_DATI_QTES_PROGETTO ADD ESTREMI_ATTO_APPROVAZIONE_CCC VARCHAR2(200);


---- PBANDI_C_PARAMETRI_COMPENSI
-- 
CREATE TABLE PBANDI_C_PARAMETRI_COMPENSI
(ID_PARAMETRO_COMPENSO INTEGER NOT NULL,
 CATEGORIA INTEGER NOT NULL,
 ORE_SETTIMANALI INTEGER NOT NULL,
 COMPENSO_DOVUTO_MENSILE NUMBER(13,2) NOT NULL,
 GIORNI_LAVORABILI_SETTIMANALI INTEGER NOT NULL,
 ORARIO_MEDIO_GIORNALIERO NUMBER (3,2) NOT NULL,
 BUDGET_INIZIALE_TIROCINANTE NUMBER(13,2) NOT NULL,
 BUDGET_INIZIALE_IMPRESA NUMBER(13,2) NOT NULL,
 DATA_INIZIO_VALIDITA DATE NOT NULL,
 DATA_FINE_VALIDITA DATE,
 CONSTRAINT PK_PBANDI_C_PARAMETRI_COMPENSI PRIMARY KEY (ID_PARAMETRO_COMPENSO) USING INDEX TABLESPACE PBANDI_IDX
);

-- PBANDI_T_DOCUMENTO_SPESA
ALTER TABLE PBANDI_T_DOCUMENTO_DI_SPESA ADD
(
--mese_anno varchar(7), 
id_parametro_compenso integer,
gg_lavorabili_mese number,
sosp_brevi number,
sosp_lunghe_gg_tot number,
sosp_lunghe_gg_lav number,
ore_mese_lavorate number,
mese number(2),
anno number(4),
CONSTRAINT FK_PBANDI_C_PARAMETRI_COMP_01 FOREIGN KEY (id_parametro_compenso) REFERENCES PBANDI_C_PARAMETRI_COMPENSI (id_parametro_compenso)
);
-- IDX
CREATE INDEX ie2_pbandi_t_documento_di_spes ON PBANDI_T_DOCUMENTO_DI_SPESA (id_parametro_compenso)  TABLESPACE PBANDI_IDX;

-- pbandi_d_fase_monit
ALTER TABLE pbandi_d_fase_monit MODIFY COD_IGRUE_T35 varchar2(4);

-- pbandi_t_dati_qtes_progetto
--ALTER TABLE  pbandi_t_dati_qtes_progetto ADD ID_DATI_QTES NUMBER(8) not null;
--ALTER TABLE  pbandi_t_dati_qtes_progetto DROP CONSTRAINT PK_PBANDI_T_DATI_QTES_PROGETTO;
--ALTER TABLE PBANDI_T_DATI_QTES_PROGETTO
--  add constraint PK_PBANDI_T_DATI_QTES_PROGETTO primary key (ID_PROGETTO, ID_COLONNA_QTES,ID_DATI_QTES)
--  using index tablespace PBANDI_IDX;
  
-- PBANDI_T_IMPORTO_FONTI_QTES
CREATE TABLE PBANDI_T_IMPORTO_FONTI_QTES
(
ID_DATI_QTES NUMBER(8) NOT NULL,
ID_SOGGETTO_FINANZIATORE  NUMBER(3) NOT NULL,
IMPORTO NUMBER(13,2),
--ID_PROGETTO NUMBER(8),
DT_INSERIMENTO DATE NOT NULL,
DT_MODIFICA DATE,
ID_UTENTE_INS NUMBER(8) NOT NULL,
ID_UTENTE_AGG NUMBER(8),
CONSTRAINT PK_PBANDI_T_IMPORTO_FONTI_QTES PRIMARY KEY (ID_DATI_QTES,ID_SOGGETTO_FINANZIATORE) USING INDEX TABLESPACE PBANDI_IDX
);
--FK
ALTER TABLE PBANDI_T_IMPORTO_FONTI_QTES   ADD CONSTRAINT fk_pbandi_t_utente_428 
    FOREIGN KEY (ID_UTENTE_INS) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
ALTER TABLE PBANDI_T_IMPORTO_FONTI_QTES   ADD CONSTRAINT fk_pbandi_t_utente_429 
    FOREIGN KEY (ID_UTENTE_AGG) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
/*
alter table PBANDI_T_IMPORTO_FONTI_QTES
  add constraint FK_PBANDI_T_PROGETTO_99 foreign key (ID_PROGETTO)
  references PBANDI_T_PROGETTO (ID_PROGETTO);
*/

ALTER TABLE PBANDI_T_IMPORTO_FONTI_QTES   ADD CONSTRAINT fk_PBANDI_T_DATI_PROG_QTES_02
    FOREIGN KEY (ID_DATI_QTES) REFERENCES pbandi_t_dati_progetto_qtes (ID_DATI_QTES);
ALTER TABLE PBANDI_T_IMPORTO_FONTI_QTES   ADD CONSTRAINT fk_pbandi_d_sogg_finanziat_04
    FOREIGN KEY (ID_SOGGETTO_FINANZIATORE) REFERENCES PBANDI_D_SOGGETTO_FINANZIATORE (ID_SOGGETTO_FINANZIATORE);    

--IDX
 CREATE INDEX IDX_PBANDI_T_IMP_FONTI_QTES_01 ON PBANDI_T_IMPORTO_FONTI_QTES (ID_UTENTE_INS)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_T_IMP_FONTI_QTES_02 ON PBANDI_T_IMPORTO_FONTI_QTES (ID_UTENTE_AGG)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_T_IMP_FONTI_QTES_03 ON PBANDI_T_IMPORTO_FONTI_QTES (ID_SOGGETTO_FINANZIATORE)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_T_IMP_FONTI_QTES_04 ON PBANDI_T_IMPORTO_FONTI_QTES (ID_DATI_QTES)  TABLESPACE PBANDI_IDX;
 -- CREATE INDEX IDX_PBANDI_T_IMP_FONTI_QTES_05 ON PBANDI_T_IMPORTO_FONTI_QTES (ID_PROGETTO)  TABLESPACE PBANDI_IDX;
 
 -- PBANDI_D_TIPO_INTERVENTO_QTES
CREATE TABLE PBANDI_D_TIPO_INTERV_QTES
(
ID_TIPO_INTERVENTO NUMBER(3) NOT NULL, 
DESC_BREVE_INTERVENTO VARCHAR2(50) NOT NULL, 
DESC_TIPO_INTERVENTO VARCHAR2(255) NOT NULL, 
DT_INIZIO_VALIDITA DATE NOT NULL, 
DT_FINE_VALIDITA DATE,
CONSTRAINT PK_PBANDI_D_TIPO_INTERV_QTES PRIMARY KEY (ID_TIPO_INTERVENTO) USING INDEX TABLESPACE PBANDI_IDX
);

-- PBANDI_T_TIPO_INTERV_QTES 
CREATE TABLE PBANDI_T_TIPO_INTERV_QTES
(
ID_TIPO_INTERVENTO  NUMBER(3) NOT NULL,
ID_DATI_QTES NUMBER(8) NOT NULL,
FLAG_SN varchar(1),
DT_INSERIMENTO DATE NOT NULL,
DT_MODIFICA DATE,
ID_UTENTE_INS NUMBER(8) NOT NULL,
ID_UTENTE_AGG NUMBER(8),
CONSTRAINT PK_PBANDI_T_TIPO_INT_QTES PRIMARY KEY (ID_TIPO_INTERVENTO, ID_DATI_QTES) USING INDEX TABLESPACE PBANDI_IDX
);

-- CHK
ALTER TABLE PBANDI_T_TIPO_INTERV_QTES add constraint CHK_FLAG_SN
  check (FLAG_SN IN ('S','N',NULL));
  
-- FK
ALTER TABLE PBANDI_T_TIPO_INTERV_QTES   ADD CONSTRAINT fk_PBANDI_D_TIPO_INTERVENTO_01
    FOREIGN KEY (ID_TIPO_INTERVENTO) REFERENCES Pbandi_d_Tipo_Interv_Qtes (ID_TIPO_INTERVENTO);  
ALTER TABLE PBANDI_T_TIPO_INTERV_QTES   ADD CONSTRAINT fk_pbandi_t_utente_440 
    FOREIGN KEY (ID_UTENTE_INS) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
ALTER TABLE PBANDI_T_TIPO_INTERV_QTES   ADD CONSTRAINT fk_pbandi_t_utente_441 
    FOREIGN KEY (ID_UTENTE_AGG) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
ALTER TABLE PBANDI_T_TIPO_INTERV_QTES   ADD CONSTRAINT fk_PBANDI_T_DATI_PROG_QTES_01 
    FOREIGN KEY (ID_DATI_QTES) REFERENCES PBANDI_T_DATI_PROGETTO_QTES (ID_DATI_QTES);

-- IDX
 CREATE INDEX IDX_PBANDI_T_TIPO_INTERV_01 ON PBANDI_T_TIPO_INTERV_QTES (ID_UTENTE_INS)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_T_TIPO_INTERV_02 ON PBANDI_T_TIPO_INTERV_QTES (ID_UTENTE_AGG)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_T_TIPO_INTERV_03 ON PBANDI_T_TIPO_INTERV_QTES (ID_TIPO_INTERVENTO)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_T_TIPO_INTERV_04 ON PBANDI_T_TIPO_INTERV_QTES (ID_DATI_QTES)  TABLESPACE PBANDI_IDX;
 

-- PBANDI_R_BANDO_LINEA_TIPO_INTERV
CREATE TABLE PBANDI_R_BANDO_LI_TIPO_IN_QTES
(
PROGR_BANDO_LINEA_INTERVENTO NUMBER(8) NOT NULL,
ID_TIPO_INTERVENTO   NUMBER(3) NOT NULL,
DT_INIZIO_VALIDITA DATE NOT NULL, 
DT_FINE_VALIDITA DATE,
ID_UTENTE_INS NUMBER(8) NOT NULL,
ID_UTENTE_AGG NUMBER(8),
CONSTRAINT PK_PBANDI_R_BAN_LI_TI_INT_QTES PRIMARY KEY (PROGR_BANDO_LINEA_INTERVENTO,ID_TIPO_INTERVENTO) USING INDEX TABLESPACE PBANDI_IDX
);

-- FK
ALTER TABLE PBANDI_R_BANDO_LI_TIPO_IN_QTES ADD CONSTRAINT fk_PBANDI_D_TIPO_INTERVENTO_02
    FOREIGN KEY (ID_TIPO_INTERVENTO) REFERENCES PBANDI_D_TIPO_INTERV_QTES (ID_TIPO_INTERVENTO);
ALTER TABLE PBANDI_R_BANDO_LI_TIPO_IN_QTES ADD CONSTRAINT fk_pbandi_r_bando_linea_int_38
    FOREIGN KEY (PROGR_BANDO_LINEA_INTERVENTO) REFERENCES PBANDI_R_BANDO_LINEA_INTERVENT (PROGR_BANDO_LINEA_INTERVENTO);     
ALTER TABLE PBANDI_R_BANDO_LI_TIPO_IN_QTES ADD CONSTRAINT fk_pbandi_t_utente_442
    FOREIGN KEY (ID_UTENTE_INS) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
ALTER TABLE PBANDI_R_BANDO_LI_TIPO_IN_QTES ADD CONSTRAINT fk_pbandi_t_utente_443 
    FOREIGN KEY (ID_UTENTE_AGG) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);

-- IDX
 CREATE INDEX IDX_PBANDI_R_BAN_LI_TI_IN_Q_01 ON PBANDI_R_BANDO_LI_TIPO_IN_QTES (ID_UTENTE_INS)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_R_BAN_LI_TI_IN_Q_02 ON PBANDI_R_BANDO_LI_TIPO_IN_QTES (ID_UTENTE_AGG)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_R_BAN_LI_TI_IN_Q_03 ON PBANDI_R_BANDO_LI_TIPO_IN_QTES (ID_TIPO_INTERVENTO)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_R_BAN_LI_TI_IN_Q_04 ON PBANDI_R_BANDO_LI_TIPO_IN_QTES (PROGR_BANDO_LINEA_INTERVENTO)  TABLESPACE PBANDI_IDX;
 
 
 -- PBANDI_D_ALTRI_VALORI_QTES
CREATE TABLE PBANDI_D_ALTRI_VALORI_QTES
(
ID_TIPO_VALORE NUMBER(3) NOT NULL, 
DESC_BREVE_TIPO_VALORE VARCHAR2(20) NOT NULL, 
DESC_TIPO_VALORE  VARCHAR2(255) NOT NULL, 
DT_INIZIO_VALIDITA DATE NOT NULL, 
DT_FINE_VALIDITA DATE,
CONSTRAINT PK_PBANDI_D_ALTRI_VALORI_QTES PRIMARY KEY (ID_TIPO_VALORE) USING INDEX TABLESPACE PBANDI_IDX
);

-- PBANDI_T_ALTRI_VALORI_QTES 
CREATE TABLE PBANDI_T_ALTRI_VALORI_QTES 
(
ID_DATI_QTES NUMBER(8) NOT NULL,
ID_TIPO_VALORE  NUMBER(3) NOT NULL,
VALORE NUMBER(13,2),
DT_INSERIMENTO DATE NOT NULL,
DT_MODIFICA DATE,
ID_UTENTE_INS NUMBER(8) NOT NULL,
ID_UTENTE_AGG NUMBER(8),
CONSTRAINT PK_PBANDI_T_ALTRI_VAL_QTES  PRIMARY KEY (ID_TIPO_VALORE, ID_DATI_QTES) USING INDEX TABLESPACE PBANDI_IDX 
);

-- fk

 ALTER TABLE PBANDI_T_ALTRI_VALORI_QTES     ADD CONSTRAINT fk_pbandi_t_utente_444 
    FOREIGN KEY (ID_UTENTE_INS) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
 ALTER TABLE PBANDI_T_ALTRI_VALORI_QTES    ADD CONSTRAINT fk_pbandi_t_utente_445
    FOREIGN KEY (ID_UTENTE_AGG) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
 ALTER TABLE PBANDI_T_ALTRI_VALORI_QTES    ADD CONSTRAINT fk_PBANDI_D_ALTRI_VAL_QTES_01
    FOREIGN KEY (ID_TIPO_VALORE) REFERENCES PBANDI_D_ALTRI_VALORI_QTES (ID_TIPO_VALORE);
 ALTER TABLE PBANDI_T_ALTRI_VALORI_QTES   ADD CONSTRAINT fk_PBANDI_T_DATI_PROG_QTES_03 
    FOREIGN KEY (ID_DATI_QTES) REFERENCES PBANDI_T_DATI_PROGETTO_QTES (ID_DATI_QTES);
    
-- idx
 CREATE INDEX IDX_PBANDI_T_ALTRI_VAL_QTES_01 ON PBANDI_T_ALTRI_VALORI_QTES  (ID_UTENTE_INS)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_T_ALTRI_VAL_QTES_02 ON PBANDI_T_ALTRI_VALORI_QTES  (ID_UTENTE_AGG)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_T_ALTRI_VAL_QTES_03 ON PBANDI_T_ALTRI_VALORI_QTES  (ID_TIPO_VALORE)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_T_ALTRI_VAL_QTES_04 ON PBANDI_T_ALTRI_VALORI_QTES  (ID_DATI_QTES)  TABLESPACE PBANDI_IDX;
 
 -- PBANDI_R_BANDOLINEA_ALTRV_QTES
CREATE TABLE PBANDI_R_BANDOLINEA_ALTRV_QTES
(
PROGR_BANDO_LINEA_INTERVENTO NUMBER(8) NOT NULL,
ID_TIPO_VALORE NUMBER(3) NOT NULL,
DT_INIZIO_VALIDITA DATE NOT NULL, 
DT_FINE_VALIDITA DATE,
ID_UTENTE_INS NUMBER(8) NOT NULL,
ID_UTENTE_AGG NUMBER(8),
CONSTRAINT PK_PBANDI_R_BAN_ALTRV_QTES PRIMARY KEY (PROGR_BANDO_LINEA_INTERVENTO,ID_TIPO_VALORE) USING INDEX TABLESPACE PBANDI_IDX
);

-- FK
ALTER TABLE PBANDI_R_BANDOLINEA_ALTRV_QTES ADD CONSTRAINT fk_PBANDI_D_ALTRI_VAL_QTES_02
    FOREIGN KEY (ID_TIPO_VALORE) REFERENCES PBANDI_D_ALTRI_VALORI_QTES  (ID_TIPO_VALORE);
ALTER TABLE PBANDI_R_BANDOLINEA_ALTRV_QTES ADD CONSTRAINT fk_pbandi_r_bando_linea_int_37
    FOREIGN KEY (PROGR_BANDO_LINEA_INTERVENTO) REFERENCES PBANDI_R_BANDO_LINEA_INTERVENT (PROGR_BANDO_LINEA_INTERVENTO);     
ALTER TABLE PBANDI_R_BANDOLINEA_ALTRV_QTES ADD CONSTRAINT fk_pbandi_t_utente_436
    FOREIGN KEY (ID_UTENTE_INS) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
ALTER TABLE PBANDI_R_BANDOLINEA_ALTRV_QTES ADD CONSTRAINT fk_pbandi_t_utente_437 
    FOREIGN KEY (ID_UTENTE_AGG) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);

-- IDX
 CREATE INDEX IDX_PBANDI_R_BAN_AV_QTES_01 ON PBANDI_R_BANDOLINEA_ALTRV_QTES (ID_UTENTE_INS)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_R_BAN_AV_QTES_02 ON PBANDI_R_BANDOLINEA_ALTRV_QTES (ID_UTENTE_AGG)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_R_BAN_AV_QTES_03 ON PBANDI_R_BANDOLINEA_ALTRV_QTES (ID_TIPO_VALORE)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_R_BAN_AV_QTES_04 ON PBANDI_R_BANDOLINEA_ALTRV_QTES (PROGR_BANDO_LINEA_INTERVENTO)  TABLESPACE PBANDI_IDX;
 

-- PBANDI_T_SPESA_PREVENTIVATA
--
CREATE TABLE PBANDI_T_SPESA_PREVENTIVATA
(id_spesa_preventivata   NUMBER(8) NOT NULL,
 id_rigo_conto_economico NUMBER(8) NOT NULL,
 importo_spesa_preventivata NUMBER (17,2)NOT NULL,
 DT_INSERIMENTO DATE NOT NULL,
 DT_MODIFICA DATE,
 ID_UTENTE_INS NUMBER(8) NOT NULL,
 ID_UTENTE_AGG NUMBER(8),
 CONSTRAINT PK_PBANDI_T_SPESA_PREVENTIVATA PRIMARY KEY (id_spesa_preventivata) USING INDEX TABLESPACE PBANDI_IDX 
);

-- FK
ALTER TABLE PBANDI_T_SPESA_PREVENTIVATA ADD CONSTRAINT fk_pbandi_t_rigo_conto_econ_02
    FOREIGN KEY (id_rigo_conto_economico) REFERENCES PBANDI_T_RIGO_CONTO_ECONOMICO (id_rigo_conto_economico);
ALTER TABLE PBANDI_T_SPESA_PREVENTIVATA ADD CONSTRAINT fk_pbandi_t_utente_438
    FOREIGN KEY (ID_UTENTE_INS) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
ALTER TABLE PBANDI_T_SPESA_PREVENTIVATA ADD CONSTRAINT fk_pbandi_t_utente_439 
    FOREIGN KEY (ID_UTENTE_AGG) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);

-- IDX
 CREATE INDEX IDX_PBANDI_T_SPESA_PREV_01 ON PBANDI_T_SPESA_PREVENTIVATA (ID_UTENTE_INS)  TABLESPACE PBANDI_IDX;
 CREATE INDEX IDX_PBANDI_T_SPESA_PREV_02 ON PBANDI_T_SPESA_PREVENTIVATA (ID_UTENTE_AGG)  TABLESPACE PBANDI_IDX;
-- AK
 alter table PBANDI_T_SPESA_PREVENTIVATA
  add constraint AK1_PBANDI_T_SPESA_PREV unique (id_rigo_conto_economico) using index 
  tablespace PBANDI_IDX;

-- seq
 CREATE SEQUENCE SEQ_PBANDI_T_SPESA_PREVENTIV
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
-- drop   seq
drop sequence seq_pbandi_d_fasi_qtes;
drop sequence seq_pbandi_r_mod_qtes_li_int;

-- PBANDI_T_DICH_MENS_WS
ALTER TABLE PBANDI.PBANDI_T_DICH_MENS_WS DROP CONSTRAINT CC_PBANDI_T_DICH_MENS_WS_ESITO;

ALTER TABLE PBANDI.PBANDI_T_DICH_MENS_WS ADD (
  CONSTRAINT CC_PBANDI_T_DICH_MENS_WS_ESITO
 CHECK (esito in ('OK','KO','NV')));
 
 
-- PBANDI_R_BANDO_LINEA_FASIMONIT
ALTER TABLE PBANDI_R_BANDO_LINEA_FASIMONIT ADD FLAG_PREV_ABILITATA VARCHAR2(1);
ALTER TABLE PBANDI_R_BANDO_LINEA_FASIMONIT
  add constraint CHK_FLAG_PREV_ABILITATA
  check (FLAG_PREV_ABILITATA IN ('S', 'N', NULL));  
  

-- PBANDI_D_TIPO_INTERV_QTES
-- AK
 alter table PBANDI_D_TIPO_INTERV_QTES
  add constraint AK1_PBANDI_D_TIPO_INTERV_QTES unique (desc_breve_intervento) using index 
  tablespace PBANDI_IDX;

-- PBANDI_D_ALTRI_VALORI_QTES
-- AK
 alter table PBANDI_D_ALTRI_VALORI_QTES
  add constraint AK1_PBANDI_D_ALTRI_VALORI_QTES unique (desc_breve_tipo_valore) using index 
  tablespace PBANDI_IDX;
  
DROP TYPE PBANDI.LISTNOTIFPROG;

DROP TYPE PBANDI.OBJNOTIFPROG;

CREATE OR REPLACE TYPE PBANDI."OBJNOTIFPROG"    AS OBJECT
(ID_PROGETTO NUMBER(8),
 TITOLO_PROGETTO  VARCHAR2(2000),
 CODICE_VISUALIZZATO  VARCHAR2(100),
 ID_NOTIFICA INTEGER,
 STATO_NOTIFICA  VARCHAR2(1),
 DT_NOTIFICA  DATE,
 SUBJECT_NOTIFICA VARCHAR2(4000),
 MESSAGE_NOTIFICA CLOB
 )
/


CREATE OR REPLACE TYPE PBANDI."LISTNOTIFPROG"   AS TABLE OF OBJNOTIFPROG
/


-- PBANDI_T_DICH_MENS_WS
Alter table PBANDI_T_DICH_MENS_WS ADD FLAG_INVIO_EMAIL VARCHAR2(1); 

alter table PBANDI_T_DICH_MENS_WS
  add constraint CHK_PBANDI_T_DICH_ME_WS_EMAIL 
  check (FLAG_INVIO_EMAIL IN ('S', NULL));
  
Alter table PBANDI_T_DICH_MENS_WS ADD  FLAG_INVIO_EROG VARCHAR2(1); 

alter table PBANDI_T_DICH_MENS_WS
  add constraint CHK_PBANDI_T_DICH_ME_WS_EROG
  check (FLAG_INVIO_EROG IN ('S', NULL));

Alter table PBANDI_T_DICH_MENS_WS ADD NOTE CLOB; 

-- 
-- PBANDI_T_CONSUNTIVO_ENTRATA

CREATE TABLE PBANDI_T_CONSUNTIVO_ENTRATA
(id_consuntivo_entrata NUMBER(8) not null,
 importo_entrata NUMBER(17,2),
 id_voce_di_entrata NUMBER(8),
 completamento varchar2(1000),
 id_rigo_conto_economico NUMBER(8),
 id_utente_ins NUMBER(8) not null,
 id_utente_agg NUMBER(8),
 dt_inizio_validita date not null,
 dt_fine_validita date,
 dt_modifica date,
 CONSTRAINT PK_PBANDI_T_CONSUNTIVO_ENTRATA PRIMARY KEY (id_consuntivo_entrata) USING INDEX TABLESPACE PBANDI_IDX  
);

-- fk
ALTER TABLE PBANDI_T_CONSUNTIVO_ENTRATA ADD CONSTRAINT fk_pbandi_t_rigo_conto_econ_03
    FOREIGN KEY (id_rigo_conto_economico) REFERENCES PBANDI_T_RIGO_CONTO_ECONOMICO (id_rigo_conto_economico);
ALTER TABLE PBANDI_T_CONSUNTIVO_ENTRATA ADD CONSTRAINT fk_pbandi_d_voce_di_entrata_03
    FOREIGN KEY (ID_VOCE_DI_ENTRATA) REFERENCES pbandi_d_voce_di_entrata (ID_VOCE_DI_ENTRATA);
ALTER TABLE PBANDI_T_CONSUNTIVO_ENTRATA ADD CONSTRAINT fk_pbandi_t_utente_446
    FOREIGN KEY (ID_UTENTE_INS) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
ALTER TABLE PBANDI_T_CONSUNTIVO_ENTRATA ADD CONSTRAINT fk_pbandi_t_utente_447 
    FOREIGN KEY (ID_UTENTE_AGG) REFERENCES PBANDI_T_UTENTE (ID_UTENTE);
    
-- idx
CREATE INDEX IDX_PBANDI_T_CONS_ENTRATA_01 ON PBANDI_T_CONSUNTIVO_ENTRATA (ID_UTENTE_INS)  TABLESPACE PBANDI_IDX; 
CREATE INDEX IDX_PBANDI_T_CONS_ENTRATA_02 ON PBANDI_T_CONSUNTIVO_ENTRATA (ID_UTENTE_AGG)  TABLESPACE PBANDI_IDX; 
CREATE INDEX IDX_PBANDI_T_CONS_ENTRATA_03 ON PBANDI_T_CONSUNTIVO_ENTRATA (id_rigo_conto_economico)  TABLESPACE PBANDI_IDX; 
CREATE INDEX IDX_PBANDI_T_CONS_ENTRATA_04 ON PBANDI_T_CONSUNTIVO_ENTRATA (ID_VOCE_DI_ENTRATA)  TABLESPACE PBANDI_IDX;  

-- seq
 CREATE SEQUENCE SEQ_PBANDI_T_CONS_ENTRATA
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
-- PBANDI_R_BANDO_MODALITA_AGEVOL
ALTER TABLE PBANDI_R_BANDO_MODALITA_AGEVOL RENAME COLUMN IMPORTO_DA_EROGARE TO PERCENTUALE_IMPORTO_DA_EROGARE;
ALTER TABLE PBANDI_R_BANDO_MODALITA_AGEVOL MODIFY(PERCENTUALE_IMPORTO_DA_EROGARE NUMBER(5,2));

--PBANDI_C_PARAMETRI_MONIT
CREATE SEQUENCE SEQ_PBANDI_C_PARAMETRI_MONIT
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
	NOCACHE
    nocycle
    noorder;

/ ---------------------------------------------------------------------- /
/ Add table "PBANDI_C_PARAMETRI_MONIT"                                   /
/ ---------------------------------------------------------------------- /

CREATE TABLE PBANDI_C_PARAMETRI_MONIT (
    ID_PARAMETRO_MONIT NUMBER(3) NOT NULL,
    DESC_BREVE_PARAMETRO_MONIT VARCHAR2(20) NOT NULL,
    DESC_PARAMETRO_MONIT VARCHAR2(200) NOT NULL,
	ID_TEMPLATE_NOTIFICA INTEGER NOT NULL,
    CONSTRAINT PK_PBANDI_C_PARAMETRI_MONIT PRIMARY KEY (ID_PARAMETRO_MONIT) USING INDEX TABLESPACE PBANDI_IDX
);

CREATE INDEX IE_PBANDI_C_PARAMETRI_MONIT_1 ON PBANDI_C_PARAMETRI_MONIT (ID_TEMPLATE_NOTIFICA)  TABLESPACE PBANDI_IDX;

