/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

insert into PBANDI_C_ENTITA
(ID_ENTITA, NOME_ENTITA, FLAG_DA_TRACCIARE, FLAG_INDEX) 
(select seq_PBANDI_C_ENTITA.nextval,tabs.TABLE_NAME,'S','N' 
from all_tables tabs
where tabs.OWNER = (select decode(instr(user,'_RW'),0,user,replace(user,'_RW',null)) from dual)
and tabs.TABLE_NAME like 'PBANDI_%'
and not exists (select 'x' from pbandi_c_entita where tabs.TABLE_NAME = NOME_ENTITA));

commit;

declare
  cursor curAttr is select col.COLUMN_NAME,en.id_ENTITA,col.TABLE_NAME
                    from all_tab_cols col,PBANDI_C_ENTITA en
                    where col.owner = (select decode(instr(user,'_RW'),0,user,replace(user,'_RW',null)) from dual)
                    and col.TABLE_NAME like 'PBANDI_%'
                    and col.COLUMN_NAME not like 'SYS_%'
                    and col.TABLE_NAME = en.NOME_ENTITA
                    and not exists (select 'x' from PBANDI_C_ATTRIBUTO att 
                                    where col.COLUMN_NAME = att.NOME_ATTRIBUTO
                                    and att.id_entita = en.id_ENTITA);
                                    
  nPosiz  PLS_INTEGER := NULL;                                                                          
begin
  for recAttr in curAttr loop

    BEGIN
      SELECT POSITION
      INTO   nPosiz 
      FROM   all_CONSTRAINTS A,all_CONS_COLUMNS B
      WHERE  A.CONSTRAINT_TYPE = 'P'
      AND    A.TABLE_NAME      = recAttr.TABLE_NAME
      AND    A.CONSTRAINT_NAME = B.CONSTRAINT_NAME
      AND    COLUMN_NAME       = recAttr.COLUMN_NAME;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        nPosiz := NULL;
    END;
    
    insert into PBANDI_C_ATTRIBUTO
    (ID_ATTRIBUTO, 
     NOME_ATTRIBUTO, 
     FLAG_DA_TRACCIARE, 
     ID_ENTITA,
     KEY_POSITION_ID) 
    values
    (SEQ_PBANDI_C_ATTRIBUTO.NEXTVAL,
     recAttr.COLUMN_NAME,
     'N',
     recAttr.id_ENTITA,
     nPosiz);
  end loop;
  COMMIT;
end;
/

  update PBANDI_D_STATO_DOCUMENTO_SPESA set desc_stato_documento_spesa = 'DICHIARABILE' where desc_breve_stato_doc_spesa = 'I';
  update PBANDI_D_STATO_DOCUMENTO_SPESA set desc_stato_documento_spesa = 'IN VALIDAZIONE' where desc_breve_stato_doc_spesa = 'D';
  update PBANDI_D_STATO_DOCUMENTO_SPESA set dt_fine_validita = dt_inizio_validita where desc_breve_stato_doc_spesa = 'S';

  update PBANDI_D_STATO_VALIDAZ_SPESA SVS set SVS.DESC_STATO_VALIDAZIONE_SPESA = 'DICHIARATO' 
     where SVS.DESC_BREVE_STATO_VALIDAZ_SPESA = 'R';
     
  update PBANDI_D_STATO_VALIDAZ_SPESA SVS set SVS.DESC_STATO_VALIDAZIONE_SPESA = 'PARZIALMENTE VALIDATO' 
     where SVS.DESC_BREVE_STATO_VALIDAZ_SPESA = 'P';

  update PBANDI_D_STATO_VALIDAZ_SPESA SVS set SVS.DESC_STATO_VALIDAZIONE_SPESA = upper(SVS.DESC_STATO_VALIDAZIONE_SPESA);


insert into PBANDI_D_MODALITA_PAGAMENTO (ID_MODALITA_PAGAMENTO, DESC_BREVE_MODALITA_PAGAMENTO, DESC_MODALITA_PAGAMENTO, DT_INIZIO_VALIDITA, DT_FINE_VALIDITA)
values (5, 'AUT', 'Varie', to_date('01-01-2000', 'dd-mm-yyyy'), null /*to_date('01-01-2000', 'dd-mm-yyyy')*/);

insert into PBANDI_D_MODALITA_PAGAMENTO (ID_MODALITA_PAGAMENTO, DESC_BREVE_MODALITA_PAGAMENTO, DESC_MODALITA_PAGAMENTO, DT_INIZIO_VALIDITA, DT_FINE_VALIDITA)
values (6, 'PER', 'Versamento costi personale', to_date('01-01-2000', 'dd-mm-yyyy'), null);

insert into PBANDI_D_STATO_VALIDAZ_SPESA (ID_STATO_VALIDAZIONE_SPESA, DESC_BREVE_STATO_VALIDAZ_SPESA, DESC_STATO_VALIDAZIONE_SPESA, DT_INIZIO_VALIDITA, DT_FINE_VALIDITA)
values (7, 'G', 'Da respingere', to_date('01-01-2009', 'dd-mm-yyyy'), null);
insert into PBANDI_D_STATO_VALIDAZ_SPESA (ID_STATO_VALIDAZIONE_SPESA, DESC_BREVE_STATO_VALIDAZ_SPESA, DESC_STATO_VALIDAZIONE_SPESA, DT_INIZIO_VALIDITA, DT_FINE_VALIDITA)
values (8, 'T', 'Respinto', to_date('01-01-2009', 'dd-mm-yyyy'), null);

INSERT INTO PBANDI_C_ENTITA ( ID_ENTITA, NOME_ENTITA, FLAG_DA_TRACCIARE,FLAG_INDEX ) 
VALUES (seq_PBANDI_C_ENTITA.nextval, 'CHECK LIST VALIDAZIONE', 'S', 'S'); 

commit;

insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(70,'FluxImpl.dichiarazioniDaValidare','FluxImpl.dichiarazioniDaValidare','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(71,'FluxImpl.isDichiarazioniDaValidare','FluxImpl.isDichiarazioniDaValidare','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(72,'GestioneDatiDiDominioImpl.findDecodificheConEsclusioni','GestioneDatiDiDominioImpl.findDecodificheConEsclusioni','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(73,'GestioneDatiDiDominioImpl.findDecodificaPerDescrizioneBreve','GestioneDatiDiDominioImpl.findDecodificaPerDescrizioneBreve','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(74,'GestioneDatiGeneraliImpl.caricaDatiGeneraliPerValidazione','GestioneDatiGeneraliImpl.caricaDatiGeneraliPerValidazione','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(75,'GestioneFornitoriImpl.findDettaglioFornitoreOriginario','GestioneFornitoriImpl.findDettaglioFornitoreOriginario','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(76,'GestionePagamentiImpl.findPagamentiAssociatiPerValidazione','GestionePagamentiImpl.findPagamentiAssociatiPerValidazione','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(77,'GestionePagamentiImpl.findPagamentoPerValidazione','GestionePagamentiImpl.findPagamentoPerValidazione','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(78,'GestionePagamentiImpl.modificaPagamentoPerValidazione','GestionePagamentiImpl.modificaPagamentoPerValidazione','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(79,'GestionePagamentiImpl.findTipologieDiPagamentoPerSpesaForfettaria','GestionePagamentiImpl.findTipologieDiPagamentoPerSpesaForfettaria','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(80,'GestionePagamentiImpl.ripartisciPagamentoOnVociDiSpesaPerValidazione','GestionePagamentiImpl.ripartisciPagamentoOnVociDiSpesaPerValidazione','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(81,'ProfilazioneImpl.findBeneficiari','ProfilazioneImpl.findBeneficiari','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(82,'ProfilazioneImpl.findBeneficiariProgetto','ProfilazioneImpl.findBeneficiariProgetto','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(83,'WorkspaceBackofficeImpl.caricaGruppiProcessiPerMigrazione','WorkspaceBackofficeImpl.caricaGruppiProcessiPerMigrazione','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(84,'WorkspaceBackofficeImpl.migraGruppoIstanzeProcesso','WorkspaceBackofficeImpl.migraGruppoIstanzeProcesso','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(85,'WorkspaceBackofficeImpl.migraIstanzaProcesso','WorkspaceBackofficeImpl.migraIstanzaProcesso','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(86,'ValidazioneRendicontazioneImpl.findDocumentiDiSpesa','ValidazioneRendicontazioneImpl.findDocumentiDiSpesa','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(87,'ValidazioneRendicontazioneImpl.findDettaglioDocumentoDiSpesa','ValidazioneRendicontazioneImpl.findDettaglioDocumentoDiSpesa','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(88,'ValidazioneRendicontazioneImpl.modificaDocumentoDiSpesa','ValidazioneRendicontazioneImpl.modificaDocumentoDiSpesa','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(89,'ValidazioneRendicontazioneImpl.aggiornaPagamentiEVociDiSpesa','ValidazioneRendicontazioneImpl.aggiornaPagamentiEVociDiSpesa','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(90,'ValidazioneRendicontazioneImpl.findPagamentiEVociDiSpesa','ValidazioneRendicontazioneImpl.findPagamentiEVociDiSpesa','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(91,'ValidazioneRendicontazioneImpl.findNoteDiCredito','ValidazioneRendicontazioneImpl.findNoteDiCredito','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(92,'ValidazioneRendicontazioneImpl.checkStatoPagamenti','ValidazioneRendicontazioneImpl.checkStatoPagamenti','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(93,'ValidazioneRendicontazioneImpl.chiudiValidazione','ValidazioneRendicontazioneImpl.chiudiValidazione','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(94,'GestioneBackofficeImpl.findBeneficiari','GestioneBackofficeImpl.findBeneficiari','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(95,'GestioneBackofficeImpl.findBandi','GestioneBackofficeImpl.findBandi','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(96,'GestioneBackofficeImpl.findDettaglioIstruttore','GestioneBackofficeImpl.findDettaglioIstruttore','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(97,'GestioneBackofficeImpl.findIstruttoriSemplici','GestioneBackofficeImpl.findIstruttoriSemplici','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(98,'GestioneBackofficeImpl.findProgettiAssociatiAIstruttore','GestioneBackofficeImpl.findProgettiAssociatiAIstruttore','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(99,'GestioneBackofficeImpl.findDettaglioProgettiAssociatiAIstruttore','GestioneBackofficeImpl.findDettaglioProgettiAssociatiAIstruttore','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(100,'GestioneBackofficeImpl.findProgettiByBando','GestioneBackofficeImpl.findProgettiByBando','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(101,'GestioneBackofficeImpl.findProgettiDaAssociare','GestioneBackofficeImpl.findProgettiDaAssociare','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(102,'GestioneBackofficeImpl.findProgettiBeneficiarioBando','GestioneBackofficeImpl.findProgettiBeneficiarioBando','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(103,'GestioneBackofficeImpl.associaProgettiAIstruttore','GestioneBackofficeImpl.associaProgettiAIstruttore','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(104,'GestioneBackofficeImpl.disassociaProgettiAIstruttore','GestioneBackofficeImpl.disassociaProgettiAIstruttore','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(105,'GestioneBackofficeImpl.findIstruttoriSempliciAssociatiProgetto','GestioneBackofficeImpl.findIstruttoriSempliciAssociatiProgetto','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(106,'EsecuzioneAttivitaImpl.chiudiAttivita','EsecuzioneAttivitaImpl.chiudiAttivita','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(107,'IndexDAO.creaContentDichiarazioneDiSpesa','IndexDAO.creaContentDichiarazioneDiSpesa','S',to_date('04/08/2009','dd/MM/yyyy'));
insert into PBANDI_C_OPERAZIONE (ID_OPERAZIONE,DESC_LOGICA,DESC_FISICA,FLAG_DA_TRACCIARE,DT_INIZIO_VALIDITA) values(108,'IndexDAO.creaContentCheckListValidazione','IndexDAO.creaContentCheckListValidazione','S',to_date('04/08/2009','dd/MM/yyyy'));

SET DEFINE OFF;
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4022, 'Beneficiario', 'LR34-04 - ASSE I MIS. RI3 LINEA A - INNOVAZIONI-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_A_-_INNOVAZIONI-1.1', 1, 1);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4019, 'Beneficiario', 'LR34-04 - ASSE I MIS. RI3 LINEA A - INNOVAZIONI-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_A_-_INNOVAZIONI-1.1', 1, 2);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4016, 'Beneficiario', 'LR34-04 - ASSE I MIS. RI3 LINEA A - INNOVAZIONI-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_A_-_INNOVAZIONI-1.1', 1, 7);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4039, 'Beneficiario', 'LR34-04 - ASSE I MIS. RI3 LINEA A - INNOVAZIONI-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_A_-_INNOVAZIONI-1.1', 4);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4023, 'Beneficiario', 'LR34-04 - ASSE I MIS. RI3 LINEA B - TUTELA AMBIENTALE-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_B_-_TUTELA_AMBIENTALE-1.1', 1, 1);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4020, 'Beneficiario', 'LR34-04 - ASSE I MIS. RI3 LINEA B - TUTELA AMBIENTALE-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_B_-_TUTELA_AMBIENTALE-1.1', 1, 2);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4017, 'Beneficiario', 'LR34-04 - ASSE I MIS. RI3 LINEA B - TUTELA AMBIENTALE-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_B_-_TUTELA_AMBIENTALE-1.1', 1, 7);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4040, 'Beneficiario', 'LR34-04 - ASSE I MIS. RI3 LINEA B - TUTELA AMBIENTALE-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_B_-_TUTELA_AMBIENTALE-1.1', 4);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4018, 'Beneficiario', 'LR34-04 - ASSE I MIS. RI3 LINEA C - TECNOLOGIE-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_C_-_TECNOLOGIE-1.1', 1, 1);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4024, 'Beneficiario', 'LR34-04 - ASSE I MIS. RI3 LINEA C - TECNOLOGIE-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_C_-_TECNOLOGIE-1.1', 1, 2);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4021, 'Beneficiario', 'LR34-04 - ASSE I MIS. RI3 LINEA C - TECNOLOGIE-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_C_-_TECNOLOGIE-1.1', 1, 7);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4041, 'Beneficiario', 'LR34-04 - ASSE I MIS. RI3 LINEA C - TECNOLOGIE-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_C_-_TECNOLOGIE-1.1', 4);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4007, 'Beneficiario', 'POR. FESR 07-13 - ASSE II MIS. 1 ENERGIA - PRODUZIONE DI ENERGIE RINNOVABILI-1.1-POR._FESR_07-13_-_ASSE_II_MIS._1_ENERGIA_-_PRODUZIONE_DI_ENERGIE_RINNOVABILI-1.1', 1, 1);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4008, 'Beneficiario', 'POR. FESR 07-13 - ASSE II MIS. 1 ENERGIA - PRODUZIONE DI ENERGIE RINNOVABILI-1.1-POR._FESR_07-13_-_ASSE_II_MIS._1_ENERGIA_-_PRODUZIONE_DI_ENERGIE_RINNOVABILI-1.1', 1, 2);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4009, 'Beneficiario', 'POR. FESR 07-13 - ASSE II MIS. 1 ENERGIA - PRODUZIONE DI ENERGIE RINNOVABILI-1.1-POR._FESR_07-13_-_ASSE_II_MIS._1_ENERGIA_-_PRODUZIONE_DI_ENERGIE_RINNOVABILI-1.1', 1, 7);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4042, 'Beneficiario', 'POR. FESR 07-13 - ASSE II MIS. 1 ENERGIA - PRODUZIONE DI ENERGIE RINNOVABILI-1.1-POR._FESR_07-13_-_ASSE_II_MIS._1_ENERGIA_-_PRODUZIONE_DI_ENERGIE_RINNOVABILI-1.1', 4);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4010, 'Beneficiario', 'POR. FESR 07-13 - ASSE II MIS. 2 ENERGIA - SOSTENIBILITA-1.1-POR._FESR_07-13_-_ASSE_II_MIS._2_ENERGIA_-_SOSTENIBILITA-1.1', 1, 1);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4011, 'Beneficiario', 'POR. FESR 07-13 - ASSE II MIS. 2 ENERGIA - SOSTENIBILITA-1.1-POR._FESR_07-13_-_ASSE_II_MIS._2_ENERGIA_-_SOSTENIBILITA-1.1', 1, 2);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4012, 'Beneficiario', 'POR. FESR 07-13 - ASSE II MIS. 2 ENERGIA - SOSTENIBILITA-1.1-POR._FESR_07-13_-_ASSE_II_MIS._2_ENERGIA_-_SOSTENIBILITA-1.1', 1, 7);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4043, 'Beneficiario', 'POR. FESR 07-13 - ASSE II MIS. 2 ENERGIA - SOSTENIBILITA-1.1-POR._FESR_07-13_-_ASSE_II_MIS._2_ENERGIA_-_SOSTENIBILITA-1.1', 4);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4013, 'Beneficiario', 'POR. FESR 07-13 - ASSE II MIS. 3 ENERGIA - DISCARICHE-1.1-POR._FESR_07-13_-_ASSE_II_MIS._3_ENERGIA_-_DISCARICHE-1.1', 1, 1);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4014, 'Beneficiario', 'POR. FESR 07-13 - ASSE II MIS. 3 ENERGIA - DISCARICHE-1.1-POR._FESR_07-13_-_ASSE_II_MIS._3_ENERGIA_-_DISCARICHE-1.1', 1, 2);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4015, 'Beneficiario', 'POR. FESR 07-13 - ASSE II MIS. 3 ENERGIA - DISCARICHE-1.1-POR._FESR_07-13_-_ASSE_II_MIS._3_ENERGIA_-_DISCARICHE-1.1', 1, 7);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4044, 'Beneficiario', 'POR. FESR 07-13 - ASSE II MIS. 3 ENERGIA - DISCARICHE-1.1-POR._FESR_07-13_-_ASSE_II_MIS._3_ENERGIA_-_DISCARICHE-1.1', 4);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4002, 'Beneficiario', 'RI7-PROGETTI SPECIALI SU TEMATICHE DI INTERESSE REGIONALE O SOVRA REGIONALE-AEREOSPAZIO-1.1-RI7-PROGETTI_SPECIALI_SU_TEMATICHE_DI_INTERESSE_REGIONALE_O_SOVRA_REGIONALE-AEREOSPAZIO-1.1', 1, 1);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4001, 'Beneficiario', 'RI7-PROGETTI SPECIALI SU TEMATICHE DI INTERESSE REGIONALE O SOVRA REGIONALE-AEREOSPAZIO-1.1-RI7-PROGETTI_SPECIALI_SU_TEMATICHE_DI_INTERESSE_REGIONALE_O_SOVRA_REGIONALE-AEREOSPAZIO-1.1', 1, 2);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA, ID_TIPO_BENEFICIARIO)
 Values
   (4003, 'Beneficiario', 'RI7-PROGETTI SPECIALI SU TEMATICHE DI INTERESSE REGIONALE O SOVRA REGIONALE-AEREOSPAZIO-1.1-RI7-PROGETTI_SPECIALI_SU_TEMATICHE_DI_INTERESSE_REGIONALE_O_SOVRA_REGIONALE-AEREOSPAZIO-1.1', 1, 7);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4045, 'Beneficiario', 'RI7-PROGETTI SPECIALI SU TEMATICHE DI INTERESSE REGIONALE O SOVRA REGIONALE-AEREOSPAZIO-1.1-RI7-PROGETTI_SPECIALI_SU_TEMATICHE_DI_INTERESSE_REGIONALE_O_SOVRA_REGIONALE-AEREOSPAZIO-1.1', 4);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4032, 'Istruttore', 'LR34-04 - ASSE I MIS. RI3 LINEA A - INNOVAZIONI-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_A_-_INNOVAZIONI-1.1', 4);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4025, 'Istruttore', 'LR34-04 - ASSE I MIS. RI3 LINEA A - INNOVAZIONI-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_A_-_INNOVAZIONI-1.1', 5);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4033, 'Istruttore', 'LR34-04 - ASSE I MIS. RI3 LINEA B - TUTELA AMBIENTALE-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_B_-_TUTELA_AMBIENTALE-1.1', 4);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4026, 'Istruttore', 'LR34-04 - ASSE I MIS. RI3 LINEA B - TUTELA AMBIENTALE-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_B_-_TUTELA_AMBIENTALE-1.1', 5);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4034, 'Istruttore', 'LR34-04 - ASSE I MIS. RI3 LINEA C - TECNOLOGIE-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_C_-_TECNOLOGIE-1.1', 4);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4027, 'Istruttore', 'LR34-04 - ASSE I MIS. RI3 LINEA C - TECNOLOGIE-1.1-LR34-04_-_ASSE_I_MIS._RI3_LINEA_C_-_TECNOLOGIE-1.1', 5);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4035, 'Istruttore', 'POR. FESR 07-13 - ASSE II MIS. 1 ENERGIA - PRODUZIONE DI ENERGIE RINNOVABILI-1.1-POR._FESR_07-13_-_ASSE_II_MIS._1_ENERGIA_-_PRODUZIONE_DI_ENERGIE_RINNOVABILI-1.1', 4);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4028, 'Istruttore', 'POR. FESR 07-13 - ASSE II MIS. 1 ENERGIA - PRODUZIONE DI ENERGIE RINNOVABILI-1.1-POR._FESR_07-13_-_ASSE_II_MIS._1_ENERGIA_-_PRODUZIONE_DI_ENERGIE_RINNOVABILI-1.1', 5);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4036, 'Istruttore', 'POR. FESR 07-13 - ASSE II MIS. 2 ENERGIA - SOSTENIBILITA-1.1-POR._FESR_07-13_-_ASSE_II_MIS._2_ENERGIA_-_SOSTENIBILITA-1.1', 4);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4029, 'Istruttore', 'POR. FESR 07-13 - ASSE II MIS. 2 ENERGIA - SOSTENIBILITA-1.1-POR._FESR_07-13_-_ASSE_II_MIS._2_ENERGIA_-_SOSTENIBILITA-1.1', 5);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4037, 'Istruttore', 'POR. FESR 07-13 - ASSE II MIS. 3 ENERGIA - DISCARICHE-1.1-POR._FESR_07-13_-_ASSE_II_MIS._3_ENERGIA_-_DISCARICHE-1.1', 4);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4030, 'Istruttore', 'POR. FESR 07-13 - ASSE II MIS. 3 ENERGIA - DISCARICHE-1.1-POR._FESR_07-13_-_ASSE_II_MIS._3_ENERGIA_-_DISCARICHE-1.1', 5);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4038, 'Istruttore', 'RI7-PROGETTI SPECIALI SU TEMATICHE DI INTERESSE REGIONALE O SOVRA REGIONALE-AEREOSPAZIO-1.1-RI7-PROGETTI_SPECIALI_SU_TEMATICHE_DI_INTERESSE_REGIONALE_O_SOVRA_REGIONALE-AEREOSPAZIO-1.1', 4);
Insert into PBANDI_C_RUOLO_PROCESSO
   (ID_RUOLO_PROCESSO, CODICE_RUOLO, DEFINIZIONE_PROCESSO, ID_TIPO_ANAGRAFICA)
 Values
   (4031, 'Istruttore', 'RI7-PROGETTI SPECIALI SU TEMATICHE DI INTERESSE REGIONALE O SOVRA REGIONALE-AEREOSPAZIO-1.1-RI7-PROGETTI_SPECIALI_SU_TEMATICHE_DI_INTERESSE_REGIONALE_O_SOVRA_REGIONALE-AEREOSPAZIO-1.1', 5);
COMMIT;
