/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

--
ALTER TABLE PBANDI_T_RECUPERO ADD FLAG_MONIT VARCHAR2(1);
--
ALTER TABLE PBANDI_T_DOCUMENTO_INDEX ADD
(NOME_DOCUMENTO VARCHAR2(255),
 NOME_DOCUMENTO_FIRMATO VARCHAR2(255),
 NOME_DOCUMENTO_MARCATO VARCHAR2(255)
);

-- Creazione OBJECT TYPE OBJIDFOLDERNEW
CREATE OR REPLACE TYPE      OBJIDFOLDERNEW   AS OBJECT
(
  ID_FOLDER  INTEGER,
  ID_FOLDER_NEW INTEGER
);
/
CREATE OR REPLACE TYPE     LISTFOLDERNEW  AS TABLE OF OBJIDFOLDERNEW;
/
--
-- PBANDI_T_TRASFERIMENTO
ALTER TABLE PBANDI_T_TRASFERIMENTO ADD ID_LINEA_DI_INTERVENTO NUMBER(3);
--FK
ALTER TABLE PBANDI_T_TRASFERIMENTO ADD
CONSTRAINT fk_pbandi_d_linea_interv_63
FOREIGN KEY (ID_LINEA_DI_INTERVENTO) 
REFERENCES PBANDI_D_LINEA_DI_INTERVENTO(ID_LINEA_DI_INTERVENTO);
-- PBANDI_D_LINEA_DI_INTERVENTO
ALTER TABLE PBANDI_D_LINEA_DI_INTERVENTO ADD FLAG_TRASFERIMENTI VARCHAR2(1);
     
--Type
DROP TYPE LISTCTRLCERTIF;

CREATE OR REPLACE TYPE OBJCTRLCERTIF AS OBJECT
(
CODICE_VISUALIZZATO VARCHAR2(100),
ID_PROGETTO NUMBER(8),
ID_PROPOSTA_CERTIFICAZ NUMBER(8),
ID_UTENTE_INS NUMBER(8),
NOME_BANDO_LINEA VARCHAR2(255),
IMPORTO_EROGAZIONI NUMBER(13,2),
ID_TIPO_OPERAZIONE NUMBER(3),
ID_DOMANDA NUMBER(8),
PROGR_BANDO_LINEA_INTERVENTO NUMBER(8),
IMPORTO_PAGAMENTI_VALIDATI NUMBER(13,2),
ID_LINEA_DI_INTERVENTO NUMBER(3),
FLAG_SIF VARCHAR2(1),
PROGR_BANDO_LINEA_INTERV_SIF NUMBER(8),
ID_PROGETTO_FINANZ NUMBER(8),
FLAG_EXTRA_POR CHAR(1)
)
/

CREATE OR REPLACE TYPE LISTCTRLCERTIF AS TABLE OF OBJCTRLCERTIF
/
