/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

ALTER TABLE PBANDI_C_MODELLO ADD (TEMPLATE_PDF   BLOB)    LOB (TEMPLATE_PDF)  STORE AS BLOB   (TABLESPACE PBANDI_LOB INDEX (TABLESPACE PBANDI_LOB));

-- PBANDI_R_BANDO_INDICATORI
ALTER TABLE PBANDI_R_BANDO_INDICATORI ADD
(INFO_INIZIALE VARCHAR2(255),
 INFO_FINALE  VARCHAR2(255)
);

--PBANDI_D_SETTORE_ENTE
ALTER TABLE PBANDI_D_SETTORE_ENTE ADD CODICE_FISCALE VARCHAR2(32);
ALTER TABLE PBANDI_D_SETTORE_ENTE MODIFY DESC_BREVE_SETTORE VARCHAR2(8);
ALTER TABLE PBANDI_D_SETTORE_ENTE MODIFY ID_SETTORE_ENTE NUMBER(5);
--
ALTER TABLE PBANDI_T_ATTO_LIQUIDAZIONE  MODIFY ID_SETTORE_ENTE NUMBER(5);
ALTER TABLE PBANDI_R_BANDO_LINEA_SETTORE  MODIFY ID_SETTORE_ENTE NUMBER(5);
--ALTER TABLE PBANDI_T_CSP_SOGGETTO  MODIFY ID_SETTORE_ENTE NUMBER(5);
--

--PBANDI_T_CSP_SOGGETTO
ALTER TABLE PBANDI_T_CSP_SOGGETTO ADD ID_SETTORE_ENTE NUMBER(5);

ALTER TABLE PBANDI_T_CSP_SOGGETTO ADD (
  CONSTRAINT FK_PBANDI_D_SETTORE_ENTE_03 
  FOREIGN KEY (ID_SETTORE_ENTE) 
  REFERENCES PBANDI_D_SETTORE_ENTE (ID_SETTORE_ENTE));
  
CREATE INDEX IE1_PBANDI_T_CSP_SOGGETTO ON PBANDI_T_CSP_SOGGETTO
(ID_SETTORE_ENTE)
TABLESPACE PBANDI_IDX;


--PBANDI_T_ENTE_COMPETENZA
ALTER TABLE PBANDI_T_ENTE_COMPETENZA  ADD CODICE_FISCALE_UO VARCHAR2(32);
ALTER TABLE PBANDI_T_ENTE_COMPETENZA  ADD PARTITA_IVA_ENTE VARCHAR2(20);

--PBANDI_D_DIPARTIMENTO 
ALTER TABLE PBANDI_D_DIPARTIMENTO ADD COD_FISCALE_DIPARTIMENTO_PBAN  VARCHAR2(32);

--

-- PBANDI_T_RECAPITI
--
/*
ALTER TABLE PBANDI_T_RECAPITI ADD
(FLAG_EMAIL_CONFERMATA VARCHAR2(1),
 FLAG_INVIO_MAIL  VARCHAR2(1)
);

ALTER TABLE PBANDI_T_RECAPITI
ADD CONSTRAINT CHK_FLAG_EMAIL_CONFERMATA CHECK (FLAG_EMAIL_CONFERMATA IN ('S','N',NULL));

ALTER TABLE PBANDI_T_RECAPITI
ADD CONSTRAINT CHK_FLAG_INVIO_MAIL CHECK (FLAG_INVIO_MAIL IN ('S','N',NULL));

*/

-- PBANDI_R_SOGG_PROGETTO_SEDE
ALTER TABLE PBANDI_R_SOGG_PROGETTO_SEDE ADD FLAG_EMAIL_CONFERMATA VARCHAR2(1);

ALTER TABLE PBANDI_R_SOGG_PROGETTO_SEDE
ADD CONSTRAINT CHK_FLAG_EMAIL_CONFERMATA CHECK (FLAG_EMAIL_CONFERMATA IN ('S','N',NULL));

--
-- PBANDI_T_SPESA_CHECKLIST
CREATE TABLE PBANDI_T_SPESA_CHECKLIST
(ID_SPESA_CHECKLIST NUMBER(3),
 ID_LINEA_DI_INTERVENTO NUMBER(3),
 ID_TIPO_OPERAZIONE NUMBER(3),
 FLAG_SIF VARCHAR2(1),
 ID_MODELLO_CL NUMBER(3),
 ID_MODELLO_CD NUMBER(3)
);

-- CHECK
ALTER TABLE PBANDI_T_SPESA_CHECKLIST
ADD CONSTRAINT CHK_FLAG_SIF CHECK (FLAG_SIF IN ('S',NULL));
 
 --PK
ALTER TABLE PBANDI_T_SPESA_CHECKLIST  ADD 
(CONSTRAINT PK_PBANDI_T_SPESA_CHECKLIST  PRIMARY KEY (ID_SPESA_CHECKLIST)
USING INDEX TABLESPACE PBANDI_IDX);

-- FK
ALTER TABLE PBANDI_T_SPESA_CHECKLIST ADD (
  CONSTRAINT fk_pbandi_d_linea_interv_64
  FOREIGN KEY (ID_LINEA_DI_INTERVENTO) 
  REFERENCES PBANDI_D_LINEA_DI_INTERVENTO (ID_LINEA_DI_INTERVENTO));

ALTER TABLE PBANDI_T_SPESA_CHECKLIST ADD (
  CONSTRAINT fk_pbandi_d_tipo_operazione_09
  FOREIGN KEY (ID_TIPO_OPERAZIONE) 
  REFERENCES PBANDI_D_TIPO_OPERAZIONE (ID_TIPO_OPERAZIONE));
  
ALTER TABLE PBANDI_T_SPESA_CHECKLIST ADD (
  CONSTRAINT fk_pbandi_c_modello_06
  FOREIGN KEY (ID_MODELLO_CL) 
  REFERENCES PBANDI_C_MODELLO (ID_MODELLO));
  
ALTER TABLE PBANDI_T_SPESA_CHECKLIST ADD (
  CONSTRAINT fk_pbandi_c_modello_07
  FOREIGN KEY (ID_MODELLO_CD) 
  REFERENCES PBANDI_C_MODELLO (ID_MODELLO));  

-- INDEX
CREATE INDEX IE1_PBANDI_T_SPESA_CHECKLIST ON PBANDI_T_SPESA_CHECKLIST (ID_LINEA_DI_INTERVENTO) TABLESPACE PBANDI_IDX;
CREATE INDEX IE2_PBANDI_T_SPESA_CHECKLIST ON PBANDI_T_SPESA_CHECKLIST (ID_TIPO_OPERAZIONE) TABLESPACE PBANDI_IDX; 
CREATE INDEX IE3_PBANDI_T_SPESA_CHECKLIST ON PBANDI_T_SPESA_CHECKLIST (ID_MODELLO_CL) TABLESPACE PBANDI_IDX;  
CREATE INDEX IE4_PBANDI_T_SPESA_CHECKLIST ON PBANDI_T_SPESA_CHECKLIST (ID_MODELLO_CD) TABLESPACE PBANDI_IDX;

-- PBANDI_R_TP_DOC_IND_BAN_LI_INT
ALTER TABLE PBANDI_R_TP_DOC_IND_BAN_LI_INT ADD FLAG_LOCK VARCHAR2(1);
-- CHECK
ALTER TABLE PBANDI_R_TP_DOC_IND_BAN_LI_INT
ADD CONSTRAINT CHK_FLAG_LOCK CHECK (FLAG_LOCK IN ('S',NULL));

-- PBANDI_T_EROGAZIONE
ALTER TABLE PBANDI_T_EROGAZIONE ADD FLAG_ABBUONO VARCHAR2(1);
-- CHECK
ALTER TABLE PBANDI_T_EROGAZIONE
ADD CONSTRAINT CHK_FLAG_ABBUONO CHECK (FLAG_ABBUONO IN ('S',NULL));
--
--PBANDI_T_UTENTE
ALTER TABLE PBANDI_T_UTENTE ADD FLAG_AMMIN VARCHAR2(1);

-- CHECK
ALTER TABLE PBANDI_T_UTENTE
ADD CONSTRAINT CHK_FLAG_AMMIN CHECK (FLAG_AMMIN IN ('S',NULL));

-- PBANDI_T_NEWS
CREATE TABLE PBANDI_T_NEWS
(
ID_NEWS NUMBER(8),
URL_PAGINA VARCHAR2(1000) NOT NULL,
TITOLO VARCHAR2(1000) NOT NULL,
DESCRIZIONE CLOB NOT NULL,
DT_INIZIO DATE NOT NULL,
DT_FINE DATE,
UTENTE_INS NUMBER(8) NOT NULL
);
-- PK
ALTER TABLE PBANDI_T_NEWS  ADD 
(CONSTRAINT PK_PBANDI_T_NEWS  PRIMARY KEY (ID_NEWS)
USING INDEX TABLESPACE PBANDI_IDX);

-- SEQ
CREATE SEQUENCE SEQ_PBANDI_T_NEWS
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

-- PBANDI_R_NEWS_TIPO_ANAGRAFICA

CREATE TABLE PBANDI_R_NEWS_TIPO_ANAGRAFICA
(
ID_NEWS NUMBER(8),
ID_TIPO_ANAGRAFICA NUMBER(3)
);
-- PK
ALTER TABLE PBANDI_R_NEWS_TIPO_ANAGRAFICA  ADD 
(CONSTRAINT PK_PBANDI_R_NEWS_TIPO_ANAG  PRIMARY KEY (ID_NEWS,ID_TIPO_ANAGRAFICA)
USING INDEX TABLESPACE PBANDI_IDX);
-- FK
ALTER TABLE PBANDI_R_NEWS_TIPO_ANAGRAFICA ADD (
  CONSTRAINT FK_PBANDI_T_NEWS_01
  FOREIGN KEY (ID_NEWS) 
  REFERENCES PBANDI_T_NEWS (ID_NEWS));
-- FK
ALTER TABLE PBANDI_R_NEWS_TIPO_ANAGRAFICA ADD (
  CONSTRAINT fk_pbandi_d_tipo_anagrafica_10
  FOREIGN KEY (ID_TIPO_ANAGRAFICA) 
  REFERENCES PBANDI_D_TIPO_ANAGRAFICA (ID_TIPO_ANAGRAFICA));
-- INDEX
CREATE INDEX IE_PBANDI_R_NEWS_TIPO_ANAG_01 ON PBANDI_R_NEWS_TIPO_ANAGRAFICA (ID_TIPO_ANAGRAFICA) TABLESPACE PBANDI_IDX;


 






