/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

--
-- PBANDI_R_ECONOM_SOGG_FINANZIAT
ALTER TABLE PBANDI_R_ECONOM_SOGG_FINANZIAT ADD TIPOLOGIA_PROGETTO VARCHAR2(1);
COMMENT ON COLUMN PBANDI_R_ECONOM_SOGG_FINANZIAT.TIPOLOGIA_PROGETTO  IS 'C = CEDENTE E R = RICEVENTE';
--ALTER TABLE PBANDI_R_ECONOM_SOGG_FINANZIAT ADD (
--  CONSTRAINT CHK_TIPOLOGIA_PROGETTO
--  CHECK (TIPOLOGIA_PROGETTO IN ('R', 'C', NULL))); --
--PK
--ALTER TABLE PBANDI_R_ECONOM_SOGG_FINANZIAT DROP CONSTRAINT PK_PBANDI_R_ECON_SOGG_FINANZ;
--DROP INDEX PK_PBANDI_R_ECON_SOGG_FINANZ;
UPDATE PBANDI_R_ECONOM_SOGG_FINANZIAT SET TIPOLOGIA_PROGETTO = 'C';
COMMIT;
ALTER TABLE PBANDI_R_ECONOM_SOGG_FINANZIAT ADD (
  CONSTRAINT CHK_TIPOLOGIA_PROGETTO
  CHECK (TIPOLOGIA_PROGETTO IN ('R', 'C', NULL))); --
--
ALTER TABLE PBANDI_R_ECONOM_SOGG_FINANZIAT DROP CONSTRAINT PK_PBANDI_R_ECON_SOGG_FINANZ;
DROP INDEX PK_PBANDI_R_ECON_SOGG_FINANZ;
ALTER TABLE  PBANDI_R_ECONOM_SOGG_FINANZIAT  ADD 
(CONSTRAINT PK_PBANDI_R_ECON_SOGG_FINANZ  PRIMARY KEY (ID_ECONOMIA, ID_SOGGETTO_FINANZIATORE,TIPOLOGIA_PROGETTO)
USING INDEX  TABLESPACE PBANDI_IDX);
--
--
-- PBANDI_C_ENTITA
INSERT INTO  PBANDI_C_ENTITA VALUES
(SEQ_PBANDI_C_ENTITA.NEXTVAL, 'PBANDI_T_INTEGRAZIONE_SPESA', 'N');
COMMIT;
--
--PBANDI_T_INTEGRAZIONE_SPESA
CREATE TABLE PBANDI_T_INTEGRAZIONE_SPESA
 (
ID_INTEGRAZIONE_SPESA  NUMBER(8),
ID_DICHIARAZIONE_SPESA NUMBER(8),
DESCRIZIONE VARCHAR2(1000),
DATA_RICHIESTA DATE,
DATA_INVIO DATE
);
--PK
ALTER TABLE PBANDI_T_INTEGRAZIONE_SPESA  ADD 
(CONSTRAINT PK_PBANDI_T_INTEGRAZIONE_SPESA  PRIMARY KEY (ID_INTEGRAZIONE_SPESA)
USING INDEX  TABLESPACE PBANDI_IDX);
--FK
ALTER TABLE PBANDI_T_INTEGRAZIONE_SPESA ADD
CONSTRAINT FK_PBANDI_T_DICHIARAZ_SPESA_07
FOREIGN KEY (ID_DICHIARAZIONE_SPESA) 
REFERENCES PBANDI_T_DICHIARAZIONE_SPESA (ID_DICHIARAZIONE_SPESA);
-- INDEX
CREATE INDEX IE1_PBANDI_T_INTEGRAZ_SPESA ON  PBANDI_T_INTEGRAZIONE_SPESA (ID_DICHIARAZIONE_SPESA) TABLESPACE PBANDI_IDX;
--
--IMPEGNI
ALTER TABLE PBANDI_W_IMPEGNI MODIFY DESCIMPEGNO VARCHAR2(500);
ALTER TABLE PBANDI_T_IMPEGNO MODIFY DESC_IMPEGNO VARCHAR2(500);
--
-- PBANDI_T_DETT_PROPOSTA_CERTIF
ALTER TABLE PBANDI_T_DETT_PROPOSTA_CERTIF ADD IMPORTO_CERT_NET_ANNI_PREC NUMBER (13,2);
--
-- PBANDI_C_PERC_SPESA_PUBBLICA
ALTER TABLE PBANDI_T_DETT_PROPOSTA_CERTIF DROP CONSTRAINT FK_PBANDI_C_PERC_SPESA_PUBB_02;
--ALTER TABLE PBANDI_C_PERC_SPESA_PUBBLICA DROP CONSTRAINT FK_PBANDI_C_PERC_SPESA_PUBB_01;
--ALTER TABLE PBANDI_C_PERC_SPESA_PUBBLICA DROP CONSTRAINT PK_PBANDI_C_PERC_SPESA_PUBBL;
DROP TABLE PBANDI_C_PERC_SPESA_PUBBLICA;

CREATE TABLE PBANDI_C_PERC_SPESA_PUBBLICA
(
  ID_LINEA_DI_INTERVENTO          NUMBER(3),
  NUM_PERC           NUMBER(3),
  NUM_NEXT_PERC      NUMBER(3),
  PERC_TEST_PAG_VAL  NUMBER(3)
);

--  PBANDI_C_PERC_SPESA_PUBBLICA
Insert into PBANDI_C_PERC_SPESA_PUBBLICA
   (ID_LINEA_DI_INTERVENTO,NUM_PERC)
 Values
   (202,100);
Insert into PBANDI_C_PERC_SPESA_PUBBLICA
   (ID_LINEA_DI_INTERVENTO,NUM_PERC, NUM_NEXT_PERC)
 Values
   (202,75, 100);
Insert into PBANDI_C_PERC_SPESA_PUBBLICA
   (ID_LINEA_DI_INTERVENTO,NUM_PERC, NUM_NEXT_PERC, PERC_TEST_PAG_VAL)
 Values
   (202,50, 75, 85);
Insert into PBANDI_C_PERC_SPESA_PUBBLICA
   (ID_LINEA_DI_INTERVENTO,NUM_PERC, NUM_NEXT_PERC, PERC_TEST_PAG_VAL)
 Values
   (202,25, 50, 85);
Insert into PBANDI_C_PERC_SPESA_PUBBLICA
   (ID_LINEA_DI_INTERVENTO,NUM_PERC, NUM_NEXT_PERC, PERC_TEST_PAG_VAL)
 Values
   (202,0, 25, 60);
COMMIT;

--PK
ALTER TABLE   PBANDI_C_PERC_SPESA_PUBBLICA ADD (
  CONSTRAINT PK_PBANDI_C_PERC_SPESA_PUBBL
  PRIMARY KEY   (ID_LINEA_DI_INTERVENTO, NUM_PERC)
  USING INDEX  TABLESPACE PBANDI_IDX);
-- FK
ALTER TABLE PBANDI_C_PERC_SPESA_PUBBLICA ADD (
  CONSTRAINT FK_PBANDI_D_LINEA_INTERV_57 
  FOREIGN KEY (ID_LINEA_DI_INTERVENTO) 
  REFERENCES  PBANDI_D_LINEA_DI_INTERVENTO (ID_LINEA_DI_INTERVENTO));

-- FK
ALTER TABLE PBANDI.PBANDI_C_PERC_SPESA_PUBBLICA ADD (
  CONSTRAINT FK_PBANDI_C_PERC_SPESA_PUBB_01 
  FOREIGN KEY (ID_LINEA_DI_INTERVENTO,NUM_NEXT_PERC) 
  REFERENCES PBANDI.PBANDI_C_PERC_SPESA_PUBBLICA (ID_LINEA_DI_INTERVENTO,NUM_PERC));
  --FK
ALTER TABLE PBANDI.PBANDI_T_DETT_PROPOSTA_CERTIF ADD (
  CONSTRAINT FK_PBANDI_C_PERC_SPESA_PUBB_02 
  FOREIGN KEY (ID_LINEA_DI_INTERVENTO, NUM_PERC_SPESA_PUBBLICA) 
  REFERENCES PBANDI.PBANDI_C_PERC_SPESA_PUBBLICA (ID_LINEA_DI_INTERVENTO, NUM_PERC)); 
  
 -- PBANDI_T_IRREGOLARITA
ALTER TABLE PBANDI_T_IRREGOLARITA ADD  IMPORTO_IRREGOLARITA NUMBER (17,2);
ALTER TABLE PBANDI_T_IRREGOLARITA ADD  QUOTA_IMP_IRREG_CERTIFICATO NUMBER (17,2);

-- PBANDI_T_NOTIFICA_PROCESSO
ALTER TABLE PBANDI_T_NOTIFICA_PROCESSO ADD
(ID_ENTITA NUMBER (3),                   
ID_TARGET NUMBER (8)                    
);
--FK
ALTER TABLE PBANDI_T_NOTIFICA_PROCESSO ADD (
CONSTRAINT FK_PBANDI_C_ENTITA_06
FOREIGN KEY (ID_ENTITA) 
REFERENCES PBANDI_C_ENTITA (ID_ENTITA));

-- PBANDI_D_TEMPLATE_NOTIFICA
ALTER TABLE PBANDI_D_TEMPLATE_NOTIFICA ADD
(ID_ENTITA NUMBER (3));
--FK
ALTER TABLE PBANDI_D_TEMPLATE_NOTIFICA ADD (
CONSTRAINT FK_PBANDI_C_ENTITA_07
FOREIGN KEY (ID_ENTITA) 
REFERENCES PBANDI_C_ENTITA (ID_ENTITA));

-- SEQUENCE
CREATE SEQUENCE SEQ_PBANDI_T_INTEGRAZ_SPESA
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  


  