/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

-- PBANDI_C_XSD
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (140, 'FINPIS_VERSO_PBANDI', 'CodiceDettaglioIntervento', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
	
-- PBANDI_D_ERRORE_BATCH
Insert into PBANDI_D_ERRORE_BATCH
   (CODICE_ERRORE, DESCRIZIONE, FLAG_NOTIFICA_MAIL)
 Values
   ('E157', 'File XML non validato - Violato vincolo di validità valore', 'S');

-- PBANDI_R_BANDO_DETT_INTERVENTO
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (2, 'A1II', 43);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (2, 'A1Ia', 43);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (2, 'A1Ib', 43);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (2, 'A2', 43);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (2, 'B1', 42);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (2, 'B2I', 42);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (2, 'B2II', 42);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (2, 'B2III', 42);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (2, 'B3I', 42);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (2, 'B3II', 42);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (3, 'C41', 42);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (3, 'C42', 42);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (3, 'C43', 42);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (4, 'C3', 40);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (5, 'linea A', 9);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (6, 'linea B', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (7, 'linea C', 14);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (8, '1', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (8, '2', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (8, '3', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (8, '4', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (8, '5', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (9, '001GE1', 3);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (9, '001IN1', 3);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (9, '001MA1', 3);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (9, '001SG1', 3);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (9, '001TC1', 3);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (10, '1', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (11, '1', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (12, '001SF1', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (12, '001SF2', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (12, '002RI', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (12, '003SS', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (23, 'Linea 1', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (23, 'Linea 2', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (23, 'Linea 3', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (23, 'Linea 4', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (23, 'Linea 5', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (24, 'A', 56);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (24, 'B', 56);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (24, 'C', 56);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (24, 'D', 56);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (24, 'E', 56);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (24, 'F', 56);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (24, 'G', 56);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (27, 'Linea 1', 14);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (27, 'Linea 2', 14);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (27, 'Linea 3', 14);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (27, 'Linea 4', 14);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (28, 'C4.2', 43);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (28, 'C4.3', 43);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (29, 'A', 50);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (30, '1', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (32, 'C4.1', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (33, 'IIA1', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (33, 'IIA2', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (33, 'IIA3a', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (33, 'IIA3b', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (33, 'IIA3c', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (33, 'IIA4', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (33, 'IIB1', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (33, 'IIB2', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (33, 'IIB3', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (33, 'IIB4', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (33, 'IIB5', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (33, 'IIB6a', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (33, 'IIB6b', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (33, 'IIB7', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.1', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.1', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.10', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.11', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.12', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.13', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.14', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.15', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.16', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.17', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.18', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.19', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.2', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.20', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.21', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.22', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.23', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.24', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.3', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.4', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.5', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.6', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.8', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (41, 'C4.2.9', 6);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (44, 'TD', 11);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (47, '001SF1', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (47, '001SF2', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (47, '002RI', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (47, '003SS', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (49, '1', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (49, '2', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (49, '3', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (49, '4', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (49, '5', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (51, '1', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (51, '2', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (51, '3', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (60, 'A1II', 43);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (60, 'A1Ia', 43);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (60, 'A1Ib', 43);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (60, 'A2', 43);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (60, 'B3I', 42);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (60, 'B3II', 42);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (62, 'B', 58);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (62, 'D', 58);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (62, 'E', 58);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (62, 'F', 58);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (62, 'H', 58);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (62, 'I', 58);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (62, 'L', 58);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (62, 'M', 58);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (62, 'N', 58);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (62, 'O', 58);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (62, 'Q', 58);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (62, 'R', 58);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (62, 'S', 58);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (62, 'T', 58);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (62, 'V', 58);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (65, 'C4.2', 43);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (66, 'EC4.I', 43);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (66, 'EC4.II', 43);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (66, 'EC4.III', 43);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (66, 'EC4.IV', 43);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (68, '1', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (68, '2', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (68, '3', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (69, '1', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (69, '2', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (69, '3', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (72, 'IIA1', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (72, 'IIA2', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (72, 'IIA3c', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (72, 'IIA4', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (72, 'IIB1', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (72, 'IIB2', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (72, 'IIB3', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (72, 'IIB4', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (72, 'IIB5', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (72, 'IIB6b', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (72, 'IIB7', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (86, 'CD', 7);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (118, 'CD1', 9);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (118, 'CD2', 9);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (118, 'CD3', 9);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (118, 'CD4', 9);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (118, 'CD5', 9);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (135, 'linea A', 43);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (135, 'linea B', 42);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (141, '1', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (141, '2', 4);
Insert into PBANDI_R_BANDO_DETT_INTERVENTO
   (PROGR_BANDO_LINEA_INTERVENTO, COD_DETT_INTERVENTO, ID_TEMA_PRIORITARIO)
 Values
   (141, '3', 4);
COMMIT;


/*
*** script da eseguire ad ogni rilascio
*/
update PBANDI_C_VERSIONE
set VERSIONE_DB = '2.11.0';

insert into PBANDI_C_ENTITA
(ID_ENTITA, NOME_ENTITA, FLAG_DA_TRACCIARE) 
(select seq_PBANDI_C_ENTITA.nextval,tabs.TABLE_NAME,'S'
from all_tables tabs
where tabs.OWNER = (select decode(instr(user,'_RW'),0,user,replace(user,'_RW',null)) from dual)
and tabs.TABLE_NAME like 'PBANDI_%'
and not exists (select 'x' from pbandi_c_entita where tabs.TABLE_NAME = NOME_ENTITA));

commit;

declare
  cursor curAttr is select col.COLUMN_NAME,en.id_ENTITA,col.TABLE_NAME
                    from all_tab_cols col,PBANDI_C_ENTITA en
                    where col.owner = (select decode(instr(user,'_RW'),0,user,replace(user,'_RW',null)) from dual)
                    and col.TABLE_NAME like 'PBANDI_%'
                    and col.COLUMN_NAME not like 'SYS_%'
                    and col.TABLE_NAME = en.NOME_ENTITA
                    and not exists (select 'x' from PBANDI_C_ATTRIBUTO att 
                                    where col.COLUMN_NAME = att.NOME_ATTRIBUTO
                                    and att.id_entita = en.id_ENTITA);
                                    
  nPosiz  PLS_INTEGER := NULL;                                                                          
begin
  for recAttr in curAttr loop

    BEGIN
      SELECT POSITION
      INTO   nPosiz 
      FROM   all_CONSTRAINTS A,all_CONS_COLUMNS B
      WHERE  A.CONSTRAINT_TYPE = 'P'
      AND    A.TABLE_NAME      = recAttr.TABLE_NAME
      AND    A.CONSTRAINT_NAME = B.CONSTRAINT_NAME
      AND    COLUMN_NAME       = recAttr.COLUMN_NAME;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        nPosiz := NULL;
    END;
    
    insert into PBANDI_C_ATTRIBUTO
    (ID_ATTRIBUTO, 
     NOME_ATTRIBUTO, 
     FLAG_DA_TRACCIARE, 
     ID_ENTITA,
     KEY_POSITION_ID) 
    values
    (SEQ_PBANDI_C_ATTRIBUTO.NEXTVAL,
     recAttr.COLUMN_NAME,
     'N',
     recAttr.id_ENTITA,
     nPosiz);
  end loop;
  COMMIT;
end;
/



