/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

-- PBANDI_W_IMPEGNI
ALTER TABLE PBANDI_W_IMPEGNI MODIFY DIREZIONE  VARCHAR2(6);           
ALTER TABLE PBANDI_W_IMPEGNI MODIFY DIREZIONEDEL  VARCHAR2(6);
-- PBANDI_T_PROPOSTA_CERTIFICAZ
ALTER TABLE PBANDI_T_PROPOSTA_CERTIFICAZ ADD ID_PERIODO NUMBER(8);
--FK
ALTER TABLE PBANDI_T_PROPOSTA_CERTIFICAZ  ADD 
CONSTRAINT FK_PBANDI_T_PERIODO_05
 FOREIGN KEY (ID_PERIODO)
 REFERENCES PBANDI_T_PERIODO (ID_PERIODO);
 --INDEX
CREATE INDEX IE1_PBANDI_T_PROPOSTA_CERTIFIC ON PBANDI_T_PROPOSTA_CERTIFICAZ (ID_PERIODO)  TABLESPACE PBANDI_IDX;
--
-- 
-- PBANDI_T_DETT_PROP_CERT_ANNUAL
CREATE TABLE PBANDI_T_DETT_PROP_CERT_ANNUAL
(ID_DETT_PROP_CERT_ANNUAL NUMBER(8),
 ID_DETT_PROPOSTA_CERTIF NUMBER(8), -- SI RIFERISCE AL DETTAGLIO RELATIVO ALLA CLONAZIONE(FOTOGRAFIA) DEI PROGETTI
 ID_PROPOSTA_CERTIFICAZ NUMBER(8), -- SI RIFERISCE ALLA PROPOSTA DI CERTIFICAZIONE RELATIVA ALLA FOTOGRAFIA - NUOVO RECORD
 IMPORTO_REVOCHE NUMBER(17,2),
 IMPORTO_RECUPERI NUMBER(17,2),
 IMPORTO_SOPPRESSIONI  NUMBER(17,2),
 IMPORTO_EROGAZIONI NUMBER(13,2),
 IMPORTO_PAGAMENTI_VALIDATI NUMBER(13,2),
 IMPORTO_CERTIFICAZIONE_NETTO NUMBER(17,2)
);
--PK
ALTER TABLE PBANDI_T_DETT_PROP_CERT_ANNUAL ADD  
 ( 
  CONSTRAINT PK_PBANDI_T_DET_PROP_CERT_ANN PRIMARY KEY (ID_DETT_PROP_CERT_ANNUAL)
  USING INDEX
  TABLESPACE PBANDI_IDX 
 );
--FK
ALTER TABLE PBANDI_T_DETT_PROP_CERT_ANNUAL ADD 
CONSTRAINT FK_PBANDI_T_DETT_PROP_CERT_11
 FOREIGN KEY (ID_DETT_PROPOSTA_CERTIF)
 REFERENCES PBANDI_T_DETT_PROPOSTA_CERTIF (ID_DETT_PROPOSTA_CERTIF);
--FK
ALTER TABLE PBANDI_T_DETT_PROP_CERT_ANNUAL ADD 
CONSTRAINT FK_PBANDI_T_PROPOSTA_CERTIF_07
 FOREIGN KEY (ID_PROPOSTA_CERTIFICAZ)
 REFERENCES PBANDI_T_PROPOSTA_CERTIFICAZ (ID_PROPOSTA_CERTIFICAZ);
--
-- PBANDI_T_TRASFERIMENTO
CREATE TABLE PBANDI_T_TRASFERIMENTO
(
ID_TRASFERIMENTO  NUMBER (8),  
COD_TRASFERIMENTO VARCHAR2(60),
DATA_TRASFERIMENTO DATE,
ID_CAUSALE_TRASFERIMENTO NUMBER (8),
IMPORTO_TRASFERIMENTO NUMBER(13,2),
ID_SOGGETTO  NUMBER (8),
FLAG_PUBBLICO_PRIVATO NUMBER(1),
ID_UTENTE_INS NUMBER(8),
ID_UTENTE_AGG NUMBER(8)
);
--PK
ALTER TABLE PBANDI_T_TRASFERIMENTO ADD  
 ( 
  CONSTRAINT PK_PBANDI_T_TRASFERIMENTO PRIMARY KEY (ID_TRASFERIMENTO)
  USING INDEX
  TABLESPACE PBANDI_IDX 
 );
--FK
ALTER TABLE  PBANDI_T_TRASFERIMENTO ADD 
CONSTRAINT FK_PBANDI_D_CAUS_TRASF_03
 FOREIGN KEY (ID_CAUSALE_TRASFERIMENTO)
 REFERENCES PBANDI_D_CAUSALE_TRASFERIMENTO (ID_CAUSALE_TRASFERIMENTO);
 --FK
ALTER TABLE  PBANDI_T_TRASFERIMENTO ADD 
CONSTRAINT FK_PBANDI_T_SOGGETTO_27
 FOREIGN KEY (ID_SOGGETTO)
 REFERENCES PBANDI_T_SOGGETTO (ID_SOGGETTO);
-- CHECK
ALTER TABLE PBANDI.PBANDI_T_TRASFERIMENTO ADD (
  CONSTRAINT CHK_FLAG_PUBBLICO_PRIVATO
  CHECK (FLAG_PUBBLICO_PRIVATO IN (1, 2)));
  
-- PBANDI_T_ECONOMIE
CREATE TABLE PBANDI_T_ECONOMIE
(ID_ECONOMIA INTEGER,--PK
 ID_CONTO_ECONOMICO_CEDENTE NUMBER(8),
 IMPORTO_CEDUTO NUMBER(15,2),
 ID_PROGETTO_RICEVENTE NUMBER(8),
 DATA_RICEVIMENTO DATE,
 DATA_UTILIZZO DATE,
 NOTE_CESSIONE VARCHAR2(2000),
 NOTE_UTILIZZO VARCHAR2(2000)
);
-- PK
ALTER TABLE PBANDI_T_ECONOMIE ADD  
 ( 
  CONSTRAINT PK_PBANDI_T_ECONOMIE PRIMARY KEY (ID_ECONOMIA)
  USING INDEX
  TABLESPACE PBANDI_IDX 
 );
-- FK
ALTER TABLE  PBANDI_T_ECONOMIE ADD 
CONSTRAINT FK_PBANDI_T_PROGETTO_44
 FOREIGN KEY (ID_PROGETTO_RICEVENTE)
 REFERENCES PBANDI_T_PROGETTO (ID_PROGETTO);
-- FK
ALTER TABLE  PBANDI_T_ECONOMIE ADD 
CONSTRAINT FK_PBANDI_T_CONTO_ECONOMICO_05
 FOREIGN KEY (ID_CONTO_ECONOMICO_CEDENTE)
 REFERENCES PBANDI_T_CONTO_ECONOMICO ( ID_CONTO_ECONOMICO);
-- PBANDI_T_SOGGETTO
ALTER TABLE PBANDI_T_SOGGETTO ADD RICEVENTE_TRASF NUMBER(1);
--
-- PBANDI_T_FORNITORE
ALTER TABLE PBANDI_T_FORNITORE ADD ALTRO_CODICE VARCHAR2(30);
COMMENT ON COLUMN PBANDI_T_FORNITORE.ALTRO_CODICE  IS 'Codice che viene utilizzato al posto del cf/partita iva per identificare un fornitore estero';
-- PBANDI_T_DICHIARAZIONE_SPESA
ALTER TABLE PBANDI_T_DICHIARAZIONE_SPESA ADD TIPO_INVIO_DS VARCHAR2(1);
COMMENT ON COLUMN PBANDI_T_DICHIARAZIONE_SPESA.TIPO_INVIO_DS IS 'C = CARTACEO, E = ELETTRONICO';
--

 -- SEQUENCE
CREATE SEQUENCE PBANDI.SEQ_PBANDI_T_DET_PROP_CERT_ANN
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE SEQUENCE PBANDI.SEQ_PBANDI_T_TRASFERIMENTO
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE SEQUENCE PBANDI.SEQ_PBANDI_T_ECONOMIE
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
-- COMMENT
COMMENT ON TABLE PBANDI_T_DETT_PROP_CERT_ANNUAL  IS 'TABELLA DEDICATA AL CALCOLO, PER CIASCUN PROGETTO DELLA PROPOSTA DI RIFERIMENTO, DELLE GRANDEZZE COIVOLTE PER ANNO CONTABILE';
--
-- VISTE
CREATE OR REPLACE FORCE VIEW PBANDI.PBANDI_V_CERTIF_CUM_ANNI_PREC
(
 ID_PROGETTO,
 IMPORTO_REVOCHE,
 IMPORTO_RECUPERI,
 IMPORTO_SOPPRESSIONI,
 IMPORTO_EROGAZIONI,
 IMPORTO_PAGAMENTI_VALIDATI,
 IMPORTO_CERTIFICAZIONE_NETTO   
)
AS
   SELECT   ID_PROGETTO,
                 SUM(NVL(pca.IMPORTO_REVOCHE,0)),
                 SUM(NVL(pca.IMPORTO_RECUPERI,0)),
                 SUM(NVL(pca.IMPORTO_SOPPRESSIONI,0)),
                 SUM(NVL(pca.IMPORTO_EROGAZIONI,0)),
                 SUM(NVL(pca.IMPORTO_PAGAMENTI_VALIDATI,0)),
                 SUM(NVL(pca.IMPORTO_CERTIFICAZIONE_NETTO,0))
     FROM   PBANDI_T_DETT_PROP_CERT_ANNUAL pca,
                PBANDI_T_PROPOSTA_CERTIFICAZ  pc,
                PBANDI_T_DETT_PROPOSTA_CERTIF dpc
     WHERE
                 pca.ID_PROPOSTA_CERTIFICAZ = pc.ID_PROPOSTA_CERTIFICAZ AND
                 dpc.ID_DETT_PROPOSTA_CERTIF = pca.ID_DETT_PROPOSTA_CERTIF AND
                 pc.ID_PERIODO IS NOT NULL AND
                 pc.ID_STATO_PROPOSTA_CERTIF = 17           
     GROUP BY ID_PROGETTO;
     
     
              
              
     
      

