/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

-- PBANDI_D_ERRORE_BATCH

Insert into PBANDI_D_ERRORE_BATCH
   (CODICE_ERRORE, DESCRIZIONE, FLAG_NOTIFICA_MAIL)
 Values
   ('E153', 'File XML non validato - Violato vincolo obbligatorietà', 'S');
Insert into PBANDI_D_ERRORE_BATCH
   (CODICE_ERRORE, DESCRIZIONE, FLAG_NOTIFICA_MAIL)
 Values
   ('E154', 'File XML non validato - Violato definizione schema', 'S');
Insert into PBANDI_D_ERRORE_BATCH
   (CODICE_ERRORE, DESCRIZIONE, FLAG_NOTIFICA_MAIL)
 Values
   ('E155', 'File XML non validato - Violato formato dei dati', 'S');
Insert into PBANDI_D_ERRORE_BATCH
   (CODICE_ERRORE, DESCRIZIONE)
 Values
   ('E156', 'Errore elaborazione indirizzi email');
COMMIT;


--PBANDI_D_INVIO_ANOMALIE_FLUSSI
Insert into PBANDI_D_INVIO_ANOMALIE_FLUSSI
   (ID_INVIO_ANOMALIE_FLUSSI, EMAIL, ID_NOME_BATCH, DT_INIZIO_VALIDITA)
 Values
   (1, 'alessandro.re@consulenti.csi.it', 1, TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_D_INVIO_ANOMALIE_FLUSSI
   (ID_INVIO_ANOMALIE_FLUSSI, EMAIL, ID_NOME_BATCH, DT_INIZIO_VALIDITA)
 Values
   (2, 'salvatore.gabriele@consulenti.csi.it', 1, TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;

--PBANDI_C_COSTANTI
Insert into PBANDI_C_COSTANTI
   (ATTRIBUTO, VALORE)
 Values
   ('VALIDAZIONE_XML_FINPIS', 'N');
   
Insert into PBANDI_C_COSTANTI
   (ATTRIBUTO, VALORE)
 Values
   ('conf.maxNumIstanzeFluxAggiornabili', '5');
COMMIT;

-- PBANDI_C_XSD
SET DEFINE OFF;
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (1, 'FINPIS_VERSO_PBANDI', 'UuidDomanda', 'Domanda', 
    1, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (2, 'FINPIS_VERSO_PBANDI', 'IdEsterno', 'Domanda', 
    1, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (3, 'FINPIS_VERSO_PBANDI', 'Indirizzo', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (4, 'FINPIS_VERSO_PBANDI', 'NumeroCivico', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (5, 'FINPIS_VERSO_PBANDI', 'Cap', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (6, 'FINPIS_VERSO_PBANDI', 'CodiceComune', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (7, 'FINPIS_VERSO_PBANDI', 'PaeseEsteroOAltroComune', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (8, 'FINPIS_VERSO_PBANDI', 'SiglaProvincia', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (9, 'FINPIS_VERSO_PBANDI', 'CodiceFase', 'Domanda', 
    1, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (10, 'FINPIS_VERSO_PBANDI', 'Abi', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (11, 'FINPIS_VERSO_PBANDI', 'Cab', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (12, 'FINPIS_VERSO_PBANDI', 'ContoCorrente', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (13, 'FINPIS_VERSO_PBANDI', 'Iban', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (14, 'FINPIS_VERSO_PBANDI', 'NomeBanca', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (15, 'FINPIS_VERSO_PBANDI', 'IndirizzoAgenzia', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (16, 'FINPIS_VERSO_PBANDI', 'CapAgenzia', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (17, 'FINPIS_VERSO_PBANDI', 'ComuneAgenzia', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (18, 'FINPIS_VERSO_PBANDI', 'FlagExtraPor', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (19, 'FINPIS_VERSO_PBANDI', 'UuidAnagrafica', 'Anagrafica', 
    1, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (20, 'FINPIS_VERSO_PBANDI', 'CodiceFiscale', 'Anagrafica', 
    1, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (21, 'FINPIS_VERSO_PBANDI', 'FlagRichiestaContributo', 'Componente', 'Anagrafica', 
    1, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (22, 'FINPIS_VERSO_PBANDI', 'NumeroDomanda', 'Domanda', 
    1, 'INTEGER', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (23, 'FINPIS_VERSO_PBANDI', 'CodiceDimensioneAzienda', 'Domanda', 
    0, 'INTEGER', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (24, 'FINPIS_VERSO_PBANDI', 'TipoRuolo', 'Componente', 'Anagrafica', 
    1, 'INTEGER', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (25, 'FINPIS_VERSO_PBANDI', 'TipoSocio', 'Componente', 'Anagrafica', 
    0, 'INTEGER', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, ID_XSD_ELEM_OPT, DT_INIZIO_VALIDITA)
 Values
   (26, 'FINPIS_VERSO_PBANDI', 'DataComitato', 'Domanda', 
    0, 'DATE', 27, TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, ID_XSD_ELEM_OPT, DT_INIZIO_VALIDITA)
 Values
   (27, 'FINPIS_VERSO_PBANDI', 'DataConcessione', 'Domanda', 
    0, 'DATE', 26, TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (28, 'FINPIS_VERSO_PBANDI', 'ImportoCostoProgetto', 'Domanda', 
    1, 'DECIMAL', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (29, 'FINPIS_VERSO_PBANDI', 'ImportoRichiesto', 'Domanda', 
    1, 'DECIMAL', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (30, 'FINPIS_VERSO_PBANDI', 'ImportoAmmesso', 'Domanda', 
    1, 'DECIMAL', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (31, 'FINPIS_VERSO_PBANDI', 'ImportoFinanziamento', 'Domanda', 
    1, 'DECIMAL', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (32, 'FINPIS_VERSO_PBANDI', 'ImportoContributo', 'Domanda', 
    1, 'DECIMAL', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (33, 'FINPIS_VERSO_PBANDI', 'ImpegnoNettoTeorico', 'Domanda', 
    1, 'DECIMAL', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (34, 'FINPIS_VERSO_PBANDI', 'ImpegnoNettoEffettivo', 'Domanda', 
    1, 'DECIMAL', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (35, 'FINPIS_VERSO_PBANDI', 'ImportoBanca', 'Domanda', 
    1, 'DECIMAL', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (36, 'FINPIS_VERSO_PBANDI', 'UuidTipoSpesa', 'SpesaDomanda', 'Domanda', 
    1, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (37, 'FINPIS_VERSO_PBANDI', 'IdTipoSpesaEsterno', 'SpesaDomanda', 'Domanda', 
    1, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (38, 'FINPIS_VERSO_PBANDI', 'ImportoSpesa', 'SpesaDomanda', 'Domanda', 
    1, 'DECIMAL', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (39, 'FINPIS_VERSO_PBANDI', 'ImportoContributo', 'SpesaDomanda', 'Domanda', 
    1, 'DECIMAL', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (40, 'FINPIS_VERSO_PBANDI', 'IdFidejussione', 'FidejussioneDomanda', 'Domanda', 
    1, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (41, 'FINPIS_VERSO_PBANDI', 'ImportoFidejussione', 'FidejussioneDomanda', 'Domanda', 
    1, 'DECIMAL', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (42, 'FINPIS_VERSO_PBANDI', 'DataDecorrenza', 'FidejussioneDomanda', 'Domanda', 
    1, 'DATE', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (43, 'FINPIS_VERSO_PBANDI', 'TipoTrattamento', 'FidejussioneDomanda', 'Domanda', 
    1, 'INTEGER', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (44, 'FINPIS_VERSO_PBANDI', 'IdErogazione', 'ErogazioneDomanda', 'Domanda', 
    1, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (45, 'FINPIS_VERSO_PBANDI', 'ImportoErogazione', 'ErogazioneDomanda', 'Domanda', 
    1, 'DECIMAL', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (46, 'FINPIS_VERSO_PBANDI', 'DataErogazione', 'ErogazioneDomanda', 'Domanda', 
    1, 'DATE', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (47, 'FINPIS_VERSO_PBANDI', 'Causale', 'ErogazioneDomanda', 'Domanda', 
    1, 'INTEGER', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (48, 'FINPIS_VERSO_PBANDI', 'TipoAgevolazione', 'ErogazioneDomanda', 'Domanda', 
    1, 'INTEGER', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (49, 'FINPIS_VERSO_PBANDI', 'ModalitaErogazione', 'ErogazioneDomanda', 'Domanda', 
    1, 'INTEGER', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (50, 'FINPIS_VERSO_PBANDI', 'IdRecupero', 'RecuperoDomanda', 'Domanda', 
    1, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (51, 'FINPIS_VERSO_PBANDI', 'TipoRecupero', 'RecuperoDomanda', 'Domanda', 
    1, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (52, 'FINPIS_VERSO_PBANDI', 'DataRecupero', 'RecuperoDomanda', 'Domanda', 
    1, 'DATE', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (53, 'FINPIS_VERSO_PBANDI', 'ImportoCapitale', 'RecuperoDomanda', 'Domanda', 
    1, 'DECIMAL', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, ID_XSD_ELEM_OPT, DT_INIZIO_VALIDITA)
 Values
   (54, 'FINPIS_VERSO_PBANDI', 'CodiceComune', 'Anagrafica', 
    0, 'STRING', 55, TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, ID_XSD_ELEM_OPT, DT_INIZIO_VALIDITA)
 Values
   (55, 'FINPIS_VERSO_PBANDI', 'PaeseEsteroOAltroComune', 'Anagrafica', 
    0, 'STRING', 54, TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, ID_XSD_ELEM_OPT, DT_INIZIO_VALIDITA)
 Values
   (56, 'FINPIS_VERSO_PBANDI', 'RagioneSociale', 'Anagrafica', 
    0, 'STRING', 70, TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (57, 'FINPIS_VERSO_PBANDI', 'NaturaGiuridica', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (58, 'FINPIS_VERSO_PBANDI', 'PartitaIva', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (59, 'FINPIS_VERSO_PBANDI', 'CodAteco', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (60, 'FINPIS_VERSO_PBANDI', 'SottogruppoAttivitaEconomica', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (61, 'FINPIS_VERSO_PBANDI', 'Cap', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (62, 'FINPIS_VERSO_PBANDI', 'SiglaProvincia', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (63, 'FINPIS_VERSO_PBANDI', 'Indirizzo', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (64, 'FINPIS_VERSO_PBANDI', 'NumeroCivico', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (65, 'FINPIS_VERSO_PBANDI', 'Telefono', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (66, 'FINPIS_VERSO_PBANDI', 'Fax', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (67, 'FINPIS_VERSO_PBANDI', 'Email', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (68, 'FINPIS_VERSO_PBANDI', 'DataCostituzione', 'Anagrafica', 
    0, 'DATE', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (69, 'FINPIS_VERSO_PBANDI', 'SiglaProvinciaIscrizioneRegistroImprese', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, ID_XSD_ELEM_OPT, DT_INIZIO_VALIDITA)
 Values
   (70, 'FINPIS_VERSO_PBANDI', 'Cognome', 'Anagrafica', 
    0, 'STRING', 56, TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (71, 'FINPIS_VERSO_PBANDI', 'Nome', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (72, 'FINPIS_VERSO_PBANDI', 'Sesso', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (73, 'FINPIS_VERSO_PBANDI', 'DataNascita', 'Anagrafica', 
    0, 'DATE', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (74, 'FINPIS_VERSO_PBANDI', 'CodiceComuneNascita', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (75, 'FINPIS_VERSO_PBANDI', 'ComuneOPaeseEsteroNascita', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (76, 'FINPIS_VERSO_PBANDI', 'IndirizzoResidenza', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (77, 'FINPIS_VERSO_PBANDI', 'NumeroCivicoResidenza', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (78, 'FINPIS_VERSO_PBANDI', 'CodiceComuneResidenza', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (79, 'FINPIS_VERSO_PBANDI', 'CapResidenza', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (80, 'FINPIS_VERSO_PBANDI', 'SiglaProvinciaResidenza', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (81, 'FINPIS_VERSO_PBANDI', 'PaeseEsteroOAltroComuneResidenza', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (82, 'FINPIS_VERSO_PBANDI', 'TipodocumentoRiconoscimento', 'Anagrafica', 
    0, 'INTEGER', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (83, 'FINPIS_VERSO_PBANDI', 'NumeroDocumentoRiconoscimento', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (84, 'FINPIS_VERSO_PBANDI', 'DataRilascioDocumento', 'Anagrafica', 
    0, 'DATE', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (85, 'FINPIS_VERSO_PBANDI', 'DataScadenzaDocumento', 'Anagrafica', 
    0, 'DATE', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (86, 'FINPIS_VERSO_PBANDI', 'EnteRilascioDocumento', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (87, 'FINPIS_VERSO_PBANDI', 'CodiceOccupazione', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (88, 'FINPIS_VERSO_PBANDI', 'CodiceCittadinanza', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (89, 'FINPIS_VERSO_PBANDI', 'CodiceTitoloStudio', 'Anagrafica', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (90, 'FINPIS_VERSO_PBANDI', 'DataInizioValidita', 'Componente', 'Anagrafica', 
    0, 'DATE', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (91, 'FINPIS_VERSO_PBANDI', 'DataFineValidita', 'Componente', 'Anagrafica', 
    0, 'DATE', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (92, 'FINPIS_VERSO_PBANDI', 'ImportoErogato', 'SpesaDomanda', 'Domanda', 
    0, 'DECIMAL', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (93, 'FINPIS_VERSO_PBANDI', 'DataScadenza', 'FidejussioneDomanda', 'Domanda', 
    0, 'DATE', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (94, 'FINPIS_VERSO_PBANDI', 'DataSvincolo', 'FidejussioneDomanda', 'Domanda', 
    0, 'DATE', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (95, 'FINPIS_VERSO_PBANDI', 'EnteEmittente', 'FidejussioneDomanda', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (96, 'FINPIS_VERSO_PBANDI', 'NoteFidejussione', 'FidejussioneDomanda', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (97, 'FINPIS_VERSO_PBANDI', 'NoteErogazione', 'ErogazioneDomanda', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (98, 'FINPIS_VERSO_PBANDI', 'IdFidejussione', 'ErogazioneDomanda', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (99, 'FINPIS_VERSO_PBANDI', 'TipoAgevolazione', 'RecuperoDomanda', 'Domanda', 
    0, 'INTEGER', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (100, 'FINPIS_VERSO_PBANDI', 'ImportoInteressi', 'RecuperoDomanda', 'Domanda', 
    0, 'DECIMAL', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (101, 'FINPIS_VERSO_PBANDI', 'NoteRecupero', 'RecuperoDomanda', 'Domanda', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (102, 'FINPIS_VERSO_PBANDI', 'UuidAnagrafica', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (103, 'FINPIS_VERSO_PBANDI', 'CodiceFiscale', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (104, 'FINPIS_VERSO_PBANDI', 'CodiceComune', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (105, 'FINPIS_VERSO_PBANDI', 'PaeseEsteroOAltroComune', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, ID_XSD_ELEM_OPT, DT_INIZIO_VALIDITA)
 Values
   (106, 'FINPIS_VERSO_PBANDI', 'RagioneSociale', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', 135, TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (107, 'FINPIS_VERSO_PBANDI', 'NaturaGiuridica', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (108, 'FINPIS_VERSO_PBANDI', 'PartitaIva', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (109, 'FINPIS_VERSO_PBANDI', 'CodAteco', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (110, 'FINPIS_VERSO_PBANDI', 'SottogruppoAttivitaEconomica', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (111, 'FINPIS_VERSO_PBANDI', 'Cap', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (112, 'FINPIS_VERSO_PBANDI', 'SiglaProvincia', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (113, 'FINPIS_VERSO_PBANDI', 'Indirizzo', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (114, 'FINPIS_VERSO_PBANDI', 'NumeroCivico', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (115, 'FINPIS_VERSO_PBANDI', 'Telefono', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (116, 'FINPIS_VERSO_PBANDI', 'Fax', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (117, 'FINPIS_VERSO_PBANDI', 'Email', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (118, 'FINPIS_VERSO_PBANDI', 'DataCostituzione', 'AnagraficaComponente', 'Componente', 
    0, 'DATE', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (119, 'FINPIS_VERSO_PBANDI', 'SiglaProvinciaIscrizioneRegistroImprese', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (120, 'FINPIS_VERSO_PBANDI', 'Nome', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (121, 'FINPIS_VERSO_PBANDI', 'Sesso', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (122, 'FINPIS_VERSO_PBANDI', 'DataNascita', 'AnagraficaComponente', 'Componente', 
    0, 'DATE', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (123, 'FINPIS_VERSO_PBANDI', 'ComuneOPaeseEsteroNascita', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (124, 'FINPIS_VERSO_PBANDI', 'IndirizzoResidenza', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (125, 'FINPIS_VERSO_PBANDI', 'NumeroCivicoResidenza', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (126, 'FINPIS_VERSO_PBANDI', 'CapResidenza', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (127, 'FINPIS_VERSO_PBANDI', 'SiglaProvinciaResidenza', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (128, 'FINPIS_VERSO_PBANDI', 'PaeseEsteroOAltroComuneResidenza', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (129, 'FINPIS_VERSO_PBANDI', 'TipodocumentoRiconoscimento', 'AnagraficaComponente', 'Componente', 
    0, 'INTEGER', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (130, 'FINPIS_VERSO_PBANDI', 'DataRilascioDocumento', 'AnagraficaComponente', 'Componente', 
    0, 'DATE', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (131, 'FINPIS_VERSO_PBANDI', 'DataScadenzaDocumento', 'AnagraficaComponente', 'Componente', 
    0, 'DATE', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (132, 'FINPIS_VERSO_PBANDI', 'EnteRilascioDocumento', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (133, 'FINPIS_VERSO_PBANDI', 'CodiceOccupazione', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (134, 'FINPIS_VERSO_PBANDI', 'CodiceTitoloStudio', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, ID_XSD_ELEM_OPT, DT_INIZIO_VALIDITA)
 Values
   (135, 'FINPIS_VERSO_PBANDI', 'Cognome', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', 106, TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (136, 'FINPIS_VERSO_PBANDI', 'CodiceComuneNascita', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (137, 'FINPIS_VERSO_PBANDI', 'CodiceComuneResidenza', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (138, 'FINPIS_VERSO_PBANDI', 'NumeroDocumentoRiconoscimento', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PBANDI_C_XSD
   (ID_XSD, NOME_XSD, NOME_ELEM, NOME_ELEM_PADRE, NOME_ELEM_PADRE_2, FLAG_REQUIRED, TIPO_ELEM, DT_INIZIO_VALIDITA)
 Values
   (139, 'FINPIS_VERSO_PBANDI', 'CodiceCittadinanza', 'AnagraficaComponente', 'Componente', 
    0, 'STRING', TO_DATE('01/01/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;

ALTER TABLE PBANDI_C_XSD ADD 
CONSTRAINT FK_PBANDI_C_XSD_01
 FOREIGN KEY (ID_XSD_ELEM_OPT)
 REFERENCES PBANDI_C_XSD (ID_XSD);
 
-- PBANDI_D_PERMESSO 
 INSERT INTO PBANDI_D_PERMESSO 
(ID_PERMESSO,DESC_BREVE_PERMESSO,DESC_PERMESSO,DT_INIZIO_VALIDITA,DT_FINE_VALIDITA)
 VALUES
(146,'TRSCLA001','Accesso alla console dei log applicativi',TRUNC(sysdate),null);

 INSERT INTO PBANDI_D_PERMESSO 
(ID_PERMESSO,DESC_BREVE_PERMESSO,DESC_PERMESSO,DT_INIZIO_VALIDITA,DT_FINE_VALIDITA)
 VALUES
(147,'VERSERV','Accesso alla console verifica servizi esterni',TRUNC(sysdate),null);

COMMIT;

/*
*** script da eseguire ad ogni rilascio
*/
update PBANDI_C_VERSIONE
set VERSIONE_DB = '2.9.0';

insert into PBANDI_C_ENTITA
(ID_ENTITA, NOME_ENTITA, FLAG_DA_TRACCIARE) 
(select seq_PBANDI_C_ENTITA.nextval,tabs.TABLE_NAME,'S'
from all_tables tabs
where tabs.OWNER = (select decode(instr(user,'_RW'),0,user,replace(user,'_RW',null)) from dual)
and tabs.TABLE_NAME like 'PBANDI_%'
and not exists (select 'x' from pbandi_c_entita where tabs.TABLE_NAME = NOME_ENTITA));

commit;

declare
  cursor curAttr is select col.COLUMN_NAME,en.id_ENTITA,col.TABLE_NAME
                    from all_tab_cols col,PBANDI_C_ENTITA en
                    where col.owner = (select decode(instr(user,'_RW'),0,user,replace(user,'_RW',null)) from dual)
                    and col.TABLE_NAME like 'PBANDI_%'
                    and col.COLUMN_NAME not like 'SYS_%'
                    and col.TABLE_NAME = en.NOME_ENTITA
                    and not exists (select 'x' from PBANDI_C_ATTRIBUTO att 
                                    where col.COLUMN_NAME = att.NOME_ATTRIBUTO
                                    and att.id_entita = en.id_ENTITA);
                                    
  nPosiz  PLS_INTEGER := NULL;                                                                          
begin
  for recAttr in curAttr loop

    BEGIN
      SELECT POSITION
      INTO   nPosiz 
      FROM   all_CONSTRAINTS A,all_CONS_COLUMNS B
      WHERE  A.CONSTRAINT_TYPE = 'P'
      AND    A.TABLE_NAME      = recAttr.TABLE_NAME
      AND    A.CONSTRAINT_NAME = B.CONSTRAINT_NAME
      AND    COLUMN_NAME       = recAttr.COLUMN_NAME;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        nPosiz := NULL;
    END;
    
    insert into PBANDI_C_ATTRIBUTO
    (ID_ATTRIBUTO, 
     NOME_ATTRIBUTO, 
     FLAG_DA_TRACCIARE, 
     ID_ENTITA,
     KEY_POSITION_ID) 
    values
    (SEQ_PBANDI_C_ATTRIBUTO.NEXTVAL,
     recAttr.COLUMN_NAME,
     'N',
     recAttr.id_ENTITA,
     nPosiz);
  end loop;
  COMMIT;
end;
/



