/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

ALTER TABLE pbandi_t_rigo_conto_economico
	ADD (IMPORTO_EROGATO NUMBER(17,2));

ALTER TABLE PBANDI_R_PROPOSTA_CERTIF_LINEA ADD (
  CONSTRAINT AK1_PBANDI_R_PROP_CERTIF_LINE
  UNIQUE (ID_PROPOSTA_CERTIFICAZ)
  USING INDEX
  TABLESPACE PBANDI_SMALL_IDX);
  
CREATE INDEX IE2_PBANDI_W_ATTI_LIQUIDAZI_DL ON PBANDI_W_ATTI_LIQUIDAZIONE_DL
  (ID_ATTI_LIQUIDAZIONE_DT)
  TABLESPACE PBANDI_SMALL_IDX;

CREATE INDEX IE2_PBANDI_W_ATTI_LIQUIDAZI_DM ON PBANDI_W_ATTI_LIQUIDAZIONE_DM
(ID_ATTI_LIQUIDAZIONE_DT)
TABLESPACE PBANDI_SMALL_IDX;

ALTER TABLE PBANDI_D_LINEA_DI_INTERVENTO
 ADD (NUM_DELIBERA  NUMBER(6),ANNO_DELIBERA  NUMBER(4));

ALTER TABLE PBANDI_T_DATI_PROGETTO_MONIT
 ADD (NUM_DELIBERA  NUMBER(6),ANNO_DELIBERA  NUMBER(4));

ALTER TABLE PBANDI_T_PROGETTO ADD
 FLAG_AR_FLUX                    VARCHAR2(1) DEFAULT 'N' NOT NULL;

COMMENT ON COLUMN PBANDI_T_PROGETTO.FLAG_AR_FLUX IS 'Viene impostato ad S se il progetto è stato elaborato con esito positivo da batch java RendicontatoreMassivo(FLUX)';
 