/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/


alter table pbandi_d_voce_di_spesa modify DESC_VOCE_DI_SPESA varchar2(300);
alter table PBANDI_T_ENTE_GIURIDICO modify DENOMINAZIONE_ENTE_GIURIDICO varchar2(1000);
alter table pbandi_t_soggetto_durc modify NUM_PROTOCOLLO_INPS varchar2(50);
ALTER TABLE PBANDI_T_RIASSICURAZIONI MODIFY RAGIONE_SOCIALE Varchar2(200);

-- pbandi_t_escussione
ALTER TABLE pbandi_t_escussione add
(DENOMINAZIONE_BANCA VARCHAR2(200),
 LOCALITA_FILIALE VARCHAR2(200),
 INDIRIZZO_FILIALE VARCHAR2(200),
 CAP_FILIALE VARCHAR2(6),
 PROVINCIA_FILIALE VARCHAR2(200),
 DATA_RICHIESTA_INTEGRAZIONI DATE,
 DATA_RICEZIONE_INTEGRAZIONI DATE
);


CREATE INDEX IE1_PBANDI_M_FINPIS_DICH ON PBANDI_W_MFINPIS_DICH
(ID_PROGETTO)
TABLESPACE PBANDI_IDX;

ALTER TABLE PBANDI_W_MFINPIS_DICH ADD (
  CONSTRAINT FK_PBANDI_T_PROGETTO_103 
 FOREIGN KEY (ID_PROGETTO) 
 REFERENCES PBANDI_T_PROGETTO (ID_PROGETTO));
 
ALTER TABLE PBANDI.PBANDI_T_RNA_PROGETTO_MAN
MODIFY(ACOVAR1 VARCHAR2(20)); 
 
--
/* eseguito il 22122023 alle 14.50
-- PBANDI_T_GESTIONE_REVOCA
ALTER TABLE PBANDI_T_GESTIONE_REVOCA ADD ID_CAUSALE_EROG_FIN NUMBER(8);
ALTER TABLE PBANDI_T_GESTIONE_REVOCA ADD ID_CAUSALE_EROG_CONTR NUMBER(8);
-- fk
ALTER TABLE PBANDI_T_GESTIONE_REVOCA   ADD CONSTRAINT fk_pbandi_d_causale_erogazi_07
    FOREIGN KEY (ID_CAUSALE_EROG_FIN) REFERENCES PBANDI_D_CAUSALE_EROGAZIONE(ID_CAUSALE_EROGAZIONE);
ALTER TABLE PBANDI_T_GESTIONE_REVOCA   ADD CONSTRAINT fk_pbandi_d_causale_erogazi_08 
    FOREIGN KEY (ID_CAUSALE_EROG_CONTR) REFERENCES PBANDI_D_CAUSALE_EROGAZIONE(ID_CAUSALE_EROGAZIONE);
-- idx
CREATE INDEX ie_pbandi_t_gestione_revoca_11 ON PBANDI_T_GESTIONE_REVOCA (ID_CAUSALE_EROG_FIN)  TABLESPACE PBANDI_IDX;
CREATE INDEX ie_pbandi_t_gestione_revoca_12 ON PBANDI_T_GESTIONE_REVOCA (ID_CAUSALE_EROG_CONTR)  TABLESPACE PBANDI_IDX;
-- PBANDI_T_INTEGRAZIONE_SPESA
ALTER TABLE PBANDI_T_INTEGRAZIONE_SPESA ADD CONSTRAINT FK_PBANDI_D_STATO_RICH_INT_01 
    FOREIGN KEY (ID_STATO_RICHIESTA) REFERENCES PBANDI_D_STATO_RICH_INTEGRAZ (ID_STATO_RICHIESTA);
/*

