/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

--PBANDI_T_DETT_PROPOSTA_CERTIF
ALTER TABLE PBANDI_T_DETT_PROPOSTA_CERTIF MODIFY TITOLO_PROGETTO VARCHAR2(2000);

--PBANDI_T_DOCUMENTO_DI_SPESA
ALTER TABLE  PBANDI_T_DOCUMENTO_DI_SPESA   MODIFY  DESC_DOCUMENTO VARCHAR2(2000);

--PBANDI_T_CSP_PROGETTO
ALTER TABLE  PBANDI_T_CSP_PROGETTO   MODIFY    TITOLO_PROGETTO  VARCHAR2(2000);

--PBANDI_T_DOMANDA
ALTER TABLE   PBANDI_T_DOMANDA    MODIFY    TITOLO_PROGETTO  VARCHAR2(2000);

--PBANDI_T_PROGETTO
ALTER TABLE  PBANDI_T_PROGETTO    MODIFY    TITOLO_PROGETTO  VARCHAR2(2000);

--PBANDI_T_RAGGRUPPAMENTO
ALTER TABLE  PBANDI_T_RAGGRUPPAMENTO  MODIFY ACRONIMO_PROGETTO  VARCHAR2(2000);

--PBANDI_R_FORNITORE_QUALIFICA
ALTER TABLE   PBANDI_R_FORNITORE_QUALIFICA  MODIFY NOTE_QUALIFICA  VARCHAR2(2000);

--PBANDI_T_APPALTO
ALTER TABLE   PBANDI_T_APPALTO MODIFY INTERVENTO_PISU   VARCHAR2(2000);
ALTER TABLE   PBANDI_T_APPALTO MODIFY IMPRESA_APPALTATRICE   VARCHAR2(2000);

--PBANDI_T_PROCEDURA_AGGIUDICAZ
ALTER TABLE  PBANDI_T_PROCEDURA_AGGIUDICAZ MODIFY DESC_PROC_AGG  VARCHAR2(2000);

--PBANDI_D_SETTORE_ENTE
ALTER TABLE   PBANDI_D_SETTORE_ENTE  MODIFY DESC_SETTORE   VARCHAR2(200);

--PBANDI_T_RINUNCIA
ALTER TABLE    PBANDI_T_RINUNCIA MODIFY MOTIVO_RINUNCIA  VARCHAR2(2500);