SELECT
	DS.ID_PROGETTO,
	DS.ID_DICHIARAZIONE_SPESA,
	fi.NOME_FILE,
	docIndex.ID_DOCUMENTO_INDEX,
	docIndex.UUID_NODO
FROM
	PBANDI_T_DICHIARAZIONE_SPESA DS,
	PBANDI_T_FILE_ENTITA FE,
	PBANDI_T_FILE FI,
	PBANDI_T_DOCUMENTO_INDEX docIndex
WHERE
	DS.ID_DICHIARAZIONE_SPESA = FE.ID_TARGET
	AND DOCINDEX.ID_DOCUMENTO_INDEX = fi.ID_DOCUMENTO_INDEX
	AND FE.ID_FILE = FI.ID_FILE
	AND FE.ID_ENTITA = (
	SELECT
		ID_ENTITA
	FROM
		PBANDI_C_ENTITA
	WHERE
		NOME_ENTITA = 'PBANDI_T_DICHIARAZIONE_SPESA')
UNION SELECT
	docIndex.ID_PROGETTO,
	docIndex.ID_TARGET AS ID_DICHIARAZIONE_SPESA,
	docIndex.NOME_FILE,
	docIndex.ID_DOCUMENTO_INDEX,
	docIndex.UUID_NODO
FROM
	PBANDI_T_DOCUMENTO_INDEX docIndex
WHERE
	docIndex.ID_ENTITA = (
	SELECT
		ID_ENTITA
	FROM
		PBANDI_C_ENTITA
	WHERE
		NOME_ENTITA = 'PBANDI_T_DICHIARAZIONE_SPESA')