SELECT CAU.DESC_CAUSALE
  || NVL2(GIU.DESC_FORMA_GIURIDICA,' - '||GIU.DESC_FORMA_GIURIDICA,'')
  || NVL2(DIM.DESC_DIMENSIONE_IMPRESA,' (dimensione '|| DIM.DESC_DIMENSIONE_IMPRESA||')','')
  || NVL2(R.PERC_SOGLIA_SPESA_QUIETANZATA,' - Soglia spesa quitenzata '||R.PERC_SOGLIA_SPESA_QUIETANZATA||'%','')
  || NVL2(R.PERC_EROGAZIONE,' - Erogazione '||R.PERC_EROGAZIONE||'%','')
  || NVL2(R.PERC_LIMITE,' - Limite '||R.PERC_LIMITE||'%','') AS DESC_TABELLARE,
  CAU.DESC_CAUSALE,
  DIM.DESC_DIMENSIONE_IMPRESA,
  GIU.DESC_FORMA_GIURIDICA,
  R.*
FROM PBANDI_R_BANDO_CAUSALE_EROGAZ R,
  PBANDI_D_CAUSALE_EROGAZIONE CAU,
  PBANDI_D_DIMENSIONE_IMPRESA DIM,
  PBANDI_D_FORMA_GIURIDICA GIU
WHERE R.ID_CAUSALE_EROGAZIONE = CAU.ID_CAUSALE_EROGAZIONE(+)
AND R.ID_DIMENSIONE_IMPRESA   = DIM.ID_DIMENSIONE_IMPRESA(+)
AND R.ID_FORMA_GIURIDICA      = GIU.ID_FORMA_GIURIDICA(+)
AND NVL(TRUNC(CAU.DT_FINE_VALIDITA), TRUNC(SYSDATE+1)) > TRUNC(SYSDATE)
AND NVL(TRUNC(DIM.DT_FINE_VALIDITA), TRUNC(SYSDATE+1)) > TRUNC(SYSDATE)
AND NVL(TRUNC(GIU.DT_FINE_VALIDITA), TRUNC(SYSDATE+1)) > TRUNC(SYSDATE)