SELECT
 	TCAMPIONAMENTO.ID_CAMPIONE,
	tcampionamento.DATA_CAMPIONAMENTO,
	tcampionamento.ID_PROPOSTA_CERTIFICAZ,
	tcampionamento.ID_LINEA_DI_INTERVENTO,
	tcampionamento.ID_CATEG_ANAGRAFICA,
	tcampionamento.ID_PERIODO,
	RCAMPIONAMENTO.AVANZAMENTO,
	RCAMPIONAMENTO.PROGR_OPERAZIONE,
	RCAMPIONAMENTO.TITOLO_PROGETTO,
	RCAMPIONAMENTO.UNIVERSO,
	RCAMPIONAMENTO.ID_PROGETTO,
	TPROGETTO.ID_TIPO_OPERAZIONE,
	dto.DESC_TIPO_OPERAZIONE,
	TPROGETTO.CODICE_VISUALIZZATO,
	INTERVENTO.DESC_LINEA,
	RCAMPIONAMENTO.ASSE,
 	PERIODO.DESC_PERIODO_VISUALIZZATA,
 	TCAMPIONAMENTO.TIPO_CONTROLLI
FROM
	PBANDI_T_CAMPIONAMENTO tcampionamento LEFT JOIN pbandi_t_periodo periodo ON TCAMPIONAMENTO.ID_PERIODO = PERIODO.ID_PERIODO,
	PBANDI_R_CAMPIONAMENTO rcampionamento LEFT JOIN PBANDI_T_PROGETTO tprogetto ON RCAMPIONAMENTO.ID_PROGETTO = TPROGETTO.ID_PROGETTO LEFT JOIN PBANDI_D_TIPO_OPERAZIONE dto ON TPROGETTO.ID_TIPO_OPERAZIONE = dto.ID_TIPO_OPERAZIONE,
	PBANDI_D_LINEA_DI_INTERVENTO intervento
WHERE
	TCAMPIONAMENTO.ID_CAMPIONE = RCAMPIONAMENTO.ID_CAMPIONE
	AND TCAMPIONAMENTO.ID_LINEA_DI_INTERVENTO = INTERVENTO.ID_LINEA_DI_INTERVENTO