SELECT DISTINCT  VOCEPADRE.COD_TIPO_VOCE_DI_SPESA_PADRE CODICE_VOCE_PADRE,
VOCEPADRE.DESC_VOCE_DI_SPESA_PADRE DESC_VOCE_PADRE,
SOTTOVOCE.COD_TIPO_VOCE_DI_SPESA CODICE_SOTTO_VOCE,
SOTTOVOCE.DESC_VOCE_DI_SPESA DESCRIZIONE_SOTTO_VOCE,
PR.ID_PROGETTO, 
DOM.ID_DOMANDA,
CODICE_VISUALIZZATO,
PR.TITOLO_PROGETTO ,
ID_STATO_CONTO_ECONOMICO, 
CE.ID_CONTO_ECONOMICO, 
RIGO.ID_RIGO_CONTO_ECONOMICO,
RIGO.IMPORTO_AMMESSO_FINANZIAMENTO,
NOME_BANDO_LINEA,
ID_SOGGETTO,
DOM.DT_PRESENTAZIONE_DOMANDA
FROM 
 PBANDI_T_PROGETTO PR,
 PBANDI_T_DOMANDA DOM,
 PBANDI_R_BANDO_LINEA_INTERVENT RBLI,
 PBANDI_R_SOGGETTO_PROGETTO RSP,
 PBANDI_T_CONTO_ECONOMICO CE,
 PBANDI_T_RIGO_CONTO_ECONOMICO RIGO,
 PBANDI_D_VOCE_DI_SPESA SOTTOVOCE,
 (SELECT ID_VOCE_DI_SPESA, DESC_VOCE_DI_SPESA AS DESC_VOCE_DI_SPESA_PADRE,
    COD_TIPO_VOCE_DI_SPESA COD_TIPO_VOCE_DI_SPESA_PADRE
  FROM PBANDI_D_VOCE_DI_SPESA
  WHERE NVL(TRUNC(PBANDI_D_VOCE_DI_SPESA.DT_FINE_VALIDITA), TRUNC(SYSDATE+1)) > TRUNC(SYSDATE)
  ) VOCEPADRE
WHERE PR.ID_DOMANDA = DOM.ID_DOMANDA
   AND CE.ID_DOMANDA = DOM.ID_DOMANDA 
   AND CE.ID_STATO_CONTO_ECONOMICO IN (SELECT ID_STATO_CONTO_ECONOMICO
                                       FROM  PBANDI_D_TIPOLOGIA_CONTO_ECON TIPOCE 
                                       JOIN
                                       PBANDI_D_STATO_CONTO_ECONOMICO STATOCE 
                                       USING(ID_TIPOLOGIA_CONTO_ECONOMICO) 
                                       WHERE TIPOCE.DESC_BREVE_TIPOLOGIA_CONTO_ECO ='MASTER' )
   AND NVL(TRUNC(CE.DT_FINE_VALIDITA), TRUNC(SYSDATE+1)) > TRUNC(SYSDATE)
   AND CE.ID_CONTO_ECONOMICO = RIGO.ID_CONTO_ECONOMICO
   AND RBLI.PROGR_BANDO_LINEA_INTERVENTO = DOM.PROGR_BANDO_LINEA_INTERVENTO
   AND RSP.ID_PROGETTO= PR.ID_PROGETTO
   AND RSP.ID_TIPO_ANAGRAFICA = 1
   AND RSP.ID_TIPO_BENEFICIARIO <> 4
   AND RIGO.ID_VOCE_DI_SPESA=SOTTOVOCE.ID_VOCE_DI_SPESA   
   AND VOCEPADRE.ID_VOCE_DI_SPESA(+)   = SOTTOVOCE.ID_VOCE_DI_SPESA_PADRE
   AND NVL(TRUNC(SOTTOVOCE.DT_FINE_VALIDITA), TRUNC(SYSDATE+1)) > TRUNC(SYSDATE)