SELECT
	DISTINCT TPF.COGNOME,
	TPF.NOME,
	TS.CODICE_FISCALE_SOGGETTO AS CODICE_FISCALE,
	TPF.ID_SOGGETTO,
	TPF.ID_PERSONA_FISICA,
	RSTA.ID_TIPO_ANAGRAFICA,
	DTA.DESC_TIPO_ANAGRAFICA,
	DTA.DESC_BREVE_TIPO_ANAGRAFICA,
	TS.DT_INSERIMENTO AS DATA_INSERIMENTO,
	RSC.ID_TIPO_SOGGETTO_CORRELATO AS ID_RELAZIONE_BENEFICIARIO ,
	ecs.id_ente_competenza id_ente_operatore,
	rblente.id_ente_competenza id_ente_progetto,
	(
	SELECT
		COUNT(*)
	FROM
		PBANDI_R_SOGGETTO_PROGETTO
	WHERE
		TPF.ID_SOGGETTO = PBANDI_R_SOGGETTO_PROGETTO.ID_SOGGETTO
		AND SYSDATE < NVL(PBANDI_R_SOGGETTO_PROGETTO.DT_FINE_VALIDITA, SYSDATE + 1) ) PROGETTI_VALIDI,
	(
	SELECT
		COUNT(*)
	FROM
		PBANDI_R_SOGGETTO_PROGETTO
	WHERE
		TPF.ID_SOGGETTO = PBANDI_R_SOGGETTO_PROGETTO.ID_SOGGETTO
		AND PBANDI_R_SOGGETTO_PROGETTO.DT_FINE_VALIDITA <SYSDATE) PROGETTI_NON_VALIDI,
	tu.ID_UTENTE
FROM
	PBANDI_T_SOGGETTO TS,
	PBANDI_V_PERSONA_FISICA TPF,
	PBANDI_R_SOGG_TIPO_ANAGRAFICA RSTA,
	PBANDI_D_TIPO_ANAGRAFICA DTA ,
	PBANDI_R_SOGGETTI_CORRELATI RSC,
	PBANDI_R_ENTE_COMPETENZA_SOGG ECS,
	PBANDI_R_SOGGETTO_PROGETTO RSP,
	PBANDI_T_PROGETTO PR,
	PBANDI_T_DOMANDA DOM,
	PBANDI_R_BANDO_LINEA_ENTE_COMP RBLENTE,
	PBANDI_D_RUOLO_ENTE_COMPETENZA RUOLOENTE,
	PBANDI_T_UTENTE TU
WHERE
	TS.ID_SOGGETTO = TPF.ID_SOGGETTO
	AND TS.ID_SOGGETTO = TU.ID_SOGGETTO(+)
	AND TS.ID_SOGGETTO = RSTA.ID_SOGGETTO
	AND TS.ID_SOGGETTO = RSC.ID_SOGGETTO(+)
	AND RSTA.ID_TIPO_ANAGRAFICA = DTA.ID_TIPO_ANAGRAFICA
	AND RSTA.ID_SOGGETTO = ECS.ID_SOGGETTO(+)
	AND RSTA.ID_SOGGETTO = RSP.ID_SOGGETTO(+)
	AND RSP.ID_PROGETTO = PR.ID_PROGETTO(+)
	AND PR.ID_DOMANDA = DOM.ID_DOMANDA(+)
	AND DOM.PROGR_BANDO_LINEA_INTERVENTO = RBLENTE.PROGR_BANDO_LINEA_INTERVENTO (+)
	AND RUOLOENTE.ID_RUOLO_ENTE_COMPETENZA(+)= RBLENTE.ID_RUOLO_ENTE_COMPETENZA
	AND ( RUOLOENTE.DESC_BREVE_RUOLO_ENTE = 'DESTINATARIO'
	OR RUOLOENTE.DESC_BREVE_RUOLO_ENTE IS NULL )
	AND SYSDATE < NVL(DTA.DT_FINE_VALIDITA, SYSDATE + 1)
	AND SYSDATE < NVL(ECS.DT_FINE_VALIDITA, SYSDATE + 1)
	AND SYSDATE < NVL(RSTA.DT_FINE_VALIDITA, SYSDATE + 1)
	AND SYSDATE < NVL(RBLENTE.DT_FINE_VALIDITA, SYSDATE + 1)
	AND SYSDATE < NVL(RSC.DT_FINE_VALIDITA, SYSDATE + 1)
	AND ( (SYSDATE < NVL(RSP.DT_FINE_VALIDITA, SYSDATE + 1) )
	OR ( 0 < (
	SELECT
		COUNT(*)
	FROM
		PBANDI_R_SOGGETTO_PROGETTO
	WHERE
		ts.id_soggetto = PBANDI_R_SOGGETTO_PROGETTO.id_soggetto
		AND PBANDI_R_SOGGETTO_PROGETTO.DT_FINE_VALIDITA <SYSDATE
		AND 0 = (
		SELECT
			COUNT(*)
		FROM
			PBANDI_R_SOGGETTO_PROGETTO
		WHERE
			TS.ID_SOGGETTO = PBANDI_R_SOGGETTO_PROGETTO.ID_SOGGETTO
			AND SYSDATE < NVL(PBANDI_R_SOGGETTO_PROGETTO.DT_FINE_VALIDITA, SYSDATE + 1) ) ) ) )
