select distinct
PBANDI_T_DOCUMENTO_INDEX.ID_DOCUMENTO_INDEX , PBANDI_T_DOCUMENTO_INDEX.VERSIONE, NOTE_DOCUMENTO_INDEX, NOME_FILE ,
PBANDI_T_DOCUMENTO_INDEX.ID_ENTITA, UUID_NODO , PBANDI_T_DOCUMENTO_INDEX.ID_TARGET,
PBANDI_T_DOCUMENTO_INDEX.ID_TIPO_DOCUMENTO_INDEX, ID_UTENTE_INS,
PBANDI_T_DOCUMENTO_INDEX.ID_PROGETTO,PBANDI_T_DOCUMENTO_INDEX.NUM_PROTOCOLLO,
ID_UTENTE_AGG, DT_AGGIORNAMENTO_INDEX,
stato.id_stato_tipo_doc_index,
REPOSITORY, DT_INSERIMENTO_INDEX, ID_MODELLO, ID_SOGG_DELEGATO  , ID_SOGG_RAPPR_LEGALE  , FLAG_FIRMA_CARTACEA, DT_MARCA_TEMPORALE ,
dt_verifica_firma,message_digest,id_stato_documento, PBANDI_T_DOCUMENTO_INDEX.ID_CATEG_ANAGRAFICA_MITT
from 
PBANDI_T_DOCUMENTO_INDEX JOIN PBANDI_R_DOCU_INDEX_TIPO_STATO stato on  stato.id_documento_index = PBANDI_T_DOCUMENTO_INDEX.id_documento_index,
(select a.ID_ENTITA, a.ID_TARGET ,a.ID_TIPO_DOCUMENTO_INDEX, a.ID_PROGETTO, max(versione)  
over ( partition by  a.ID_ENTITA, a.ID_TARGET , a.ID_TIPO_DOCUMENTO_INDEX, a.ID_PROGETTO ) as versione  
from PBANDI_T_DOCUMENTO_INDEX a, PBANDI_R_DOCU_INDEX_TIPO_STATO b
where b.id_documento_index = a.id_documento_index and b.ID_STATO_TIPO_DOC_INDEX = 2) maxVersione
where nvl(PBANDI_T_DOCUMENTO_INDEX.versione, -1) = nvl(maxVersione.versione, -1) 
and PBANDI_T_DOCUMENTO_INDEX.ID_ENTITA=maxVersione.ID_ENTITA
and PBANDI_T_DOCUMENTO_INDEX.ID_TARGET =maxVersione.ID_TARGET
and PBANDI_T_DOCUMENTO_INDEX.ID_TIPO_DOCUMENTO_INDEX =maxVersione.ID_TIPO_DOCUMENTO_INDEX
and PBANDI_T_DOCUMENTO_INDEX.ID_PROGETTO =maxVersione.ID_PROGETTO