SELECT PBANDI_R_FOLDER_FILE_DOC_INDEX.*,
  PBANDI_T_DOCUMENTO_INDEX.ID_TARGET,
  PBANDI_T_DOCUMENTO_INDEX.ID_ENTITA,
  PBANDI_T_DOCUMENTO_INDEX.ID_PROGETTO,
  PBANDI_T_PROGETTO.CODICE_VISUALIZZATO
FROM PBANDI_T_DOCUMENTO_INDEX
JOIN PBANDI_R_FOLDER_FILE_DOC_INDEX
ON (PBANDI_T_DOCUMENTO_INDEX.ID_DOCUMENTO_INDEX = PBANDI_R_FOLDER_FILE_DOC_INDEX.ID_DOCUMENTO_INDEX)
LEFT JOIN PBANDI_T_PROGETTO
ON (PBANDI_T_PROGETTO.ID_PROGETTO = PBANDI_T_DOCUMENTO_INDEX.ID_PROGETTO)