SELECT  
  PBANDI_T_PROGETTO.CODICE_VISUALIZZATO  AS CODICE_PROGETTO ,
  PBANDI_T_PROGETTO.TITOLO_PROGETTO,
  RBLI.NOME_BANDO_LINEA AS DESC_BANDO_LINEA,
  RBLI.PROGR_BANDO_LINEA_INTERVENTO AS PROGR_BANDO_LINEA_INTERVENTO,
  FORN.CODICE_FISCALE_FORNITORE AS CF_FORNITORE,
  NVL(FORN.DENOMINAZIONE_FORNITORE,FORN.COGNOME_FORNITORE
                                   ||' '
                                   ||FORN.NOME_FORNITORE) AS NOME_FORNITORE ,
QUALIFICA.DESC_QUALIFICA,
QUAL.PROGR_FORNITORE_QUALIFICA,
DOCINDEX.ID_DOCUMENTO_INDEX,
ID_SOGGETTO_BEN,
TFILE.NOME_FILE,
TFILE.SIZE_FILE,
TFILE.DT_INSERIMENTO  ,
TFILE.DT_AGGIORNAMENTO ,
FILE_ENTITA.ID_TARGET,
FILE_ENTITA.ID_ENTITA,
ID_FOLDER
FROM PBANDI_T_DOCUMENTO_INDEX DOCINDEX
JOIN PBANDI_T_FILE TFILE  ON (DOCINDEX.ID_DOCUMENTO_INDEX=TFILE.ID_DOCUMENTO_INDEX)
JOIN PBANDI_T_FILE_ENTITA FILE_ENTITA ON FILE_ENTITA.ID_FILE=TFILE.ID_FILE AND 
 FILE_ENTITA.ID_ENTITA=(SELECT ID_ENTITA FROM PBANDI_C_ENTITA WHERE UPPER(NOME_ENTITA)=UPPER('PBANDI_R_FORNITORE_QUALIFICA'))
JOIN PBANDI_T_FOLDER USING (ID_FOLDER)
JOIN PBANDI_R_FORNITORE_QUALIFICA QUAL ON (QUAL.PROGR_FORNITORE_QUALIFICA = FILE_ENTITA.ID_TARGET)
JOIN PBANDI_T_FORNITORE FORN ON (FORN.ID_FORNITORE = QUAL.ID_FORNITORE)
JOIN PBANDI_D_QUALIFICA QUALIFICA USING (ID_QUALIFICA)
JOIN PBANDI_T_PROGETTO ON FILE_ENTITA.ID_PROGETTO=PBANDI_T_PROGETTO.ID_PROGETTO
JOIN PBANDI_T_DOMANDA  ON PBANDI_T_PROGETTO.ID_DOMANDA= PBANDI_T_DOMANDA.ID_DOMANDA
JOIN PBANDI_R_BANDO_LINEA_INTERVENT RBLI ON PBANDI_T_DOMANDA.PROGR_BANDO_LINEA_INTERVENTO = RBLI.PROGR_BANDO_LINEA_INTERVENTO