SELECT DISTINCT
PBANDI_T_PROGETTO.CODICE_VISUALIZZATO  AS CODICE_PROGETTO ,
PBANDI_T_PROGETTO.TITOLO_PROGETTO,
PBANDI_D_STATO_DOCUMENTO_SPESA.DESC_BREVE_STATO_DOC_SPESA  ,
PBANDI_D_STATO_DOCUMENTO_SPESA.DESC_STATO_DOCUMENTO_SPESA  ,
PBANDI_D_TIPO_DOCUMENTO_SPESA.DESC_TIPO_DOCUMENTO_SPESA ,
PBANDI_T_FILE.DT_INSERIMENTO  ,
PBANDI_T_FILE.DT_AGGIORNAMENTO ,
PBANDI_T_DOCUMENTO_DI_SPESA.DT_EMISSIONE_DOCUMENTO ,
PBANDI_T_DOCUMENTO_DI_SPESA.NUMERO_DOCUMENTO ,
ID_TIPO_DOCUMENTO_SPESA,
PBANDI_T_DOCUMENTO_INDEX.ID_DOCUMENTO_INDEX ,
ID_DOCUMENTO_DI_SPESA  ,
PBANDI_T_DOCUMENTO_INDEX.ID_ENTITA ,
ID_FOLDER ,
ID_STATO_DOCUMENTO_SPESA  ,
PBANDI_T_FOLDER.ID_SOGGETTO_BEN ,
PBANDI_T_DOCUMENTO_INDEX.ID_TARGET ,
PBANDI_T_FILE.NOME_FILE  ,
PBANDI_T_FILE.SIZE_FILE ,
RBLI.NOME_BANDO_LINEA AS DESC_BANDO_LINEA,
RBLI.PROGR_BANDO_LINEA_INTERVENTO AS PROGR_BANDO_LINEA_INTERVENTO,
PBANDI_T_FORNITORE.CODICE_FISCALE_FORNITORE  AS CF_FORNITORE,
PBANDI_T_FORNITORE.ID_FORNITORE,
NVL(PBANDI_T_FORNITORE.DENOMINAZIONE_FORNITORE,PBANDI_T_FORNITORE.COGNOME_FORNITORE
  ||' '
  ||PBANDI_T_FORNITORE.NOME_FORNITORE) AS NOME_FORNITORE
FROM PBANDI_T_FILE  
JOIN PBANDI_T_DOCUMENTO_INDEX PBANDI_T_DOCUMENTO_INDEX ON (PBANDI_T_DOCUMENTO_INDEX.ID_DOCUMENTO_INDEX= PBANDI_T_FILE.ID_DOCUMENTO_INDEX)
JOIN PBANDI_T_FILE_ENTITA  
ON PBANDI_T_FILE_ENTITA.ID_FILE=PBANDI_T_FILE.ID_FILE AND PBANDI_T_FILE_ENTITA.ID_ENTITA=(SELECT ID_ENTITA FROM PBANDI_C_ENTITA WHERE upper(NOME_ENTITA)=UPPER('PBANDI_T_DOCUMENTO_DI_SPESA')) 
JOIN PBANDI_T_PROGETTO ON PBANDI_T_FILE_ENTITA.ID_PROGETTO=PBANDI_T_PROGETTO.ID_PROGETTO
JOIN PBANDI_R_DOC_SPESA_PROGETTO ON 
          (PBANDI_T_FILE_ENTITA.ID_TARGET=PBANDI_R_DOC_SPESA_PROGETTO.ID_DOCUMENTO_DI_SPESA
          AND PBANDI_T_FILE_ENTITA.ID_PROGETTO=PBANDI_R_DOC_SPESA_PROGETTO.ID_PROGETTO
          )
JOIN PBANDI_T_DOCUMENTO_DI_SPESA   USING (ID_DOCUMENTO_DI_SPESA)
JOIN PBANDI_D_STATO_DOCUMENTO_SPESA   USING(ID_STATO_DOCUMENTO_SPESA)
JOIN PBANDI_D_TIPO_DOCUMENTO_SPESA   USING(ID_TIPO_DOCUMENTO_SPESA)
JOIN PBANDI_T_FOLDER USING(ID_FOLDER)
JOIN PBANDI_T_DOMANDA  ON PBANDI_T_PROGETTO.ID_DOMANDA= PBANDI_T_DOMANDA.ID_DOMANDA
JOIN PBANDI_R_BANDO_LINEA_INTERVENT RBLI ON PBANDI_T_DOMANDA.PROGR_BANDO_LINEA_INTERVENTO = RBLI.PROGR_BANDO_LINEA_INTERVENTO
LEFT JOIN PBANDI_T_FORNITORE ON PBANDI_T_DOCUMENTO_DI_SPESA.ID_FORNITORE=PBANDI_T_FORNITORE.ID_FORNITORE