SELECT PBANDI_T_PAGAMENTO.ID_PAGAMENTO AS ID_PAGAMENTO,
  	PBANDI_T_PAGAMENTO.IMPORTO_PAGAMENTO AS IMPORTO_PAGAMENTO,
  	PBANDI_R_DOC_SPESA_PROGETTO.ID_DOCUMENTO_DI_SPESA,
  	PBANDI_R_DOC_SPESA_PROGETTO.ID_PROGETTO
  	/*,PBANDI_D_STATO_VALIDAZ_SPESA.ID_STATO_VALIDAZIONE_SPESA,
  	DESC_STATO_VALIDAZIONE_SPESA,
  	desc_breve_stato_validaz_spesa*/
FROM pbandi_t_pagamento,
	PBANDI_R_PAGAMENTO_DOC_SPESA,
	/*PBANDI_D_STATO_VALIDAZ_SPESA,*/
	PBANDI_R_DOC_SPESA_PROGETTO
WHERE PBANDI_R_PAGAMENTO_DOC_SPESA.ID_PAGAMENTO=PBANDI_T_PAGAMENTO.ID_PAGAMENTO
 /* AND PBANDI_T_PAGAMENTO.ID_STATO_VALIDAZIONE_SPESA = PBANDI_D_STATO_VALIDAZ_SPESA.ID_STATO_VALIDAZIONE_SPESA*/
  and PBANDI_R_DOC_SPESA_PROGETTO.ID_DOCUMENTO_DI_SPESA = PBANDI_R_PAGAMENTO_DOC_SPESA.ID_DOCUMENTO_DI_SPESA