SELECT DISTINCT	
  rdsp.note_validazione as note_validazione_doc,
  rpqpds.note_validazione as note_validazione_vds, 
  trunc(ds.DT_DICHIARAZIONE) dt_dich_spesa,
	trunc(ds.DT_CHIUSURA_VALIDAZIONE) dt_validazione,
  PBANDI_T_FORNITORE.CODICE_FISCALE_FORNITORE,
  DECODE(pbandi_t_fornitore.id_fornitore,NULL,NULL,pbandi_d_tipo_soggetto.desc_tipo_soggetto) AS desc_tipologia_fornitore,
  DECODE(pbandi_t_fornitore.id_fornitore,NULL,NULL,pbandi_d_tipo_soggetto.id_tipo_soggetto) AS id_tipo_fornitore,
  PBANDI_T_FORNITORE.NOME_FORNITORE,
  PBANDI_T_FORNITORE.COGNOME_FORNITORE,
  PBANDI_T_FORNITORE.DENOMINAZIONE_FORNITORE,
  DECODE(DECODE(pbandi_t_fornitore.id_fornitore,NULL,NULL,pbandi_d_tipo_soggetto.id_tipo_soggetto),1,PBANDI_T_FORNITORE.COGNOME_FORNITORE || ' ' || PBANDI_T_FORNITORE.NOME_FORNITORE,2,PBANDI_T_FORNITORE.DENOMINAZIONE_FORNITORE) AS desc_fornitore,
  PBANDI_D_STATO_DOCUMENTO_SPESA.DESC_STATO_DOCUMENTO_SPESA,
  PBANDI_D_TIPO_DOCUMENTO_SPESA.DESC_TIPO_DOCUMENTO_SPESA,
  PBANDI_D_TIPO_DOCUMENTO_SPESA.desc_breve_tipo_doc_spesa,
  PBANDI_T_DOCUMENTO_DI_SPESA.DT_EMISSIONE_DOCUMENTO,
  PBANDI_T_DOCUMENTO_DI_SPESA.DESC_DOCUMENTO,
  PBANDI_T_DOCUMENTO_DI_SPESA.DESTINAZIONE_TRASFERTA,
  PBANDI_T_DOCUMENTO_DI_SPESA.DURATA_TRASFERTA,
  PBANDI_T_DOCUMENTO_DI_SPESA.ID_DOC_RIFERIMENTO,
  PBANDI_T_DOCUMENTO_DI_SPESA.ID_DOCUMENTO_DI_SPESA,
  PBANDI_T_DOCUMENTO_DI_SPESA.ID_FORNITORE,
  PBANDI_T_DOCUMENTO_DI_SPESA.ID_SOGGETTO,
  PBANDI_T_DOCUMENTO_DI_SPESA.ID_TIPO_DOCUMENTO_SPESA,
  PBANDI_T_DOCUMENTO_DI_SPESA.ID_TIPO_OGGETTO_ATTIVITA,
  PBANDI_T_DOCUMENTO_DI_SPESA.ID_UTENTE_AGG,
  PBANDI_T_DOCUMENTO_DI_SPESA.ID_UTENTE_INS,
  PBANDI_T_DOCUMENTO_DI_SPESA.IMPONIBILE,
  PBANDI_T_DOCUMENTO_DI_SPESA.IMPORTO_IVA,
  PBANDI_T_DOCUMENTO_DI_SPESA.IMPORTO_IVA_COSTO,
  PBANDI_T_DOCUMENTO_DI_SPESA.IMPORTO_TOTALE_DOCUMENTO,
  PBANDI_T_DOCUMENTO_DI_SPESA.NUMERO_DOCUMENTO,
  rpds.id_dichiarazione_spesa,
  rdsp.task,
  tqpds.id_rigo_conto_economico,
  (
	SELECT DISTINCT
	  NVL2(P.DESC_VOCE_DI_SPESA_PADRE,
	       P.DESC_VOCE_DI_SPESA_PADRE || ' - ' || V.DESC_VOCE_DI_SPESA, V.DESC_VOCE_DI_SPESA) DESC_VOCE_DI_SPESA_COMPOSTA
	FROM
	  PBANDI_R_BANDO_VOCE_SPESA R,
	  PBANDI_D_VOCE_DI_SPESA V,
	  pbandi_t_rigo_conto_economico tr,
	  (
	    SELECT DESC_VOCE_DI_SPESA AS DESC_VOCE_DI_SPESA_PADRE,
	    ID_VOCE_DI_SPESA
	    FROM PBANDI_D_VOCE_DI_SPESA
	    WHERE NVL(TRUNC(PBANDI_D_VOCE_DI_SPESA.DT_FINE_VALIDITA), TRUNC(SYSDATE+1)) > TRUNC(SYSDATE)
	  ) P
	WHERE V.ID_VOCE_DI_SPESA = R.ID_VOCE_DI_SPESA
	AND P.ID_VOCE_DI_SPESA(+) = V.ID_VOCE_DI_SPESA_PADRE
	AND TQPDS.ID_RIGO_CONTO_ECONOMICO = TR.ID_RIGO_CONTO_ECONOMICO
	AND TR.ID_VOCE_DI_SPESA = V.ID_VOCE_DI_SPESA
  ) voce_di_spesa,
  SUM(rpqpds.importo_validato) OVER (partition by rpds.id_dichiarazione_spesa, PBANDI_T_DOCUMENTO_DI_SPESA.ID_DOCUMENTO_DI_SPESA) importo_validato_doc,
  SUM(rpqpds.importo_validato) OVER (partition by rpds.id_dichiarazione_spesa, PBANDI_T_DOCUMENTO_DI_SPESA.ID_DOCUMENTO_DI_SPESA, tqpds.id_rigo_conto_economico) importo_validato_voce,
  SUM(rpqpds.importo_quietanzato) OVER (partition by rpds.id_dichiarazione_spesa, PBANDI_T_DOCUMENTO_DI_SPESA.ID_DOCUMENTO_DI_SPESA, tqpds.id_rigo_conto_economico) importo_quietanzato_voce
FROM
  PBANDI_T_DOCUMENTO_DI_SPESA,
  PBANDI_D_TIPO_DOCUMENTO_SPESA,
  PBANDI_D_TIPO_SOGGETTO,
  PBANDI_T_FORNITORE,
  PBANDI_D_STATO_DOCUMENTO_SPESA,
  PBANDI_R_PAGAMENTO_DICH_SPESA rpds,
  PBANDI_R_DOC_SPESA_PROGETTO rdsp,
  PBANDI_R_PAGAMENTO_DOC_SPESA rpag,
  PBANDI_T_QUOTA_PARTE_DOC_SPESA tqpds,
  PBANDI_R_PAG_QUOT_PARTE_DOC_SP rpqpds,
  PBANDI_T_DICHIARAZIONE_SPESA ds 
WHERE rdsp.ID_STATO_DOCUMENTO_SPESA_VALID = PBANDI_D_STATO_DOCUMENTO_SPESA.ID_STATO_DOCUMENTO_SPESA
AND PBANDI_T_DOCUMENTO_DI_SPESA.ID_DOCUMENTO_DI_SPESA  = rdsp.ID_DOCUMENTO_DI_SPESA
and rpds.id_pagamento (+) = rpag.id_pagamento
and tqpds.id_documento_di_spesa = rdsp.id_documento_di_spesa
and tqpds.id_progetto = rdsp.id_progetto
and rpqpds.ID_PAGAMENTO = rpag.id_pagamento
and rpqpds.ID_QUOTA_PARTE_DOC_SPESA = tqpds.ID_QUOTA_PARTE_DOC_SPESA
AND PBANDI_T_DOCUMENTO_DI_SPESA.ID_TIPO_DOCUMENTO_SPESA = PBANDI_D_TIPO_DOCUMENTO_SPESA.ID_TIPO_DOCUMENTO_SPESA
AND PBANDI_T_DOCUMENTO_DI_SPESA.ID_FORNITORE = PBANDI_T_FORNITORE.ID_FORNITORE (+)
AND ds.ID_DICHIARAZIONE_SPESA=rpds.ID_DICHIARAZIONE_SPESA 
AND pbandi_d_tipo_soggetto.id_tipo_soggetto(+) = pbandi_t_fornitore.id_tipo_soggetto 
and ds.id_progetto = rdsp.id_progetto
AND NVL(TRUNC(PBANDI_D_TIPO_SOGGETTO.DT_FINE_VALIDITA), TRUNC(sysdate+1)) > TRUNC(sysdate)
AND NVL(TRUNC(PBANDI_D_STATO_DOCUMENTO_SPESA.DT_FINE_VALIDITA), TRUNC(sysdate+1)) > TRUNC(sysdate)
AND NVL(TRUNC(PBANDI_D_TIPO_DOCUMENTO_SPESA.DT_FINE_VALIDITA), TRUNC(sysdate +1)) > TRUNC(sysdate)