SELECT RBL.*,
  RIGO.ID_VOCE_DI_SPESA
FROM PBANDI_R_BANDO_LINEA_INTERVENT RBL,
  PBANDI_T_DOMANDA DOMANDA,
  PBANDI_T_CONTO_ECONOMICO CONTO,
  PBANDI_T_RIGO_CONTO_ECONOMICO RIGO
WHERE RBL.PROGR_BANDO_LINEA_INTERVENTO = DOMANDA.PROGR_BANDO_LINEA_INTERVENTO
AND DOMANDA.ID_DOMANDA                 = CONTO.ID_DOMANDA
AND RIGO.ID_CONTO_ECONOMICO            = CONTO.ID_CONTO_ECONOMICO

AND NVL(TRUNC(CONTO.DT_FINE_VALIDITA), TRUNC(SYSDATE+1)) > TRUNC(SYSDATE)
AND NVL(TRUNC(RIGO.DT_FINE_VALIDITA), TRUNC(SYSDATE+1)) > TRUNC(SYSDATE)