/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

DECLARE
  CURSOR curConto IS SELECT ce.*,nvl(d.DT_PRESENTAZIONE_DOMANDA,ce.DT_INIZIO_VALIDITA) data_inizio,
							NVL(DT_CONCESSIONE,nvl(DT_COMITATO,SYSDATE)) DATA_FINE
					 FROM   PBANDI_T_CONTO_ECONOMICO ce,PBANDI_T_DOMANDA d,PBANDI_T_PROGETTO p
					 WHERE  ce.ID_DOMANDA = d.ID_DOMANDA
					 AND    p.ID_DOMANDA  = d.ID_DOMANDA;
  
  nIdContoEconomicoNew   PBANDI_T_CONTO_ECONOMICO.ID_CONTO_ECONOMICO%type;
BEGIN
  FOR recConto IN curConto LOOP
    INSERT INTO PBANDI_T_CONTO_ECONOMICO
    (ID_CONTO_ECONOMICO, COSTO_TOT_AMMESSO_FINANZIAMEN, ID_UTENTE_INS, 
     ID_UTENTE_AGG, DT_INIZIO_VALIDITA, DT_FINE_VALIDITA, ID_DOMANDA, 
     ID_STATO_CONTO_ECONOMICO, COSTO_TOTALE_RECUPERATO, 
     IMPORTO_FINANZIAMENTO_BANCA, IMPORTO_FINANZ_BANCA_RICHIESTO)
    VALUES
	(SEQ_PBANDI_T_CONTO_ECONOMICO.nextval,recConto.COSTO_TOT_AMMESSO_FINANZIAMEN,recConto.ID_UTENTE_INS,
	 NULL,recConto.data_inizio,recConto.DATA_FINE,recConto.ID_DOMANDA, 
     7, recConto.COSTO_TOTALE_RECUPERATO, 
     recConto.IMPORTO_FINANZIAMENTO_BANCA, recConto.IMPORTO_FINANZ_BANCA_RICHIESTO)
	RETURNING ID_CONTO_ECONOMICO INTO nIdContoEconomicoNew;
    
	INSERT INTO PBANDI_T_RIGO_CONTO_ECONOMICO
    (ID_RIGO_CONTO_ECONOMICO, IMPORTO_SPESA, IMPORTO_AMMESSO_FINANZIAMENTO, 
	 IMPORTO_CONTRIBUTO, ID_UTENTE_INS, ID_UTENTE_AGG, DT_INIZIO_VALIDITA, 
	 DT_FINE_VALIDITA, ID_CONTO_ECONOMICO, ID_VOCE_DI_SPESA)
    (SELECT SEQ_PBANDI_T_RIGO_CONTO_ECONOM.NEXTVAL, IMPORTO_SPESA, IMPORTO_AMMESSO_FINANZIAMENTO, 
	  	    IMPORTO_CONTRIBUTO, ID_UTENTE_INS, null, recConto.data_inizio, 
		    DT_FINE_VALIDITA, nIdContoEconomicoNew, ID_VOCE_DI_SPESA
	 FROM   PBANDI_T_RIGO_CONTO_ECONOMICO
	 WHERE  ID_CONTO_ECONOMICO = recConto.Id_Conto_Economico); 
  END LOOP;
END;
  