/*******************************************************************************
* Copyright Regione Piemonte - 2024
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

CREATE TABLE SAP_EROGAZIONI
(
  NOME_PARTNER    VARCHAR2(100 BYTE)            NOT NULL,
  IDENTIFICATIVO  VARCHAR2(15 BYTE)             NOT NULL,
  IMPORTO         VARCHAR2(10 BYTE)             NOT NULL,
  DATA_CONTABILE  VARCHAR2(19 BYTE)             NOT NULL,
  CAUSALE         VARCHAR2(1 BYTE)              NOT NULL,
  TIPO_AGEV       VARCHAR2(1 BYTE)              NOT NULL,
  FIDEJUSSIONE    VARCHAR2(5 BYTE)              NOT NULL,
  ID_PROGETTO     NUMBER(8)
);

SET DEFINE OFF;
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('UNIVERSITA'' DI TORINO', '0127000003-01/B', '50825', '2009-08-23T00:00:00', '4', '1', 'FALSE', 821);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('CNR ISTEC', '0127000003-01/C', '54928,5', '2009-08-23T00:00:00', '4', '1', 'FALSE', 822);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('OFFICINE MECCANICHE CARPENTERIE MONREGALESI SNC', '0127000007-01/C', '82828', '2009-08-23T00:00:00', '4', '1', 'TRUE', 838);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('POLITECNICO DI TORINO', '0127000010-01/B', '179305', '2009-08-23T00:00:00', '4', '1', 'FALSE', 850);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('POLITECNICO DI TORINO', '0127000010-01/C', '34282,5', '2009-08-23T00:00:00', '4', '1', 'FALSE', 851);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('FN NUOVE TECNOLOGIE E SISTEMI AVANZATI SPA', '0127000010-01/E', '148107,5', '2009-08-23T00:00:00', '4', '1', 'TRUE', 853);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('Faiveley Transport Italia', '0127000013-01/A', '137991,76', '2009-08-23T00:00:00', '4', '1', 'TRUE', 861);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('POLITECNICO DI TORINO', '0127000013-01/B', '89609,03', '2009-08-23T00:00:00', '4', '1', 'FALSE', 862);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('POLITECNICO DI TORINO', '0127000013-01/C', '89428,15', '2009-08-23T00:00:00', '4', '1', 'FALSE', 863);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('CHINOOK', '0127000013-01/D', '121748,02', '2009-08-23T00:00:00', '4', '1', 'TRUE', 864);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('SPEA', '0127000015-01/A', '303251,8', '2009-08-23T00:00:00', '4', '1', 'TRUE', 875);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('POLITECNICO DI TORINO', '0127000015-01/B', '161905,85', '2009-08-23T00:00:00', '4', '1', 'FALSE', 876);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('CONSOFT SISTEMI', '0127000021-01/A', '90737,5', '2009-08-23T00:00:00', '4', '1', 'TRUE', 904);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('POLITECNICO DI TORINO', '0127000021-01/B', '30327,5', '2009-08-23T00:00:00', '4', '1', 'FALSE', 905);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('ISTITUTO SUPERIORE MARIO BOELLA', '0127000021-01/C', '130060', '2009-08-23T00:00:00', '4', '1', 'TRUE', 906);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('CR & S', '0127000021-01/D', '23560,65', '2009-08-23T00:00:00', '4', '1', 'TRUE', 907);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('ERPLAN SRL', '0127000021-01/E', '59375', '2009-08-23T00:00:00', '4', '1', 'TRUE', 908);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('TESEO', '0127000022-01/A', '144733,5', '2009-08-23T00:00:00', '4', '1', 'TRUE', 909);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('SKF SPA', '0127000022-01/C', '42704', '2009-08-23T00:00:00', '4', '1', 'TRUE', 911);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('POLITECNICO DI TORINO', '0127000022-01/B', '59500', '2009-08-23T00:00:00', '4', '1', 'FALSE', 910);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('INTRAUMA srl', '0127000003-01/A', '374263,13', '2009-08-23T00:00:00', '4', '1', 'TRUE', 820);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('MICHELIN ITALIANA S.A.M.I', '0127000007-01/A', '59760,5', '2009-08-23T00:00:00', '4', '1', 'TRUE', 836);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('TECNOGRANDA', '0127000007-01/B', '60695', '2009-08-23T00:00:00', '4', '1', 'TRUE', 837);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('INTEGRA renewable energies', '0127000025-01/A', '400000', '2009-08-23T00:00:00', '4', '1', 'TRUE', 917);
Insert into SAP_EROGAZIONI
   (NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE, ID_PROGETTO)
 Values
   ('MUSEO DELL''UOMO E DELLA FRUTTA - UNIVERSITA DI TORINO', '0127000025-01/B', '100000', '2009-08-23T00:00:00', '4', '1', 'FALSE', 918);

Insert into SAP_EROGAZIONI(NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE) Values('E.N.E.A.',             '0127000019-01/B','107815,00','2009-10-25T00:00:00','4','1','FALSE'); 
Insert into SAP_EROGAZIONI(NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE) Values('POLITECNICO DI TORINO','0127000019-01/C','53956,87', '2009-10-25T00:00:00','4','1','FALSE'); 
Insert into SAP_EROGAZIONI(NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE) Values('CAMPIA IMBALLAGGI',    '0127000023-01/A','95368,25', '2009-10-25T00:00:00','4','1','TRUE' );
Insert into SAP_EROGAZIONI(NOME_PARTNER, IDENTIFICATIVO, IMPORTO, DATA_CONTABILE, CAUSALE, TIPO_AGEV, FIDEJUSSIONE) Values('POLITECNICO DI TORINO','0127000023-01/B','43750,00', '2009-10-25T00:00:00','4','1','FALSE');
COMMIT;


update SAP_EROGAZIONI
set ID_PROGETTO = null;

declare
  cursor curErog is select * from sap_erogazioni where id_progetto is not null;
  
  nIdTipoTrattamento     PBANDI_T_FIDEIUSSIONE.ID_TIPO_TRATTAMENTO%TYPE;
  nIdErogazione          PBANDI_T_EROGAZIONE.ID_EROGAZIONE%TYPE;        
  nIdFideiussione        PBANDI_T_FIDEIUSSIONE.ID_FIDEIUSSIONE%TYPE;  
begin
  for recErog in curErog loop
    BEGIN
      SELECT e.ID_EROGAZIONE
      INTO   nIdErogazione
      FROM   PBANDI_T_EROGAZIONE e  
      WHERE  e.ID_PROGETTO                = recErog.Id_Progetto
      AND    e.COD_RIFERIMENTO_EROGAZIONE = recErog.Identificativo;
      
      UPDATE PBANDI_T_EROGAZIONE
      SET    COD_RIFERIMENTO_EROGAZIONE = recErog.Identificativo,
             DT_CONTABILE               = PCK_PBANDI_UTILITY_BATCH.returnDateTime(recErog.Data_Contabile),
             IMPORTO_EROGAZIONE         = to_number(recErog.Importo),
             ID_CAUSALE_EROGAZIONE      = recErog.Causale,
             ID_MODALITA_AGEVOLAZIONE   = recErog.Tipo_Agev,
             ID_MODALITA_EROGAZIONE     = 1,
             ID_UTENTE_AGG              = 2
      WHERE  ID_PROGETTO                = recErog.Id_Progetto
      AND    COD_RIFERIMENTO_EROGAZIONE = recErog.Identificativo;       

    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        INSERT INTO PBANDI_T_EROGAZIONE
        (ID_EROGAZIONE, IMPORTO_EROGAZIONE, 
         COD_RIFERIMENTO_EROGAZIONE,DT_CONTABILE, 
         ID_CAUSALE_EROGAZIONE, ID_MODALITA_AGEVOLAZIONE, 
         ID_PROGETTO, ID_UTENTE_INS, ID_MODALITA_EROGAZIONE)
        VALUES
        (SEQ_PBANDI_T_EROGAZIONE.NEXTVAL,to_number(recErog.Importo),
         recErog.Identificativo,PCK_PBANDI_UTILITY_BATCH.returnDateTime(recErog.Data_Contabile),
         recErog.Causale,recErog.Tipo_Agev,
         recErog.Id_Progetto,2,1);
    END;
    
    IF recErog.Fidejussione = 'TRUE' THEN
      IF recErog.Causale = 1 THEN
        nIdTipoTrattamento := 1;
      ELSIF recErog.Causale IN (2,3) THEN
        nIdTipoTrattamento := 2;  
      ELSIF recErog.Causale = 4 THEN
        nIdTipoTrattamento := 3;  
      ELSE
        nIdTipoTrattamento := NULL;
      END IF;
        
      BEGIN
        SELECT ID_FIDEIUSSIONE
        INTO   nIdFideiussione 
        FROM   PBANDI_T_FIDEIUSSIONE 
        WHERE  ID_PROGETTO                  = recErog.Id_Progetto
        AND    COD_RIFERIMENTO_FIDEIUSSIONE = recErog.Identificativo;
        
        UPDATE PBANDI_T_FIDEIUSSIONE
        SET    IMPORTO_FIDEIUSSIONE         = to_number(recErog.Importo),
               COD_RIFERIMENTO_FIDEIUSSIONE = recErog.Identificativo,
               DT_DECORRENZA                = PCK_PBANDI_UTILITY_BATCH.returnDateTime(recErog.Data_Contabile),
               NOTE_FIDEIUSSIONE            = 'Fideiussione generata in automatico dal sistema',
               ID_TIPO_TRATTAMENTO          = nIdTipoTrattamento,
               ID_UTENTE_AGG                = 2
        WHERE  ID_PROGETTO                  = recErog.Id_Progetto
        AND    COD_RIFERIMENTO_FIDEIUSSIONE = recErog.Identificativo;               

      EXCEPTION
        WHEN NO_DATA_FOUND THEN
          INSERT INTO PBANDI_T_FIDEIUSSIONE
          (ID_FIDEIUSSIONE, IMPORTO_FIDEIUSSIONE, 
           COD_RIFERIMENTO_FIDEIUSSIONE,DT_DECORRENZA, 
           NOTE_FIDEIUSSIONE, ID_TIPO_TRATTAMENTO, 
           ID_PROGETTO,ID_UTENTE_INS)
          VALUES
          (SEQ_PBANDI_T_FIDEIUSSIONE.NEXTVAL,to_number(recErog.Importo),
           recErog.Identificativo,PCK_PBANDI_UTILITY_BATCH.returnDateTime(recErog.Data_Contabile),
           'Fideiussione generata in automatico dal sistema',nIdTipoTrattamento,
           recErog.Id_Progetto,2); 
      END;    
    END IF;  
  END LOOP;
EXCEPTION
  WHEN OTHERS THEN
    dbms_output.PUT_LINE('errore = '||sqlerrm);
    rollback;
end;
/
