SELECT DOCIND.id_Entita as idEntita,DOCIND.id_target as idTarget,DOCIND.id_progetto idProgetto,DOCIND.num_protocollo numProtocollo
	,ID_FOLDER as idFolder,ID_DOCUMENTO_INDEX as idDocumentoIndex,PBANDI_T_FILE.NOME_FILE AS nomeFile
	,SIZE_FILE as sizeFile,PBANDI_T_FILE.ID_UTENTE_INS AS idUtenteIns
	,DT_INSERIMENTO dtInserimento,PBANDI_T_FILE.ID_UTENTE_AGG AS idUtenteAgg,DT_AGGIORNAMENTO dtAggiornamento
	,PBANDI_T_FILE_ENTITA.ID_FILE_ENTITA as idFileEntita
 FROM 
 PBANDI_T_FILE
 JOIN
 	PBANDI_T_DOCUMENTO_INDEX DOCIND using (ID_DOCUMENTO_INDEX)
 JOIN
 	PBANDI_T_FILE_ENTITA using (ID_FILE) 
WHERE (PBANDI_T_FILE_ENTITA.ID_TARGET = ?
 	AND PBANDI_T_FILE_ENTITA.ID_ENTITA = (SELECT ID_ENTITA FROM PBANDI_C_ENTITA 
 						WHERE NOME_ENTITA='PBANDI_T_APPALTO'))
ORDER BY  PBANDI_T_FILE_ENTITA.DT_ENTITA, nomeFile
