SELECT DISTINCT PBANDI_T_FORNITORE.CODICE_FISCALE_FORNITORE as codiceFiscaleFornitore, PBANDI_T_FORNITORE.COGNOME_FORNITORE as cognomeFornitore, PBANDI_T_FORNITORE.DENOMINAZIONE_FORNITORE as denominazioneFornitore, PBANDI_T_FORNITORE.ID_FORNITORE as idFornitore, PBANDI_T_FORNITORE.ID_TIPO_SOGGETTO as idTipoSoggetto, PBANDI_T_FORNITORE.NOME_FORNITORE as nomeFornitore, PBANDI_T_FORNITORE.PARTITA_IVA_FORNITORE as partitaIvaFornitore, PBANDI_T_FORNITORE.ID_FORMA_GIURIDICA as idFormaGiuridica, PBANDI_T_FORNITORE.ID_ATTIVITA_ATECO as idAttivitaAteco, PBANDI_T_FORNITORE.ID_NAZIONE as idNazione, PBANDI_T_FORNITORE.ALTRO_CODICE as altroCodice, PBANDI_D_TIPO_SOGGETTO.DESC_TIPO_SOGGETTO as descTipoSoggetto, PBANDI_D_QUALIFICA.DESC_QUALIFICA as descQualifica, PBANDI_D_QUALIFICA.ID_QUALIFICA as idQualifica, PBANDI_T_FORNITORE.DT_FINE_VALIDITA as dtFineValidita, PBANDI_T_FORNITORE.FLAG_PUBBLICO_PRIVATO as flagPubblicoPrivato, PBANDI_T_FORNITORE.COD_UNI_IPA as codUniIpa
FROM PBANDI_T_FORNITORE,PBANDI_D_TIPO_SOGGETTO,PBANDI_R_FORNITORE_QUALIFICA,PBANDI_D_QUALIFICA
WHERE PBANDI_T_FORNITORE.ID_TIPO_SOGGETTO=PBANDI_D_TIPO_SOGGETTO.ID_TIPO_SOGGETTO
AND PBANDI_T_FORNITORE.ID_FORNITORE=PBANDI_R_FORNITORE_QUALIFICA.ID_FORNITORE(+)
AND PBANDI_R_FORNITORE_QUALIFICA.ID_QUALIFICA =PBANDI_D_QUALIFICA.ID_QUALIFICA(+)
AND nvl(trunc(PBANDI_T_FORNITORE.DT_FINE_VALIDITA), trunc(sysdate+1)) > trunc(sysdate)
AND nvl(trunc(PBANDI_D_TIPO_SOGGETTO.DT_FINE_VALIDITA), trunc(sysdate+1)) > trunc(sysdate)
AND nvl(trunc(PBANDI_D_QUALIFICA.DT_FINE_VALIDITA), trunc(sysdate+1)) > trunc(sysdate)
