select DESC_TIPO_PERCETTORE as descTipoPercettore , ID_TIPO_SOGGETTO as idTipoSoggetto , DT_INVIO_VERIFICA_AFFIDAMENTO as dtInvioVerificaAffidamento , PARTITA_IVA_FORNITORE as partitaIvaFornitore , ID_TIPO_PERCETTORE as idTipoPercettore , DENOMINAZIONE_FORNITORE as denominazioneFornitore , CODICE_FISCALE_FORNITORE as codiceFiscaleFornitore , NOME_FORNITORE as nomeFornitore , ID_FORNITORE as idFornitore , ID_APPALTO as idAppalto , COGNOME_FORNITORE as cognomeFornitore , FLG_INVIO_VERIFICA_AFFIDAMENTO as flgInvioVerificaAffidamento from (
select rfa.ID_FORNITORE, rfa.ID_APPALTO, rfa.ID_TIPO_PERCETTORE,
       rfa.DT_INVIO_VERIFICA_AFFIDAMENTO, rfa.FLG_INVIO_VERIFICA_AFFIDAMENTO,
       dtp.DESC_TIPO_PERCETTORE,
       tf.ID_TIPO_SOGGETTO,
       tf.NOME_FORNITORE, tf.COGNOME_FORNITORE, tf.CODICE_FISCALE_FORNITORE,
       tf.DENOMINAZIONE_FORNITORE,
       tf.PARTITA_IVA_FORNITORE
from PBANDI_R_FORNITORE_AFFIDAMENTO rfa, PBANDI_D_TIPO_PERCETTORE dtp, PBANDI_T_FORNITORE tf
where dtp.ID_TIPO_PERCETTORE = rfa.ID_TIPO_PERCETTORE
  and tf.ID_FORNITORE = rfa.ID_FORNITORE
) where ID_APPALTO = ?