INSERT INTO PBANDI_T_PROCEDURA_AGGIUDICAZ 
(DT_AGGIUDICAZIONE , IMPORTO , ID_MOTIVO_ASSENZA_CIG , ID_PROCEDURA_AGGIUDICAZ ,
 ID_TIPOLOGIA_AGGIUDICAZ , COD_PROC_AGG , ID_UTENTE_INS , DESC_PROC_AGG , 
 ID_PROGETTO , DT_INIZIO_VALIDITA) 
VALUES (? , ? , ? , ? , ? , ? , ? , ? , ? , ?)