INSERT INTO 
PBANDI_T_APPALTO 
(IMPORTO_CONTRATTO , ID_TIPO_AFFIDAMENTO , OGGETTO_APPALTO , ID_TIPOLOGIA_APPALTO ,
 DT_FIRMA_CONTRATTO , DT_INSERIMENTO , ID_STATO_AFFIDAMENTO , BILANCIO_PREVENTIVO ,
  IMP_RENDICONTABILE , ID_PROCEDURA_AGGIUDICAZ , INTERVENTO_PISU , ID_NORMA ,
   ID_UTENTE_INS , DT_INIZIO_PREVISTA , ID_APPALTO , SOPRA_SOGLIA) 
   VALUES (? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ?)