UPDATE PBANDI_T_PROPOSTA_CERTIFICAZ 
SET DT_ORA_CREAZIONE = (?) ,
 DT_CUT_OFF_VALIDAZIONI = (?) ,
  DT_CUT_OFF_FIDEIUSSIONI = (?) ,
   ID_STATO_PROPOSTA_CERTIF = ? , 
   DT_CUT_OFF_PAGAMENTI = (?) ,
    ID_UTENTE_AGG = ? , DT_CUT_OFF_EROGAZIONI = (?) ,
     DESC_PROPOSTA = ? 
WHERE ID_PROPOSTA_CERTIFICAZ = ?