select DT_ORA_CREAZIONE as dtOraCreazione , ID_PERIODO as idPeriodo , DESC_PERIODO_VISUALIZZATA as descPeriodoVisualizzata , ID_STATO_PROPOSTA_CERTIF as idStatoPropostaCertif , ID_PROPOSTA_CERTIFICAZ as idPropostaCertificaz , DT_INIZIO_VALIDITA as dtInizioValidita , ID_TIPO_PERIODO as idTipoPeriodo , DESC_PROPOSTA as descProposta , DT_FINE_VALIDITA as dtFineValidita , DESC_PERIODO as descPeriodo from (
SELECT t.ID_PROPOSTA_CERTIFICAZ,
        t.DESC_PROPOSTA,
        t.DT_ORA_CREAZIONE,
        ID_STATO_PROPOSTA_CERTIF,
        p.ID_PERIODO,
        ID_TIPO_PERIODO,
        DESC_PERIODO,
        DESC_PERIODO_VISUALIZZATA,
        DT_INIZIO_VALIDITA,
        DT_FINE_VALIDITA
from PBANDI_T_PROPOSTA_CERTIFICAZ t, PBANDI_T_PERIODO p
 WHERE p.ID_PERIODO = t.ID_PERIODO
) where ID_PROPOSTA_CERTIFICAZ = ?