SELECT p.*, r.ID_LINEA_DI_INTERVENTO, s.DESC_BREVE_STATO_PROPOSTA_CERT, s.DESC_STATO_PROPOSTA_CERTIF 
	FROM PBANDI_T_PROPOSTA_CERTIFICAZ p, PBANDI_R_PROPOSTA_CERTIF_LINEA r, PBANDI_D_STATO_PROPOSTA_CERTIF s 
	WHERE 	p.ID_PROPOSTA_CERTIFICAZ=r.ID_PROPOSTA_CERTIFICAZ 
		AND p.ID_STATO_PROPOSTA_CERTIF = s.ID_STATO_PROPOSTA_CERTIF 
		AND p.ID_PROPOSTA_CERTIFICAZ = ? 